// examples/vue/src/Provider/Sidebar.vue
<script lang="ts" setup>
import type { Node } from '@xyflow/vue';
import { storeToRefs, useStore, useVueFlow } from '@xyflow/vue';

const { addSelectedNodes, getNodes, viewport } = useVueFlow();

const { nodesSelectionActive } = storeToRefs(useStore());

function selectAll() {
  addSelectedNodes(getNodes.value as unknown as Node[]);
  nodesSelectionActive.value = true;
}
</script>

<template>
  <aside>
    <div class="description">
      This is an example of how you can access the internal state outside of the Vue VueFlow component.
    </div>
    <div class="title">
      Zoom & pan transform
    </div>
    <div class="transform">
      {{ [viewport.x.toFixed(2), viewport.y.toFixed(2), viewport.zoom.toFixed(2)] }}
    </div>
    <div class="title">
      Nodes
    </div>
    <div v-for="node of getNodes" :key="node.id">
      Node {{ node.id }} - x: {{ node.position.x.toFixed(2) }}, y: {{ node.position.y.toFixed(2) }}
    </div>

    <div class="selectall">
      <button @click="selectAll">
        select all nodes
      </button>
    </div>
  </aside>
</template>

// examples/vite-app/src/examples/Provider/Sidebar.tsx
import { useReactFlow, useStore } from '@xyflow/react';

import styles from './provider.module.css';

const Sidebar = () => {
  const { setNodes } = useReactFlow();
  const nodeInfos = useStore((store) =>
    store.getNodes().map((n) => `Node ${n.id} - x: ${n.position.x.toFixed(2)}, y: ${n.position.y.toFixed(2)}`)
  );
  const transform = useStore((store) => store.transform);

  const selectAll = () => {
    setNodes((nodes) => nodes.map((n) => ({ ...n, selected: true })));
  };

  return (
    <aside className={styles.aside}>
      <div className={styles.description}>
        This is an example of how you can access the internal state outside of the ReactFlow component.
      </div>
      <div className={styles.title}>Zoom & pan transform</div>
      <div className={styles.transform}>
        [{transform[0].toFixed(2)}, {transform[1].toFixed(2)}, {transform[2].toFixed(2)}]
      </div>
      <div className={styles.title}>Nodes</div>
      {nodeInfos.map((info, index) => (
        <div key={index}>{info}</div>
      ))}

      <div className={styles.selectall}>
        <button onClick={selectAll}>select all nodes</button>
      </div>
    </aside>
  );
};

export default Sidebar;
