// packages/angular/src/lib/components/plugins/panel.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'angular-flow-panel',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="angular-flow__panel" [class]="'angular-flow__panel-' + position">
      <ng-content></ng-content>
    </div>
  `,
  styles: [`
    .angular-flow__panel {
      position: absolute;
      z-index: 1000;
      padding: 16px;
    }

    .angular-flow__panel-top-left {
      top: 16px;
      left: 16px;
    }

    .angular-flow__panel-top-center {
      top: 16px;
      left: 50%;
      transform: translateX(-50%);
    }

    .angular-flow__panel-top-right {
      top: 16px;
      right: 16px;
    }

    .angular-flow__panel-bottom-left {
      bottom: 16px;
      left: 16px;
    }

    .angular-flow__panel-bottom-center {
      bottom: 16px;
      left: 50%;
      transform: translateX(-50%);
    }

    .angular-flow__panel-bottom-right {
      bottom: 16px;
      right: 16px;
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PanelComponent {
  @Input() position: 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right' = 'top-left';
}

// packages/svelte/src/lib/container/Panel/index.svelte
<script lang="ts">
  import cc from 'classcat';
  import type { PanelProps } from './Panel';

  interface $$Props extends PanelProps {}

  export let position: $$Props['position'] = 'top-right';
  export let style: $$Props['style'] = '';
  let className: $$Props['class'] = undefined;
  export { className as class };

  $: positionClasses = `${position}`.split('-');
</script>

<div class={cc(['react-flow__panel', className, ...positionClasses])} {style}>
  <slot />
</div>

<style>
  .react-flow__panel {
    position: absolute;
    z-index: 5;
    margin: 15px;
  }

  .react-flow__panel.top {
    top: 0;
  }

  .react-flow__panel.bottom {
    bottom: 0;
  }

  .react-flow__panel.left {
    left: 0;
  }

  .react-flow__panel.right {
    right: 0;
  }

  .react-flow__panel.center {
    left: 50%;
    transform: translateX(-50%);
  }
</style>
