// src/container/Viewport/index.tsx
import React, { ReactNode } from 'react';

import { useStore } from '../../store';
import { ReactFlowState } from '../../types';

const selector = (s: ReactFlowState) => s.transform;

type ViewportProps = {
  children: ReactNode;
};

function Viewport({ children }: ViewportProps) {
  const transform = useStore(selector);

  return (
    <div
      className="react-flow__viewport react-flow__container"
      style={{ transform: `translate(${transform[0]}px,${transform[1]}px) scale(${transform[2]})` }}
    >
      {children}
    </div>
  );
}

export default Viewport;

// packages/solidjs/src/container/Viewport/index.tsx

import { useStore } from '../../hooks/useStore';
import type { SolidFlowState } from '../../types';
import { ParentProps } from 'solid-js';

const selector = (s: SolidFlowState) => () => `translate(${s.transform.get()[0]}px,${s.transform.get()[1]}px) scale(${s.transform.get()[2]})`;


export function Viewport(p: ParentProps) {
  const transform = useStore(selector);

  return (
    <div class="react-flow__viewport xyflow__viewport react-flow__container" style={{ transform: transform() }}>
      {p.children}
    </div>
  );
}
