// packages/solidjs/src/additional-components/Controls/ControlButton.tsx
import cc from 'classcat';

import type { ControlButtonProps } from './types';
import { splitProps } from 'solid-js';

export function ControlButton(p: ControlButtonProps) {
  // { children, className, ...rest }: ControlButtonProps) {
    const [_, rest] = splitProps(p, ['children', 'class']);

  return (
    <button type="button" class={cc(['react-flow__controls-button', p.class])} {...rest}>
      {p.children}
    </button>
  );
}

// packages/react/src/additional-components/Controls/ControlButton.tsx
import cc from 'classcat';

import type { ControlButtonProps } from './types';

export function ControlButton({ children, className, ...rest }: ControlButtonProps) {
  return (
    <button type="button" className={cc(['react-flow__controls-button', className])} {...rest}>
      {children}
    </button>
  );
}
