// examples/svelte/src/routes/custom-connection-line/+page.svelte
<script lang="ts">
	import { SvelteFlow } from '@xyflow/svelte';
	import { Background, BackgroundVariant, type Edge, type Node } from '@xyflow/svelte';
	import { writable } from 'svelte/store';

	import CustomNode from './CustomNode.svelte';
	import ConnectionLine from './ConnectionLine.svelte';

	import '@xyflow/svelte/dist/style.css';

	const nodeTypes = {
		custom: CustomNode
	};

	const nodes = writable<Node[]>([
		{
			id: 'connectionline-1',
			type: 'custom',
			data: { label: 'Node 1' },
			position: { x: 250, y: 5 }
		}
	]);

	const edges = writable<Edge[]>([]);
</script>

<div style="height:100vh;">
	<SvelteFlow {nodeTypes} {nodes} {edges} fitView>
		<ConnectionLine slot="connectionLineComponent" />
		<Background variant={BackgroundVariant.Lines} />
	</SvelteFlow>
</div>

<style>
</style>

// examples/nextjs/pages/CustomConnectionLine/index.tsx
import React, { useCallback } from 'react';
import {
  ReactFlow,
  Node,
  addEdge,
  Connection,
  Edge,
  useNodesState,
  useEdgesState,
  Background,
  BackgroundVariant,
} from 'reactflow';

import ConnectionLine from './ConnectionLine';

const initialNodes: Node[] = [
  {
    id: '1',
    type: 'default',
    data: { label: 'Node 1' },
    position: { x: 250, y: 5 },
  },
];
const initialEdges: Edge[] = [];

const ConnectionLineFlow = () => {
  const [nodes, , onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const onConnect = useCallback((params: Connection | Edge) => setEdges((eds) => addEdge(params, eds)), [setEdges]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      connectionLineComponent={ConnectionLine}
      onConnect={onConnect}
    >
      <Background variant={BackgroundVariant.Lines} />
    </ReactFlow>
  );
};

export default ConnectionLineFlow;
