// examples/svelte/src/routes/examples/overview/CustomEdge.svelte
<script lang="ts">
	import {
		BaseEdge,
		EdgeLabelRenderer,
		useEdges,
		type EdgeProps,
		getBezierPath
	} from '@xyflow/svelte';

	type $$Props = EdgeProps;

	$: [path, labelX, labelY] = getBezierPath({
		sourceX: $$props.sourceX,
		sourceY: $$props.sourceY,
		targetX: $$props.targetX,
		targetY: $$props.targetY,
		sourcePosition: $$props.sourcePosition,
		targetPosition: $$props.targetPosition
	});

	const edges = useEdges();

	function onClick() {
		edges.update((eds) => eds.filter((e) => e.id !== $$props.id));
	}
</script>

<BaseEdge {path} {labelX} {labelY} {...$$props} />

<EdgeLabelRenderer>
	<button
		style:transform={`translate(-50%,-50%) translate(${labelX}px,${labelY}px)`}
		class="edge-button"
		on:click={onClick}
	>
		✕
	</button>
</EdgeLabelRenderer>

<style>
	.edge-button {
		border-radius: 50%;
		position: absolute;
		border: none;
		width: 1rem;
		height: 1rem;
		display: flex;
		justify-content: center;
		align-items: center;
		font-size: 8px;
		pointer-events: all;
		cursor: pointer;
		background-color: #eee;
	}

	.edge-button:hover {
		box-shadow: 0 0 2px 1px rgba(0, 0, 0, 0.12);
	}
</style>

// examples/vite-app/src/examples/EdgeRenderer/CustomEdge.tsx
import { FC, MouseEvent } from 'react';
import { EdgeProps, getBezierPath, EdgeLabelRenderer, useStore } from '@xyflow/react';

const CustomEdge: FC<EdgeProps> = ({
  id,
  source,
  target,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
}) => {
  const isConnectedNodeDragging = useStore((s) =>
    s.getNodes().find((n) => n.dragging && (target === n.id || source === n.id))
  );

  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  const onClick = (event: MouseEvent) => {
    event.preventDefault();
    event.stopPropagation();

    console.log('click', data.text);
  };

  return (
    <>
      <path id={id} className="react-flow__edge-path" d={edgePath} />

      <EdgeLabelRenderer>
        <div
          style={{
            position: 'absolute',
            transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
            background: '#ffcc00',
            padding: 10,
            zIndex: isConnectedNodeDragging ? 10 : 0,
            pointerEvents: 'all',
          }}
          className="nodrag nopan"
        >
          {data.text}
          <input style={{ display: 'block' }} />
          <button onClick={onClick}>send</button>
        </div>
      </EdgeLabelRenderer>
    </>
  );
};

export default CustomEdge;
