// packages/solidjs/src/additional-components/NodeToolbar/types.ts
// import type { HTMLAttributes } from 'react';
import type { Position, Align } from '@xyflow/system';
import { JSX } from 'solid-js';

export type NodeToolbarProps = JSX.HTMLAttributes<HTMLDivElement> & {
  /** Id of the node, or array of ids the toolbar should be displayed at */
  nodeId?: string | string[];
  /** If true, node toolbar is visible even if node is not selected */
  isVisible?: boolean;
  /** Position of the toolbar relative to the node
   * @example Position.TopLeft, Position.TopRight,
   * Position.BottomLeft, Position.BottomRight
   */
  position?: Position;
  /** Offset the toolbar from the node */
  offset?: number;
  /** Align the toolbar relative to the node
   * @example Align.Start, Align.Center, Align.End
   */
  align?: Align;
};

// packages/react/src/additional-components/EdgeToolbar/types.ts
import type { HTMLAttributes } from 'react';
import type { Position, Align } from '@xyflow/system';

/**
 * @expand
 */
export type EdgeToolbarProps = HTMLAttributes<HTMLDivElement> & {
  /**
   * An edge toolbar must be attached to an edge.
   */
  edgeId: string;
  /** If `true`, edge toolbar is visible even if edge is not selected. */
  isVisible?: boolean;
  /**
   * TODO: What and how?? Needed?
   * Position of the toolbar relative to the edge.
   * @default Position.Top
   * @example Position.TopLeft, Position.TopRight, Position.BottomLeft, Position.BottomRight
   */
  position?: Position;
  /**
   * The space between the edge and the toolbar, measured in pixels.
   * @default 10
   */
  offset?: number;
  /**
   * Align the toolbar relative to the edge.
   * @default "center"
   * @example Align.Start, Align.Center, Align.End
   */
  align?: Align;
  /**
   * The `x` position of the edge label.
   */
  x: number;
  /**
   * The `y` position of the edge label.
   */
  y: number;
  /**
   * The `offsetX` position of the edge label relative to the edge in pixels.
   */
  offsetX?: number;
  /**
   * The `offsetY` position of the edge label relative to the edge in pixels.
   */
  offsetY?: number;
};
