// examples/vite-app/src/examples/FloatingEdges/FloatingEdge.tsx
import { FC, CSSProperties } from 'react';
import { EdgeProps, useStore, getBezierPath } from '@xyflow/react';

import { getEdgeParams } from './utils';

const FloatingEdge: FC<EdgeProps> = ({ id, source, target, style }) => {
  const { sourceNode, targetNode } = useStore((s) => {
    const sourceNode = s.nodes.find((n) => n.id === source);
    const targetNode = s.nodes.find((n) => n.id === target);

    return { sourceNode, targetNode };
  });

  if (!sourceNode || !targetNode) {
    return null;
  }

  const { sx, sy, tx, ty, sourcePos, targetPos } = getEdgeParams(sourceNode, targetNode);

  const [path] = getBezierPath({
    sourceX: sx,
    sourceY: sy,
    sourcePosition: sourcePos,
    targetPosition: targetPos,
    targetX: tx,
    targetY: ty,
  });

  return (
    <g className="react-flow__connection">
      <path id={id} className="react-flow__edge-path" d={path} style={style as CSSProperties} />
    </g>
  );
};

export default FloatingEdge;

// examples/vue/src/FloatingEdges/FloatingEdge.vue
<script lang="ts" setup>
import type { EdgeProps } from '@xyflow/vue';
import { BaseEdge, getBezierPath, useVueFlow } from '@xyflow/vue';
import { getEdgeParams } from './floating-edge-utils';

const props = defineProps<EdgeProps>();

const { getInternalNode } = useVueFlow();

const edgeParams = computed(() => {
  const sourceNode = getInternalNode(props.source);
  const targetNode = getInternalNode(props.target);

  if (!sourceNode || !targetNode) {
    return null;
  }

  return getEdgeParams(sourceNode, targetNode);
});

const edgePath = computed(
  () =>
    (edgeParams.value?.sx
      && getBezierPath({
        sourceX: edgeParams.value.sx,
        sourceY: edgeParams.value.sy,
        targetX: edgeParams.value.tx,
        targetY: edgeParams.value.ty,
        sourcePosition: edgeParams.value.sourcePos,
        targetPosition: edgeParams.value.targetPos,
      }))
      // fall back to an array so `edgePath[0]` is always a string — before the nodes are measured
      // `sx` is undefined and a bare `''` fallback made `edgePath[0]` undefined (BaseEdge `path` warning)
      || [''],
);
</script>

<template>
  <BaseEdge :id="id" :path="edgePath[0]" :marker-start="markerStart" :marker-end="markerEnd" :style="style" />
</template>
