// examples/svelte/src/generic-tests/nodes/components/DragHandleNode.svelte
<script lang="ts">
	import type { NodeProps } from '@xyflow/svelte';

	type $$Props = NodeProps;
</script>

<div class="container">
	<div class="drag-handle custom-drag-handle"></div>
</div>

<style>
	.container {
		width: 100px;
		height: 50px;
		background: red;
		display: flex;
		align-items: center;
		justify-content: center;
	}
	.drag-handle {
		display: inline-block;
		width: 25px;
		height: 25px;
		background-color: green;
	}
</style>

// examples/react/src/generic-tests/nodes/components/DragHandleNode.tsx
export default () => {
  return (
    <div
      className="container"
      style={{
        width: '100px',
        height: '50px',
        background: 'red',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <div
        className="drag-handle custom-drag-handle"
        style={{
          display: 'inline-block',
          width: '25px',
          height: '25px',
          backgroundColor: 'green',
        }}
      />
    </div>
  );
};
