// examples/svelte/src/generic-tests/nodes/components/UpdateNodeInternalsNode.svelte
<script lang="ts">
	import { useUpdateNodeInternals, useSvelteFlow, type NodeProps } from '@xyflow/svelte';

	let { id }: NodeProps = $props();

	const updateNodeInternals = useUpdateNodeInternals();
	const { getInternalNode } = useSvelteFlow();
	let containerEl: HTMLDivElement;

	$effect(() => {
		const w = window as any;
		w.__updateNodeInternals = updateNodeInternals;
		w.__getInternalNode = getInternalNode;
		w.__nodeId = id;
		w.__expandContainer = () => {
			if (containerEl && !containerEl.querySelector('.extra-content')) {
				const extra = document.createElement('div');
				extra.className = 'extra-content';
				extra.style.height = '150px';
				extra.style.background = '#a8dadc';
				containerEl.appendChild(extra);
			}
		};
	});
</script>

<div class="update-internals-node">
	<div bind:this={containerEl} class="toggle-container"></div>
</div>

<style>
	.update-internals-node {
		display: flex;
		flex-direction: column;
		align-items: center;
		padding: 10px;
		border: 1px solid #ccc;
		background: #fff;
	}
</style>

// examples/react/src/generic-tests/nodes/components/UpdateNodeInternalsNode.tsx
import { useEffect, useRef } from 'react';
import { useUpdateNodeInternals, useReactFlow, type NodeProps } from '@xyflow/react';

export default function UpdateNodeInternalsNode({ id }: NodeProps) {
  const updateNodeInternals = useUpdateNodeInternals();
  const { getInternalNode } = useReactFlow();
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const w = window as any;
    w.__updateNodeInternals = updateNodeInternals;
    w.__getInternalNode = getInternalNode;
    w.__nodeId = id;
    w.__expandContainer = () => {
      const container = containerRef.current;
      if (container && !container.querySelector('.extra-content')) {
        const extra = document.createElement('div');
        extra.className = 'extra-content';
        extra.style.height = '150px';
        extra.style.background = '#a8dadc';
        container.appendChild(extra);
      }
    };
  }, [id, updateNodeInternals, getInternalNode]);

  return (
    <div className="update-internals-node" style={{ padding: 10, border: '1px solid #ccc', background: '#fff' }}>
      <div>Update Internals</div>
      <div ref={containerRef} className="toggle-container" />
    </div>
  );
}
