// packages/react/src/components/Nodes/DefaultNode.tsx
import { Position } from '@xyflow/system';

import { Handle } from '../../components/Handle';
import type { BuiltInNode, NodeProps } from '../../types/nodes';

export function DefaultNode({
  data,
  isConnectable,
  targetPosition = Position.Top,
  sourcePosition = Position.Bottom,
}: NodeProps<BuiltInNode>) {
  return (
    <>
      <Handle type="target" position={targetPosition} isConnectable={isConnectable} />
      {data?.label}
      <Handle type="source" position={sourcePosition} isConnectable={isConnectable} />
    </>
  );
}

// packages/solidjs/src/components/Nodes/DefaultNode.tsx
import { Position } from '@xyflow/system';

import { Handle } from '../Handle';
import type { BuiltInNode, NodeProps } from '../../types/nodes';
import { mergeProps } from 'solid-js';

export function DefaultNode(_p: NodeProps<BuiltInNode>) {
  const p = mergeProps(
    {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
    },
    _p
  );

  return (
    <>
      <Handle type="target" position={p.targetPosition} isConnectable={p.isConnectable} />
      {p.data?.label}
      <Handle type="source" position={p.sourcePosition} isConnectable={p.isConnectable} />
    </>
  );
}
