// packages/svelte/src/lib/plugins/EdgeToolbar/EdgeToolbar.svelte
<script lang="ts">
  import { getEdgeToolbarTransform } from '@xyflow/system';

  import { useStore } from '$lib/store';
  import { EdgeLabel } from '$lib/components/EdgeLabel';
  import type { EdgeToolbarProps } from './types';

  let {
    edgeId,
    x,
    y,
    alignX = 'center',
    alignY = 'center',
    isVisible,
    children,
    ...rest
  }: EdgeToolbarProps = $props();

  const store = useStore();
  const edge = $derived(store.edgeLookup.get(edgeId));
  const isActive = $derived(typeof isVisible === 'boolean' ? isVisible : edge?.selected);
  const transform = $derived(getEdgeToolbarTransform(x, y, store.viewport.zoom, alignX, alignY));
  const zIndex = $derived((edge?.zIndex ?? 0) + 1);
</script>

{#if store.domNode && isActive}
  <EdgeLabel>
    <div
      style:position="absolute"
      style:transform
      style:z-index={zIndex}
      style:transform-origin="0 0"
      {...rest}
      class="svelte-flow__edge-toolbar"
      data-id={edgeId ?? ''}
    >
      {@render children?.()}
    </div>
  </EdgeLabel>
{/if}

// packages/vue/src/components/EdgeToolbar/EdgeToolbar.vue
<script lang="ts" setup>
import type { CSSProperties } from 'vue';
import type { EdgeToolbarProps } from './types';
import { getEdgeToolbarTransform } from '@xyflow/system';
import { computed } from 'vue';
import { useStore, useVueFlow } from '../../composables';
import EdgeLabelRenderer from '../Edges/EdgeLabelRenderer.vue';

const props = withDefaults(defineProps<EdgeToolbarProps>(), {
  alignX: 'center',
  alignY: 'center',
  isVisible: undefined,
});

const { viewport } = useVueFlow();

const { edgeLookup } = useStore();

const edge = computed(() => edgeLookup.get(props.edgeId));

const isActive = computed(() =>
  typeof props.isVisible === 'boolean' ? props.isVisible : edge.value?.selected,
);

const wrapperStyle = computed<CSSProperties>(() => ({
  position: 'absolute',
  transform: getEdgeToolbarTransform(props.x, props.y, viewport.value.zoom, props.alignX, props.alignY),
  zIndex: (edge.value?.zIndex ?? 0) + 1,
  pointerEvents: 'all',
  transformOrigin: '0 0',
}));
</script>

<script lang="ts">
export default {
  name: 'EdgeToolbar',
  compatConfig: { MODE: 3 },
  inheritAttrs: false,
};
</script>

<template>
  <EdgeLabelRenderer v-if="isActive">
    <div v-bind="{ ...$attrs, 'data-id': edge?.id ?? '' }" :style="wrapperStyle" class="vue-flow__edge-toolbar">
      <slot />
    </div>
  </EdgeLabelRenderer>
</template>
