// packages/vue/src/components/NodeResizer/ResizeControl.vue
<script lang="ts" setup>
import type { NodeDimensionChange, NodePositionChange } from '@xyflow/system';
import type { NodeChange } from '../../types';
import type { NodeResizerEmits, ResizeControlProps } from './types';
import { XYResizer } from '@xyflow/system';
import { computed, shallowRef, toRef, watchEffect } from 'vue';
import { storeToRefs, useStore, useVueFlow } from '../../composables';
import { useNodeId } from '../../composables/useNodeId';
import { ResizeControlVariant } from './types';
import { DefaultPositions, StylingProperty } from './utils';

const props = withDefaults(defineProps<ResizeControlProps>(), {
  variant: 'handle' as ResizeControlVariant,
  minWidth: 10,
  minHeight: 10,
  maxWidth: Number.MAX_VALUE,
  maxHeight: Number.MAX_VALUE,
  keepAspectRatio: false,
  autoScale: true,
});

const emits = defineEmits<NodeResizerEmits>();

const { emits: triggerEmits, viewport } = useVueFlow();

const { nodeLookup } = useStore();

const { transform, nodeOrigin, snapGrid, snapToGrid, vueFlowRef, noDragClassName } = storeToRefs(useStore());

const resizeControlRef = shallowRef<HTMLDivElement>();

// fall back to the node context id so a bare `<NodeResizeControl>` inside a custom node resolves its node
// without an explicit `node-id` prop
const contextNodeId = useNodeId();

const nodeId = toRef(() => (typeof props.nodeId === 'string' ? props.nodeId : contextNodeId || undefined));

const controlPosition = toRef(() => props.position ?? DefaultPositions[props.variant]);

const positionClassNames = computed(() => controlPosition.value.split('-'));

const controlStyle = toRef(() => (props.color ? { [StylingProperty[props.variant]]: props.color } : {}));

watchEffect((onCleanup) => {
  if (!resizeControlRef.value || !nodeId.value) {
    return;
  }

  const resizerInstance = XYResizer({
    domNode: resizeControlRef.value,
    nodeId: nodeId.value,
    getStoreItems: () => ({
      nodeLookup,
      transform: transform.value,
      snapGrid: snapGrid.value,
      snapToGrid: snapToGrid.value,
      nodeOrigin: nodeOrigin.value,
      paneDomNode: vueFlowRef.value,
    }),
    onChange: (changes, childChanges) => {
      const nodeChanges: NodeChange[] = [];
      const node = nodeLookup.get(nodeId.value!);

      const nextX = changes.x;
      const nextY = changes.y;

      if (typeof nextX !== 'undefined' || typeof nextY !== 'undefined') {
        const position = {
          x: nextX ?? node?.position.x ?? 0,
          y: nextY ?? node?.position.y ?? 0,
        };
        nodeChanges.push({
          id: nodeId.value!,
          type: 'position',
          position,
          positionAbsolute: position,
        } as NodePositionChange);
      }

      if (typeof changes.width !== 'undefined' || typeof changes.height !== 'undefined') {
        nodeChanges.push({
          id: nodeId.value!,
          type: 'dimensions',
          setAttributes: true,
          resizing: true,
          dimensions: {
            width: changes.width ?? 0,
            height: changes.height ?? 0,
          },
        } as NodeDimensionChange);
      }

      for (const child of childChanges) {
        nodeChanges.push({
          id: child.id,
          type: 'position',
          position: child.position,
          positionAbsolute: child.position,
        } as NodePositionChange);
      }

      if (nodeChanges.length) {
        triggerEmits.nodesChange(nodeChanges);
      }
    },
    onEnd: ({ width, height }) => {
      triggerEmits.nodesChange([
        {
          id: nodeId.value!,
          type: 'dimensions',
          resizing: false,
          dimensions: { width, height },
        } as NodeDimensionChange,
      ]);
    },
  });

  resizerInstance.update({
    controlPosition: controlPosition.value,
    boundaries: {
      minWidth: props.minWidth,
      minHeight: props.minHeight,
      maxWidth: props.maxWidth,
      maxHeight: props.maxHeight,
    },
    keepAspectRatio: Boolean(props.keepAspectRatio ?? false),
    onResizeStart: (event, params) => emits('resizeStart', { event, params }),
    onResize: (event, params) => emits('resize', { event, params }),
    onResizeEnd: (event, params) => emits('resizeEnd', { event, params }),
    shouldResize: props.shouldResize,
  });

  onCleanup(() => {
    resizerInstance.destroy();
  });
});
</script>

<script lang="ts">
export default {
  name: 'ResizeControl',
  compatConfig: { MODE: 3 },
};
</script>

<template>
  <div
    ref="resizeControlRef"
    class="vue-flow__resize-control"
    :class="[...positionClassNames, variant, noDragClassName]"
    :style="{
      ...controlStyle,
      // keep handle controls from shrinking below their base size when zooming out; `autoScale` opts out
      scale: variant === ResizeControlVariant.Handle && autoScale ? `${Math.max(1 / viewport.zoom, 1)}` : undefined,
    }"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/plugins/NodeResizer/ResizeControl.svelte
<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import cc from 'classcat';
  import { useStore } from '$lib/store';
  import {
    XYResizer,
    ResizeControlVariant,
    type ControlPosition,
    type XYResizerInstance,
    type XYResizerChange,
    type XYResizerChildChange
  } from '@xyflow/system';
  import type { ResizeControlProps } from './types';

  type $$Props = ResizeControlProps;

  export let nodeId: $$Props['nodeId'] = undefined;
  export let position: $$Props['position'] = undefined;
  export let variant: $$Props['variant'] = ResizeControlVariant.Handle;
  export let color: $$Props['color'] = undefined;
  export let minWidth: $$Props['minWidth'] = 10;
  $: _minWidth = minWidth ?? 10;
  export let minHeight: $$Props['minHeight'] = 10;
  $: _minHeight = minHeight ?? 10;
  export let maxWidth: $$Props['maxWidth'] = Number.MAX_VALUE;
  $: _maxWidth = maxWidth ?? Number.MAX_VALUE;
  export let maxHeight: $$Props['maxHeight'] = Number.MAX_VALUE;
  $: _maxHeight = maxHeight ?? Number.MAX_VALUE;
  export let keepAspectRatio: $$Props['keepAspectRatio'] = false;
  export let shouldResize: $$Props['shouldResize'] = undefined;
  export let onResizeStart: $$Props['onResizeStart'] = undefined;
  export let onResize: $$Props['onResize'] = undefined;
  export let onResizeEnd: $$Props['onResizeEnd'] = undefined;
  export let style: $$Props['style'] = '';
  let className: $$Props['class'] = '';
  export { className as class };

  const { nodeLookup, snapGrid, viewport, nodes, nodeOrigin, domNode } = useStore();

  const contextNodeId = getContext<string>('svelteflow__node_id');
  $: id = typeof nodeId === 'string' ? nodeId : contextNodeId;

  let resizeControlRef: HTMLDivElement;
  let resizer: XYResizerInstance | null = null;

  $: defaultPosition = (
    variant === ResizeControlVariant.Line ? 'right' : 'bottom-right'
  ) as ControlPosition;
  $: controlPosition = position ?? defaultPosition;

  $: positionClassNames = controlPosition.split('-');

  $: colorStyleProp = variant === ResizeControlVariant.Line ? 'border-color' : 'background-color';
  $: _style = style ?? '';
  $: controlStyle = color ? `${_style} ${colorStyleProp}: ${color};` : _style;

  onMount(() => {
    if (resizeControlRef) {
      resizer = XYResizer({
        domNode: resizeControlRef,
        nodeId: id,
        getStoreItems: () => {
          return {
            nodeLookup: $nodeLookup,
            transform: [$viewport.x, $viewport.y, $viewport.zoom],
            snapGrid: $snapGrid ?? undefined,
            snapToGrid: !!$snapGrid,
            nodeOrigin: $nodeOrigin,
            paneDomNode: $domNode
          };
        },
        onChange: (change: XYResizerChange, childChanges: XYResizerChildChange[]) => {
          const node = $nodeLookup.get(id)?.internals.userNode;
          if (!node) {
            return;
          }

          if (change.x !== undefined && change.y !== undefined) {
            node.position = { x: change.x, y: change.y };
          }

          if (change.width !== undefined && change.height !== undefined) {
            node.width = change.width;
            node.height = change.height;
          }

          for (const childChange of childChanges) {
            const childNode = $nodeLookup.get(childChange.id)?.internals.userNode;
            if (childNode) {
              childNode.position = childChange.position;
            }
          }

          $nodes = $nodes;
        }
      });
    }
    return () => {
      resizer?.destroy();
    };
  });

  $: {
    resizer?.update({
      controlPosition,
      boundaries: {
        minWidth: _minWidth,
        minHeight: _minHeight,
        maxWidth: _maxWidth,
        maxHeight: _maxHeight
      },
      keepAspectRatio: !!keepAspectRatio,
      onResizeStart,
      onResize,
      onResizeEnd,
      shouldResize
    });
  }
</script>

<div
  class={cc(['svelte-flow__resize-control', 'nodrag', ...positionClassNames, variant, className])}
  bind:this={resizeControlRef}
  style={controlStyle}
>
  <slot />
</div>
