// storybook/shared/components/EdgeToolbar/CustomEdge.svelte
<script lang="ts">
  import {
    getBezierPath,
    getStraightPath,
    getSmoothStepPath,
    BaseEdge,
    EdgeToolbar,
    useSvelteFlow,
    type Edge,
    type EdgeProps,
  } from '@xyflow/svelte';
  type ToolbarEdge = Edge<{ type: string; align: ['left' | 'center' | 'right', 'top' | 'center' | 'bottom'] }>;
  let props: EdgeProps<ToolbarEdge> = $props();
  const { deleteElements } = useSvelteFlow();
  let path = $derived(
    (props.data?.type === 'smoothstep'
      ? getSmoothStepPath
      : props.data?.type === 'straight'
        ? getStraightPath
        : getBezierPath)(props)
  );
</script>

<BaseEdge id={props.id} path={path[0]} />
<EdgeToolbar
  x={path[1]}
  y={path[2]}
  alignX={props.data?.align?.[0] ?? 'center'}
  alignY={props.data?.align?.[1] ?? 'center'}
  isVisible
>
  <button onclick={() => deleteElements({ edges: [{ id: props.id }] })}>Delete</button>
</EdgeToolbar>

// storybook/shared/components/EdgeToolbar/CustomEdge.tsx
import {
  getBezierPath,
  BaseEdge,
  EdgeProps,
  type Edge,
  useReactFlow,
  getStraightPath,
  getSmoothStepPath,
} from '@xyflow/react';
import { EdgeToolbar } from '@xyflow/react';

const getPath = (
  props: EdgeProps<Edge<{ type: string; align: ['left' | 'center' | 'right', 'top' | 'center' | 'bottom'] }>>
) => {
  switch (props.data!.type) {
    case 'smoothstep':
      return getSmoothStepPath(props);
    case 'straight':
      return getStraightPath(props);
    default:
      return getBezierPath(props);
  }
};

export function CustomEdge(
  props: EdgeProps<Edge<{ type: string; align: ['left' | 'center' | 'right', 'top' | 'center' | 'bottom'] }>>
) {
  const [edgePath, centerX, centerY] = getPath(props);
  const { setEdges } = useReactFlow();

  const deleteEdge = () => {
    setEdges((edges) => edges.filter((edge) => edge.id !== props.id));
  };

  return (
    <>
      <BaseEdge id={props.id} path={edgePath} />
      <EdgeToolbar
        edgeId={props.id}
        x={centerX + 0}
        y={centerY + 0}
        alignX={props.data?.align?.[0] ?? 'center'}
        alignY={props.data?.align?.[1] ?? 'center'}
        isVisible
      >
        <button style={{}} onClick={deleteEdge}>
          Delete
        </button>
      </EdgeToolbar>
    </>
  );
}
