// examples/svelte/src/routes/examples/handle-connect/SingleHandleNode.svelte
<script lang="ts">
	import { Handle, Position, type NodeProps, type Connection } from '@xyflow/svelte';

	let { id }: NodeProps = $props();

	function onConnectTarget(connection: Connection[]) {
		console.log('connect target', connection);
	}

	function onConnectSource(connection: Connection[]) {
		console.log('connect source', connection);
	}

	function onDisconnectTarget(connection: Connection[]) {
		console.log('disconnect target', connection);
	}

	function onDisconnectSource(connection: Connection[]) {
		console.log('disconnect source', connection);
	}
</script>

<div class="custom">
	<Handle
		type="target"
		position={Position.Left}
		onconnect={onConnectTarget}
		ondisconnect={onDisconnectTarget}
	/>
	<div>node {id}</div>
	<Handle
		type="source"
		position={Position.Right}
		onconnect={onConnectSource}
		ondisconnect={onDisconnectSource}
	/>
</div>

<style>
	.custom {
		background-color: #333;
		padding: 10px;
		border-radius: 10px;
		color: #fff;
	}
</style>

// examples/react/src/examples/UseHandleConnections/SingleHandleNode.tsx
import { memo, FC, useEffect, useCallback } from 'react';
import { Handle, Position, NodeProps, useHandleConnections, Connection, HandleProps } from '@xyflow/react';

function CustomHandle({ nodeId, ...handleProps }: HandleProps & { nodeId: string }) {
  const onConnect = useCallback(
    (connections: Connection[]) => {
      console.log('onConnect handler, node id:', nodeId, connections);
    },
    [nodeId]
  );
  const onDisconnect = useCallback(
    (connections: Connection[]) => {
      console.log('onDisconnect handler, node id:', nodeId, connections);
    },
    [nodeId]
  );
  const connections = useHandleConnections({
    type: handleProps.type,
    id: handleProps.id,
    onConnect,
    onDisconnect,
  });

  useEffect(() => {
    console.log('useEffect, node id:', nodeId, handleProps.type, connections);
  }, [connections]);

  return <Handle {...handleProps} />;
}

const CustomNode: FC<NodeProps> = ({ id }) => {
  return (
    <div style={{ background: '#333', color: '#fff', padding: 10, fontSize: 12, borderRadius: 10 }}>
      <CustomHandle nodeId={id} type="target" position={Position.Left} />
      <div>node {id}</div>
      <CustomHandle nodeId={id} type="source" position={Position.Right} />
    </div>
  );
};

export default memo(CustomNode);
