// packages/react/src/container/Pane/index.tsx
import {
  useRef,
  type MouseEventHandler,
  type MutableRefObject,
  type MouseEvent as ReactMouseEvent,
  type PointerEvent as ReactPointerEvent,
  type WheelEvent as ReactWheelEvent,
  type ReactNode,
} from 'react';
import { shallow } from 'zustand/shallow';
import cc from 'classcat';
import {
  getNodesInside,
  getEventPosition,
  SelectionMode,
  areSetsEqual,
  calcAutoPan,
  pointToRendererPoint,
  rendererPointToPoint,
  XYPosition,
} from '@xyflow/system';

import { UserSelection } from '../../components/UserSelection';
import { containerStyle } from '../../styles/utils';
import { useStore, useStoreApi } from '../../hooks/useStore';
import { getSelectionChanges } from '../../utils';
import type { ReactFlowProps, ReactFlowState } from '../../types';

type PaneProps = {
  isSelecting: boolean;
  selectionKeyPressed: boolean;
  children: ReactNode;
  paneClickDistance: number;
} & Partial<
  Pick<
    ReactFlowProps,
    | 'selectionMode'
    | 'panOnDrag'
    | 'autoPanOnSelection'
    | 'onSelectionStart'
    | 'onSelectionEnd'
    | 'onPaneClick'
    | 'onPaneContextMenu'
    | 'onPaneScroll'
    | 'onPaneMouseEnter'
    | 'onPaneMouseMove'
    | 'onPaneMouseLeave'
    | 'selectionOnDrag'
  >
>;

const wrapHandler = (
  handler: MouseEventHandler | undefined,
  containerRef: MutableRefObject<HTMLDivElement | null>
): MouseEventHandler => {
  return (event: ReactMouseEvent) => {
    if (event.target !== containerRef.current) {
      return;
    }
    handler?.(event);
  };
};

const selector = (s: ReactFlowState) => ({
  userSelectionActive: s.userSelectionActive,
  elementsSelectable: s.elementsSelectable,
  connectionInProgress: s.connection.inProgress,
  dragging: s.paneDragging,
  panBy: s.panBy,
  autoPanSpeed: s.autoPanSpeed,
});

export function Pane({
  isSelecting,
  selectionKeyPressed,
  selectionMode = SelectionMode.Full,
  panOnDrag,
  autoPanOnSelection,
  paneClickDistance,
  selectionOnDrag,
  onSelectionStart,
  onSelectionEnd,
  onPaneClick,
  onPaneContextMenu,
  onPaneScroll,
  onPaneMouseEnter,
  onPaneMouseMove,
  onPaneMouseLeave,
  children,
}: PaneProps) {
  const autoPanId = useRef<number>(0);
  const store = useStoreApi();
  const { userSelectionActive, elementsSelectable, dragging, connectionInProgress, panBy, autoPanSpeed } = useStore(
    selector,
    shallow
  );
  const isSelectionEnabled = elementsSelectable && (isSelecting || userSelectionActive);

  const container = useRef<HTMLDivElement | null>(null);
  const containerBounds = useRef<DOMRect>();
  const selectedNodeIds = useRef<Set<string>>(new Set());
  const selectedEdgeIds = useRef<Set<string>>(new Set());

  // Used to prevent click events when the user lets go of the selectionKey during a selection
  const selectionInProgress = useRef<boolean>(false);

  // In auto-panning, selection start position must stay fixed in flow space, not pane pixels
  const userSelectionFlowOrigin = useRef<XYPosition | null>(null);

  // Used for auto pan when approaching the edges of the container during selection
  const position = useRef<XYPosition>({ x: 0, y: 0 });
  const autoPanStarted = useRef<boolean>(false);

  const onClick = (event: ReactMouseEvent) => {
    // We prevent click events when the user let go of the selectionKey during a selection
    // We also prevent click events when a connection is in progress
    if (selectionInProgress.current || connectionInProgress) {
      selectionInProgress.current = false;
      return;
    }

    onPaneClick?.(event);
    store.getState().resetSelectedElements();
    store.setState({ nodesSelectionActive: false });
  };

  const onContextMenu = (event: ReactMouseEvent) => {
    if (Array.isArray(panOnDrag) && panOnDrag?.includes(2)) {
      event.preventDefault();
      return;
    }

    onPaneContextMenu?.(event);
  };

  const onWheel = onPaneScroll ? (event: ReactWheelEvent) => onPaneScroll(event) : undefined;

  const onClickCapture = (event: ReactMouseEvent) => {
    if (selectionInProgress.current) {
      event.stopPropagation();
      selectionInProgress.current = false;
    }
  };

  // We are using capture here in order to prevent other pointer events
  // to be able to create a selection above a node or an edge
  const onPointerDownCapture = (event: ReactPointerEvent): void => {
    const { domNode } = store.getState();
    containerBounds.current = domNode?.getBoundingClientRect();
    if (!containerBounds.current) return;

    const eventTargetIsContainer = event.target === container.current;
    // if a child element has the 'nokey' class, we don't want to swallow the event and don't start a selection
    const isNoKeyEvent = !eventTargetIsContainer && !!(event.target as HTMLElement).closest('.nokey');
    const isSelectionActive = (selectionOnDrag && eventTargetIsContainer) || selectionKeyPressed;

    if (isNoKeyEvent || !isSelecting || !isSelectionActive || event.button !== 0 || !event.isPrimary) {
      return;
    }

    (event.target as Partial<Element>)?.setPointerCapture?.(event.pointerId);

    selectionInProgress.current = false;

    const { x, y } = getEventPosition(event.nativeEvent, containerBounds.current);
    const { transform } = store.getState();
    userSelectionFlowOrigin.current = pointToRendererPoint({ x, y }, transform);

    store.setState({
      userSelectionRect: {
        width: 0,
        height: 0,
        startX: x,
        startY: y,
        x,
        y,
      },
    });

    if (!eventTargetIsContainer) {
      event.stopPropagation();
      event.preventDefault();
    }
  };

  // We commit the user selection rectangle to the store on auto-panning or pointer move during selection.
  function commitUserSelectionRect(mouseX: number, mouseY: number): void {
    const flowOrigin = userSelectionFlowOrigin.current;
    if (!flowOrigin) {
      return;
    }

    const {
      transform,
      nodeLookup,
      edgeLookup,
      connectionLookup,
      triggerNodeChanges,
      triggerEdgeChanges,
      defaultEdgeOptions,
    } = store.getState();

    const screenStart = rendererPointToPoint(flowOrigin, transform);
    // This has to be in screen coordinates, not in flow coordinates.
    // We store the selection rectangle in userSelectionFlowOrigin coordinates to be able to
    // fix the start position of the selection rectangle when we are auto-panning.
    const nextUserSelectRect = {
      startX: screenStart.x,
      startY: screenStart.y,
      x: mouseX < screenStart.x ? mouseX : screenStart.x,
      y: mouseY < screenStart.y ? mouseY : screenStart.y,
      width: Math.abs(mouseX - screenStart.x),
      height: Math.abs(mouseY - screenStart.y),
    };

    const prevSelectedNodeIds = selectedNodeIds.current;
    const prevSelectedEdgeIds = selectedEdgeIds.current;

    selectedNodeIds.current = new Set(
      getNodesInside(nodeLookup, nextUserSelectRect, transform, selectionMode === SelectionMode.Partial, true).map(
        (node) => node.id
      )
    );

    selectedEdgeIds.current = new Set();
    const edgesSelectable = defaultEdgeOptions?.selectable ?? true;

    // We look for all edges connected to the selected nodes
    for (const nodeId of selectedNodeIds.current) {
      const connections = connectionLookup.get(nodeId);
      if (!connections) continue;
      for (const { edgeId } of connections.values()) {
        const edge = edgeLookup.get(edgeId);
        if (edge && (edge.selectable ?? edgesSelectable)) {
          selectedEdgeIds.current.add(edgeId);
        }
      }
    }

    if (!areSetsEqual(prevSelectedNodeIds, selectedNodeIds.current)) {
      const changes = getSelectionChanges(nodeLookup, selectedNodeIds.current, true);
      triggerNodeChanges(changes);
    }

    if (!areSetsEqual(prevSelectedEdgeIds, selectedEdgeIds.current)) {
      const changes = getSelectionChanges(edgeLookup, selectedEdgeIds.current);
      triggerEdgeChanges(changes);
    }

    store.setState({
      userSelectionRect: nextUserSelectRect,
      userSelectionActive: true,
      nodesSelectionActive: false,
    });
  }

  function autoPan(): void {
    if (!autoPanOnSelection || !containerBounds.current) {
      return;
    }
    const [x, y] = calcAutoPan(position.current, containerBounds.current, autoPanSpeed);

    panBy({ x, y }).then((panned) => {
      if (!selectionInProgress.current || !userSelectionFlowOrigin.current || !panned) {
        return;
      }
      const { x: mx, y: my } = position.current;
      commitUserSelectionRect(mx, my);
    });

    autoPanId.current = requestAnimationFrame(autoPan);
  }

  const onPointerMove = (event: ReactPointerEvent): void => {
    const { userSelectionRect, transform, resetSelectedElements } = store.getState();

    if (!containerBounds.current || !userSelectionRect || !userSelectionFlowOrigin.current) {
      return;
    }

    const { x: mouseX, y: mouseY } = getEventPosition(event.nativeEvent, containerBounds.current);
    position.current = { x: mouseX, y: mouseY };

    const screenStart = rendererPointToPoint(userSelectionFlowOrigin.current, transform);

    if (!selectionInProgress.current) {
      const requiredDistance = selectionKeyPressed ? 0 : paneClickDistance;
      const distance = Math.hypot(mouseX - screenStart.x, mouseY - screenStart.y);
      if (distance <= requiredDistance) {
        return;
      }
      resetSelectedElements();
      onSelectionStart?.(event);
    }

    selectionInProgress.current = true;

    if (!autoPanStarted.current) {
      autoPan();
      autoPanStarted.current = true;
    }

    commitUserSelectionRect(mouseX, mouseY);
  };

  const onPointerUp = (event: ReactPointerEvent) => {
    if (event.button !== 0) {
      return;
    }

    (event.target as Partial<Element>)?.releasePointerCapture?.(event.pointerId);

    /*
     * We only want to trigger click functions when in selection mode if
     * the user did not move the mouse.
     */
    if (!userSelectionActive && event.target === container.current && store.getState().userSelectionRect) {
      onClick?.(event);
    }

    store.setState({
      userSelectionActive: false,
      userSelectionRect: null,
    });

    if (selectionInProgress.current) {
      onSelectionEnd?.(event);

      store.setState({
        nodesSelectionActive: selectedNodeIds.current.size > 0,
      });
    }

    cancelAnimationFrame(autoPanId.current);
    autoPanId.current = 0;
    autoPanStarted.current = false;
    userSelectionFlowOrigin.current = null;
  };

  const draggable = panOnDrag === true || (Array.isArray(panOnDrag) && panOnDrag.includes(0));

  return (
    <div
      className={cc(['react-flow__pane', { draggable, dragging, selection: isSelecting }])}
      onClick={isSelectionEnabled ? undefined : wrapHandler(onClick, container)}
      onContextMenu={wrapHandler(onContextMenu, container)}
      onWheel={wrapHandler(onWheel, container)}
      onPointerEnter={isSelectionEnabled ? undefined : onPaneMouseEnter}
      onPointerMove={isSelectionEnabled ? onPointerMove : onPaneMouseMove}
      onPointerUp={isSelectionEnabled ? onPointerUp : undefined}
      onPointerDownCapture={isSelectionEnabled ? onPointerDownCapture : undefined}
      onClickCapture={isSelectionEnabled ? onClickCapture : undefined}
      onPointerLeave={onPaneMouseLeave}
      ref={container}
      style={containerStyle}
    >
      {children}
      <UserSelection />
    </div>
  );
}

// packages/vue/src/container/Pane/Pane.vue
<script lang="ts" setup>
import type { XYPosition } from '@xyflow/system';
import type { EdgeChange, NodeChange } from '../../types';
import { areSetsEqual, calcAutoPan, getEventPosition, getNodesInside, pointToRendererPoint, rendererPointToPoint, SelectionMode } from '@xyflow/system';
import { onUnmounted, shallowRef, toRef, watch } from 'vue';
import NodesSelection from '../../components/NodesSelection/NodesSelection.vue';
import UserSelection from '../../components/UserSelection/UserSelection.vue';
import { storeToRefs, useKeyPress, useStore, useVueFlow } from '../../composables';
import { getSelectionChanges } from '../../utils';

const { isSelecting, selectionKeyPressed } = defineProps<{ isSelecting: boolean; selectionKeyPressed: boolean }>();

const { emits, removeSelectedNodes, removeSelectedEdges, resetSelectedElements, getSelectedEdges, getSelectedNodes, deleteElements, panBy } = useVueFlow();

const { edgeLookup, nodeLookup } = useStore();

const {
  vueFlowRef,
  transform,
  userSelectionActive,
  userSelectionRect,
  elementsSelectable,
  nodesSelectionActive,
  selectionMode,
  deleteKeyCode,
  multiSelectionKeyCode,
  multiSelectionActive,
  connectionLookup,
  defaultEdgeOptions,
  connectionStartHandle,
  panOnDrag,
  paneClickDistance,
  autoPanOnSelection,
  autoPanSpeed,
} = storeToRefs(useStore());

const container = shallowRef<HTMLDivElement | null>(null);

const selectedNodeIds = shallowRef<Set<string>>(new Set());

const selectedEdgeIds = shallowRef<Set<string>>(new Set());

const containerBounds = shallowRef<DOMRect | null>(null);

const hasActiveSelection = toRef(() => elementsSelectable.value && (isSelecting || userSelectionActive.value));

const connectionInProgress = toRef(() => connectionStartHandle.value !== null);

// Used to prevent click events when the user lets go of the selectionKey during a selection
let selectionInProgress = false;
let selectionStarted = false;

let autoPanId = 0;
let autoPanStarted = false;
let lastPointerPosition: XYPosition = { x: 0, y: 0 };

const deleteKeyPressed = useKeyPress(deleteKeyCode, { actInsideInputWithModifier: false });

const multiSelectKeyPressed = useKeyPress(multiSelectionKeyCode);

watch(deleteKeyPressed, (isKeyPressed) => {
  if (!isKeyPressed) {
    return;
  }

  // routed through `deleteElements` so the `onBeforeDelete` guard (cancel/confirm/filter) is triggered
  deleteElements({
    nodes: [...getSelectedNodes.value],
    edges: [...getSelectedEdges.value],
  });

  nodesSelectionActive.value = false;
});

watch(multiSelectKeyPressed, (isKeyPressed) => {
  multiSelectionActive.value = isKeyPressed;
});

onUnmounted(() => {
  cleanupAutoPan();
});

function wrapHandler<E extends Event>(handler: (event: E) => void, containerRef: HTMLDivElement | null) {
  return (event: E) => {
    if (event.target !== containerRef) {
      return;
    }

    handler(event);
  };
}

function onClick(event: MouseEvent) {
  if (selectionInProgress || connectionInProgress.value) {
    selectionInProgress = false;
    return;
  }

  emits.paneClick(event);

  // clears the selection, but keeps it while `elementsSelectable` is off (xyflow/react #5217)
  resetSelectedElements();

  nodesSelectionActive.value = false;
}

function onContextMenu(event: MouseEvent) {
  if (Array.isArray(panOnDrag.value) && panOnDrag.value?.includes(2)) {
    event.preventDefault();
    return;
  }

  emits.paneContextMenu(event);
}

function onWheel(event: WheelEvent) {
  emits.paneScroll(event);
}

function onPointerDown(event: PointerEvent) {
  containerBounds.value = vueFlowRef.value?.getBoundingClientRect() ?? null;

  if (
    !elementsSelectable.value
    || !isSelecting
    || event.button !== 0
    || event.target !== container.value
    || !containerBounds.value
  ) {
    return;
  }

  ;(event.target as Element)?.setPointerCapture?.(event.pointerId);

  const { x, y } = getEventPosition(event, containerBounds.value);

  selectionStarted = true;
  selectionInProgress = false;
  autoPanStarted = false;

  // the selection only begins once the pointer moves past the click threshold (see `onPointerMove`); resetting
  // here would clear the selection on a plain click and open a selection box for it

  // store the origin in flow coordinates so it stays anchored to the canvas while auto-panning
  const flowStart = pointToRendererPoint({ x, y }, transform.value);

  userSelectionRect.value = {
    width: 0,
    height: 0,
    startX: flowStart.x,
    startY: flowStart.y,
    x,
    y,
  };
}

function commitUserSelectionRect(mouseX: number, mouseY: number) {
  if (!userSelectionRect.value) {
    return;
  }

  const { startX = 0, startY = 0 } = userSelectionRect.value;
  const screenStart = rendererPointToPoint({ x: startX, y: startY }, transform.value);

  const nextUserSelectRect = {
    startX,
    startY,
    x: mouseX < screenStart.x ? mouseX : screenStart.x,
    y: mouseY < screenStart.y ? mouseY : screenStart.y,
    width: Math.abs(mouseX - screenStart.x),
    height: Math.abs(mouseY - screenStart.y),
  };

  const prevSelectedNodeIds = selectedNodeIds.value;
  const prevSelectedEdgeIds = selectedEdgeIds.value;
  selectedNodeIds.value = new Set(
    getNodesInside(nodeLookup, nextUserSelectRect, transform.value, selectionMode.value === SelectionMode.Partial, true).map(
      node => node.id,
    ),
  );

  selectedEdgeIds.value = new Set();
  const edgesSelectable = defaultEdgeOptions.value?.selectable ?? elementsSelectable.value;

  // We look for all edges connected to the selected nodes
  for (const nodeId of selectedNodeIds.value) {
    const connections = connectionLookup.value.get(nodeId);
    if (!connections) {
      continue;
    }
    for (const { edgeId } of connections.values()) {
      const edge = edgeLookup.get(edgeId);
      if (edge && (edge.selectable ?? edgesSelectable)) {
        selectedEdgeIds.value.add(edgeId);
      }
    }
  }

  if (!areSetsEqual(prevSelectedNodeIds, selectedNodeIds.value)) {
    const changes = getSelectionChanges(nodeLookup, selectedNodeIds.value) as NodeChange[];
    emits.nodesChange(changes);
  }

  if (!areSetsEqual(prevSelectedEdgeIds, selectedEdgeIds.value)) {
    const changes = getSelectionChanges(edgeLookup, selectedEdgeIds.value) as EdgeChange[];
    emits.edgesChange(changes);
  }

  userSelectionRect.value = nextUserSelectRect;
  userSelectionActive.value = true;
  nodesSelectionActive.value = false;
}

function autoPan() {
  if (!autoPanOnSelection.value || !containerBounds.value) {
    return;
  }

  const [xMovement, yMovement] = calcAutoPan(lastPointerPosition, containerBounds.value, autoPanSpeed.value);

  panBy({ x: xMovement, y: yMovement }).then((panned) => {
    if (selectionInProgress && panned) {
      commitUserSelectionRect(lastPointerPosition.x, lastPointerPosition.y);
    }

    autoPanId = requestAnimationFrame(autoPan);
  });
}

function cleanupAutoPan() {
  cancelAnimationFrame(autoPanId);
  autoPanId = 0;
  autoPanStarted = false;
}

function onPointerMove(event: PointerEvent) {
  if (!containerBounds.value || !userSelectionRect.value) {
    return;
  }

  const { x: mouseX, y: mouseY } = getEventPosition(event, containerBounds.value);
  lastPointerPosition = { x: mouseX, y: mouseY };

  if (!selectionInProgress) {
    const screenStart = rendererPointToPoint({ x: userSelectionRect.value.startX, y: userSelectionRect.value.startY }, transform.value);
    const requiredDistance = selectionKeyPressed ? 0 : paneClickDistance.value;
    const distance = Math.hypot(mouseX - screenStart.x, mouseY - screenStart.y);

    if (distance <= requiredDistance) {
      return;
    }

    removeSelectedNodes();
    removeSelectedEdges();
    emits.selectionStart(event);
  }

  selectionInProgress = true;

  if (!autoPanStarted) {
    autoPan();
    autoPanStarted = true;
  }

  commitUserSelectionRect(mouseX, mouseY);
}

function onPointerUp(event: PointerEvent) {
  if (event.button !== 0 || !selectionStarted) {
    return;
  }

  ;(event.target as Element)?.releasePointerCapture(event.pointerId);

  if (!userSelectionActive.value && userSelectionRect.value && event.target === container.value) {
    onClick(event);
  }

  userSelectionActive.value = false;
  userSelectionRect.value = null;

  // only a real selection drag (not a plain click) updates the selection box / emits `selectionEnd` (xyflow/react #5593)
  if (selectionInProgress) {
    nodesSelectionActive.value = selectedNodeIds.value.size > 0;
    emits.selectionEnd(event);
  }

  if (selectionKeyPressed) {
    selectionInProgress = false;
  }

  selectionStarted = false;

  cleanupAutoPan();
}

function onPointerCancel(event: PointerEvent) {
  ;(event.target as Element)?.releasePointerCapture?.(event.pointerId);
  cleanupAutoPan();
}
</script>

<script lang="ts">
export default {
  name: 'Pane',
  compatConfig: { MODE: 3 },
};
</script>

<template>
  <div
    ref="container"
    class="vue-flow__pane vue-flow__container"
    :class="{ selection: isSelecting }"
    @click="(event) => (hasActiveSelection ? undefined : wrapHandler(onClick, container)(event))"
    @contextmenu="wrapHandler(onContextMenu, container)($event)"
    @wheel.passive="wrapHandler(onWheel, container)($event)"
    @pointerenter="(event) => (hasActiveSelection ? undefined : emits.paneMouseEnter(event))"
    @pointerdown="(event) => (hasActiveSelection ? onPointerDown(event) : undefined)"
    @pointermove="(event) => (hasActiveSelection ? onPointerMove(event) : emits.paneMouseMove(event))"
    @pointerup="(event) => (hasActiveSelection ? onPointerUp(event) : undefined)"
    @pointercancel="(event) => (hasActiveSelection ? onPointerCancel(event) : undefined)"
    @pointerleave="emits.paneMouseLeave($event)"
  >
    <slot />
    <UserSelection v-if="userSelectionActive && userSelectionRect" :user-selection-rect="userSelectionRect" />
    <NodesSelection v-if="nodesSelectionActive && getSelectedNodes.length" />
  </div>
</template>
