// storybook/shared/InteractionPanel/InteractionPanel.tsx
import { Panel, useReactFlow, type Node, type Edge } from '@xyflow/react';
import { action } from 'storybook/actions';
import { createInteractionPanel, panelActions } from './actions';
import './styles.css';

export default function InteractionPanel() {
  const flow = useReactFlow();
  const actions = createInteractionPanel(
    {
      ...flow,
      setNodes: (nodes) => flow.setNodes(nodes as Node[]),
      setEdges: (edges) => flow.setEdges(edges as Edge[]),
    },
    'react',
    (name, value) => action(name)(value)
  );

  return (
    <Panel position="top-right" className="interaction-panel">
      {panelActions.map(({ id, label }) => (
        <button
          type="button"
          key={id}
          data-action={id}
          onClick={() => {
            action(id)();
            void actions[id]();
          }}
        >
          {label}
        </button>
      ))}
    </Panel>
  );
}

// storybook/shared/InteractionPanel/InteractionPanel.svelte
<script lang="ts">
  import { Panel, useNodes, useEdges, useSvelteFlow, type Node, type Edge } from '@xyflow/svelte';
  import { action } from 'storybook/actions';
  import { createInteractionPanel, panelActions } from './actions';
  import './styles.css';

  const nodes = useNodes();
  const edges = useEdges();
  const flow = useSvelteFlow();
  const actions = createInteractionPanel(
    {
      ...flow,
      addNodes: (value) => {
        nodes.current = [...nodes.current, ...(value as Node[])];
      },
      setNodes: (value) => {
        nodes.current = value as Node[];
      },
      setEdges: (value) => {
        edges.current = value as Edge[];
      },
    },
    'svelte',
    (name, value) => action(name)(value)
  );
</script>

<Panel position="top-right" class="interaction-panel">
  {#each panelActions as item (item.id)}
    <button
      type="button"
      data-action={item.id}
      onclick={() => {
        action(item.id)();
        void actions[item.id]();
      }}
    >
      {item.label}
    </button>
  {/each}
</Panel>
