// storybook/shared/InteractionPanel/InteractionPanel.vue
<script setup lang="ts">
import { Panel, useVueFlow, type Edge } from '@xyflow/vue';
import { action } from 'storybook/actions';
import { createInteractionPanel, panelActions } from './actions';
import './styles.css';
const flow = useVueFlow();
const actions = createInteractionPanel(
  {
    getNodes: () =>
      flow.getNodes.value.map((node) => ({ ...node, class: typeof node.class === 'string' ? node.class : undefined })),
    getEdges: () => [...flow.getEdges.value],
    setNodes: (nodes) => flow.setNodes(nodes),
    setEdges: (edges) => flow.setEdges(edges as Edge[]),
    addNodes: (nodes) => flow.addNodes(nodes),
    setViewport: flow.setViewport,
    deleteElements: flow.deleteElements,
    updateNodeData: flow.updateNodeData,
    toObject: flow.toObject,
  },
  'vue',
  (name, value) => action(name)(value)
);
</script>
<template>
  <Panel position="top-right" class="interaction-panel">
    <button
      v-for="{ id, label } in panelActions"
      :key="id"
      type="button"
      v-bind="{ 'data-action': id }"
      @click="actions[id]()"
    >
      {{ label }}
    </button>
  </Panel>
</template>

// storybook/shared/InteractionPanel/InteractionPanel.tsx
import { Panel, useReactFlow, type Node, type Edge } from '@xyflow/react';
import { action } from 'storybook/actions';
import { createInteractionPanel, panelActions } from './actions';
import './styles.css';

export default function InteractionPanel() {
  const flow = useReactFlow();
  const actions = createInteractionPanel(
    {
      ...flow,
      setNodes: (nodes) => flow.setNodes(nodes as Node[]),
      setEdges: (edges) => flow.setEdges(edges as Edge[]),
    },
    'react',
    (name, value) => action(name)(value)
  );

  return (
    <Panel position="top-right" className="interaction-panel">
      {panelActions.map(({ id, label }) => (
        <button
          type="button"
          key={id}
          data-action={id}
          onClick={() => {
            action(id)();
            void actions[id]();
          }}
        >
          {label}
        </button>
      ))}
    </Panel>
  );
}
