// examples/svelte/src/routes/examples/usenodesdata/UppercaseNode.svelte
<script lang="ts">
	import {
		Handle,
		Position,
		useNodeConnections,
		useNodesData,
		useSvelteFlow,
		type Node,
		type NodeProps
	} from '@xyflow/svelte';
	import { type MyNode } from './+page.svelte';

	let { id }: NodeProps<Node<{ text: string }>> = $props();

	const { updateNodeData } = useSvelteFlow();
	const connections = useNodeConnections(() => ({
		handleType: 'target'
	}));

	const nodesData = useNodesData<MyNode>(() => ({ nodeIds: connections.current[0]?.source }));

	$effect.pre(() => {
		const text =
			nodesData.current?.type === 'text' ? nodesData.current?.data.text.toUpperCase() : undefined;
		updateNodeData(id, { text });
	});
</script>

<div class="custom">
	<Handle type="target" position={Position.Left} isConnectable={connections.current.length === 0} />
	<div>uppercase transform</div>
	<Handle type="source" position={Position.Right} />
</div>

<style>
	.custom {
		background-color: #eee;
		padding: 10px;
		border-radius: 10px;
	}
</style>

// storybook/shared/examples/StateAndAPI/NodesData/UppercaseNode.vue
<script setup lang="ts">
import { watch } from 'vue';
import { Handle, Position, useVueFlow, useNodesData, useNodeConnections, type NodeProps } from '@xyflow/vue';
const props = defineProps<NodeProps>();
const { updateNodeData } = useVueFlow();
const connections = useNodeConnections({ handleType: 'target' });
const source = useNodesData(() => connections.value[0]?.source);
watch(
  source,
  (node) =>
    updateNodeData(props.id, { text: node?.type === 'text' ? String(node.data.text).toUpperCase() : undefined }),
  { immediate: true }
);
</script>
<template>
  <div style="background: #eee; color: #222; padding: 10px; font-size: 12px; border-radius: 10px">
    <Handle type="target" :position="Position.Left" :is-connectable="connections.length === 0" />
    uppercase transform
    <Handle type="source" :position="Position.Right" />
  </div>
</template>
