// packages/angular/projects/xyflow-angular/src/lib/components/background/line-pattern.component.ts
import { Component, Input, NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BackgroundVariant } from './types';

/**
 * Line pattern component for background grid.
 * Renders lines or crosses based on variant.
 */
@Component({
  selector: 'g[line-pattern]',
  standalone: true,
  schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <path
      [attr.stroke-width]="lineWidth"
      [attr.d]="getPathData()"
      [class]="getPatternClasses()"
    />
  `,
})
export class LinePatternComponent {
  @Input() dimensions: [number, number] = [20, 20];
  @Input() variant: BackgroundVariant = BackgroundVariant.Lines;
  @Input() lineWidth: number = 1;
  @Input() patternClass?: string;

  getPathData(): string {
    const [width, height] = this.dimensions;
    return `M${width / 2} 0 V${height} M0 ${height / 2} H${width}`;
  }

  getPatternClasses(): string {
    const baseClasses = ['angular-flow__background-pattern', this.variant];
    if (this.patternClass) {
      baseClasses.push(this.patternClass);
    }
    return baseClasses.join(' ');
  }
}

// packages/svelte/src/lib/plugins/Background/LinePattern.svelte
<script lang="ts">
  import cc from 'classcat';
  import type { BackgroundVariant } from './types';

  let {
    lineWidth = 1,
    dimensions = [20, 20],
    variant,
    class: className
  }: {
    lineWidth?: number;
    dimensions?: [number, number];
    variant?: BackgroundVariant;
    class?: string;
  } = $props();
</script>

<path
  stroke-width={lineWidth}
  d={`M${dimensions[0] / 2} 0 V${dimensions[1]} M0 ${dimensions[1] / 2} H${dimensions[0]}`}
  class={cc(['svelte-flow__background-pattern', variant, className])}
/>
