// examples/svelte/src/routes/useupdatenodeinternals/Flow.svelte
<script lang="ts">
	import { writable } from 'svelte/store';
	import {
		SvelteFlow,
		Controls,
		Background,
		BackgroundVariant,
		MiniMap,
		type NodeTypes
	} from '@xyflow/svelte';

	import CustomNode from './CustomNode.svelte';

	import '@xyflow/svelte/dist/style.css';

	const nodeTypes: NodeTypes = {
		custom: CustomNode
	};

	const nodes = writable([
		{
			id: '1',
			type: 'custom',
			data: { label: 'Input Node' },
			position: { x: 150, y: 0 }
		},
		{
			id: '2',
			type: 'default',
			data: { label: 'Node' },
			position: { x: 0, y: 150 }
		},
		{
			id: '3',
			type: 'output',
			data: { label: 'Output Node' },
			position: { x: 300, y: 150 }
		}
	]);

	const edges = writable([
		{
			id: '1-2',
			source: '1',
			target: '2'
		},
		{
			id: '1-3',
			source: '1',
			target: '3'
		}
	]);
</script>

<main>
	<SvelteFlow {nodes} {edges} {nodeTypes} fitView>
		<Controls />
		<Background variant={BackgroundVariant.Dots} />
		<MiniMap />
	</SvelteFlow>
</main>

<style>
	main {
		height: 100%;
		display: flex;
	}
</style>

// examples/vue/src/MultiFlows/Flow.vue
<script lang="ts" setup>
import type { Edge, Node } from '@xyflow/vue';
import { Background, isEdge, isNode, VueFlow } from '@xyflow/vue';

const initialElements: (Node | Edge)[] = [
  { id: '1', type: 'input', data: { label: 'Node 1' }, position: { x: 250, y: 5 }, class: 'light' },
  { id: '2', data: { label: 'Node 2' }, position: { x: 100, y: 100 }, class: 'light' },
  { id: '3', data: { label: 'Node 3' }, position: { x: 400, y: 100 }, class: 'light' },
  { id: '4', data: { label: 'Node 4' }, position: { x: 400, y: 200 }, class: 'light' },
  { id: 'e1-2', source: '1', target: '2', animated: true },
  { id: 'e1-3', source: '1', target: '3' },
];

const nodes = ref<Node[]>(initialElements.filter(isNode));
const edges = ref<Edge[]>(initialElements.filter(isEdge));
</script>

<template>
  <VueFlow v-model:nodes="nodes" v-model:edges="edges" fit-view>
    <Background />
  </VueFlow>
</template>
