// storybook/shared/components/NodeResizer/Flow.svelte
<script lang="ts">
  import { SvelteFlow, Controls, type CoordinateExtent, type Edge } from '@xyflow/svelte';

  import DefaultResizer from './DefaultResizer.svelte';
  import CustomResizer from './CustomResizer.svelte';
  import VerticalResizer from './VerticalResizer.svelte';
  import HorizontalResizer from './HorizontalResizer.svelte';
  import BottomRightResizer from './BottomRightResizer.svelte';
  import FixedExtentNode from './FixedExtentNode.svelte';

  import '@xyflow/svelte/dist/style.css';
  import type { ResizeNode } from './types';
  import { setContext } from 'svelte';
  import { createResizeState, RESIZE_CONTEXT } from './resizeState.svelte';
  import { initialNodes, initialEdges } from './config';
  const store = createResizeState();
  setContext(RESIZE_CONTEXT, store);

  const nodeTypes = {
    defaultResizer: DefaultResizer,
    customResizer: CustomResizer,
    verticalResizer: VerticalResizer,
    horizontalResizer: HorizontalResizer,
    bottomRightResizer: BottomRightResizer,
    fixedExtent: FixedExtentNode,
  };

  let nodes = $state.raw<ResizeNode[]>(
    structuredClone(initialNodes).map((node) => ({
      ...node,
      style: 'border: 1px solid #222; font-size: 10px; background-color: #ddd;',
    })) as ResizeNode[]
  );
  let edges = $state.raw<Edge[]>(structuredClone(initialEdges));

  let { snapToGrid = false }: { snapToGrid?: boolean } = $props();
</script>

<svelte:window
  on:blur={() => {
    store.keepAspectRatio = false;
  }}
  on:keydown={(e) => {
    if (e.key === 'k') store.keepAspectRatio = true;
  }}
  on:keyup={(e) => {
    if (e.key === 'k') store.keepAspectRatio = false;
  }}
/>

<div style="height: 100vh;">
  <SvelteFlow
    bind:nodes
    bind:edges
    {nodeTypes}
    minZoom={0.2}
    maxZoom={5}
    snapGrid={snapToGrid ? [10, 10] : undefined}
    fitView
  >
    <Controls />
  </SvelteFlow>
</div>

// storybook/shared/components/NodeResizer/Flow.vue
<script setup lang="ts">
import { markRaw } from 'vue';
import { VueFlow, Controls } from '@xyflow/vue';
import { initialNodes, initialEdges } from './config';
import { useFlowFixture } from '../../vue/useFlowFixture';
import ResizeNode from './ResizeNode.vue';
defineProps<{ snapToGrid?: boolean }>();
const { nodes, edges, onConnect } = useFlowFixture({ nodes: initialNodes, edges: initialEdges });
const extent = initialNodes.find((node) => node.type === 'fixedExtent')?.data?.extent as
  | [[number, number], [number, number]]
  | undefined;
const nodeTypes = Object.fromEntries(
  ['defaultResizer', 'customResizer', 'verticalResizer', 'horizontalResizer', 'bottomRightResizer', 'fixedExtent'].map(
    (type) => [type, markRaw(ResizeNode)]
  )
);
</script>
<template>
  <VueFlow
    v-model:nodes="nodes"
    v-model:edges="edges"
    :node-types="nodeTypes"
    :snap-to-grid="snapToGrid"
    :snap-grid="[10, 10]"
    :min-zoom="0.2"
    :max-zoom="5"
    fit-view
    only-render-visible-elements
    @connect="onConnect"
    ><Controls />
    <template #zoom-pane>
      <div
        v-if="extent"
        :style="{
          position: 'absolute',
          transform: 'translate(' + extent[0][0] + 'px,' + extent[0][1] + 'px)',
          width: extent[1][0] - extent[0][0] + 'px',
          height: extent[1][1] - extent[0][1] + 'px',
          background: 'rgb(255 0 0 / 25%)',
          pointerEvents: 'none',
        }"
      /> </template
  ></VueFlow>
</template>
