// example/src/SaveRestore/Controls.tsx
import React, { memo, useCallback, Dispatch, FC } from 'react';
import { useReactFlow, Edge, Node, ReactFlowJsonObject } from 'react-flow-renderer';
import localforage from 'localforage';

localforage.config({
  name: 'react-flow',
  storeName: 'flows',
});

const flowKey = 'example-flow';

const getNodeId = () => `randomnode_${+new Date()}`;

type ControlsProps = {
  setNodes: Dispatch<React.SetStateAction<Node<any>[]>>;
  setEdges: Dispatch<React.SetStateAction<Edge<any>[]>>;
};

const Controls: FC<ControlsProps> = ({ setNodes, setEdges }) => {
  const { setViewport, toObject } = useReactFlow();

  const onSave = useCallback(() => {
    const flow = toObject();
    localforage.setItem(flowKey, flow);
  }, [toObject]);

  const onRestore = useCallback(() => {
    const restoreFlow = async () => {
      const flow: ReactFlowJsonObject | null = await localforage.getItem(flowKey);

      if (flow) {
        const { x, y, zoom } = flow.viewport;

        setNodes(flow.nodes || []);
        setEdges(flow.edges || []);
        setViewport({ x, y, zoom: zoom || 0 });
      }
    };

    restoreFlow();
  }, [setNodes, setEdges, setViewport]);

  const onAdd = useCallback(() => {
    const newNode = {
      id: `random_node-${getNodeId()}`,
      data: { label: 'Added node' },
      position: { x: Math.random() * window.innerWidth - 100, y: Math.random() * window.innerHeight },
    };
    setNodes((nds) => nds.concat(newNode));
  }, [setNodes]);

  return (
    <div className="save__controls">
      <button onClick={onSave}>save</button>
      <button onClick={onRestore}>restore</button>
      <button onClick={onAdd}>add node</button>
    </div>
  );
};

export default memo(Controls);

// examples/vue/src/SaveRestore/Controls.vue
<script lang="ts" setup>
import type { Edge, FlowExportObject, Node } from '@xyflow/vue';
import { storeToRefs, useStore, useVueFlow } from '@xyflow/vue';

const flowKey = 'example-flow';

const state = useStorage(flowKey, {
  nodes: [] as Node[],
  edges: [] as Edge[],
  viewport: { x: 0, y: 0, zoom: 1 },
} as FlowExportObject);

function getNodeId() {
  return `randomnode_${Date.now()}`;
}

const { addNodes, setNodes, setEdges, toObject, setViewport } = useVueFlow();

const { dimensions } = storeToRefs(useStore());

function onSave() {
  state.value = toObject();
}

function onRestore() {
  const flow = state.value;

  if (flow) {
    const { x = 0, y = 0, zoom = 1 } = flow.viewport;

    setNodes(flow.nodes);

    setEdges(flow.edges);

    setViewport({ x, y, zoom });
  }
}

function onAdd() {
  addNodes({
    id: `random_node-${getNodeId()}`,
    data: { label: 'Added node' },
    position: { x: Math.random() * dimensions.value.width, y: Math.random() * dimensions.value.height },
  });
}
</script>

<template>
  <div class="save__controls">
    <button @click="onSave">
      save
    </button>
    <button @click="onRestore">
      restore
    </button>
    <button @click="onAdd">
      add node
    </button>
  </div>
</template>
