// packages/react/src/components/UserSelection/index.tsx
import { shallow } from 'zustand/shallow';

import { useStore } from '../../hooks/useStore';

export function UserSelection() {
  const { userSelectionActive, userSelectionRect } = useStore((s) => ({
    userSelectionActive: s.userSelectionActive,
    userSelectionRect: s.userSelectionRect,
  }), shallow);
  const isActive = userSelectionActive && userSelectionRect;

  if (!isActive) {
    return null;
  }

  return (
    <div
      className="react-flow__selection react-flow__container"
      style={{
        width: userSelectionRect.width,
        height: userSelectionRect.height,
        transform: `translate(${userSelectionRect.x}px, ${userSelectionRect.y}px)`,
      }}
    />
  );
}

// packages/vue/src/components/UserSelection/UserSelection.vue
<script lang="ts" setup>
import type { SelectionRect } from '@xyflow/system';

defineProps<{ userSelectionRect: SelectionRect }>();
</script>

<script lang="ts">
export default {
  name: 'UserSelection',
  compatConfig: { MODE: 3 },
};
</script>

<template>
  <div
    class="vue-flow__selection vue-flow__container"
    :style="{
      width: `${userSelectionRect.width}px`,
      height: `${userSelectionRect.height}px`,
      transform: `translate(${userSelectionRect.x}px, ${userSelectionRect.y}px)`,
    }"
  />
</template>
