// packages/react/src/container/EdgeRenderer/index.tsx
import { memo, ReactNode } from 'react';

import { useStore, useShallow } from '../../hooks/useStore';
import { useVisibleEdgeIds } from '../../hooks/useVisibleEdgeIds';
import MarkerDefinitions from './MarkerDefinitions';
import { GraphViewProps } from '../GraphView';
import EdgeWrapper from '../../components/EdgeWrapper';
import type { Edge, ReactFlowState, Node } from '../../types';

type EdgeRendererProps<EdgeType extends Edge = Edge> = Pick<
  GraphViewProps<Node, EdgeType>,
  | 'onEdgeClick'
  | 'onEdgeDoubleClick'
  | 'defaultMarkerColor'
  | 'onlyRenderVisibleElements'
  | 'onReconnect'
  | 'onEdgeContextMenu'
  | 'onEdgeMouseEnter'
  | 'onEdgeMouseMove'
  | 'onEdgeMouseLeave'
  | 'onReconnectStart'
  | 'onReconnectEnd'
  | 'reconnectRadius'
  | 'noPanClassName'
  | 'rfId'
  | 'disableKeyboardA11y'
  | 'edgeTypes'
> & {
  children?: ReactNode;
};

const selector = (s: ReactFlowState) => ({
  edgesFocusable: s.edgesFocusable,
  edgesReconnectable: s.edgesReconnectable,
  elementsSelectable: s.elementsSelectable,
  connectionMode: s.connectionMode,
  onError: s.onError,
});

function EdgeRendererComponent<EdgeType extends Edge = Edge>({
  defaultMarkerColor,
  onlyRenderVisibleElements,
  rfId,
  edgeTypes,
  noPanClassName,
  onReconnect,
  onEdgeContextMenu,
  onEdgeMouseEnter,
  onEdgeMouseMove,
  onEdgeMouseLeave,
  onEdgeClick,
  reconnectRadius,
  onEdgeDoubleClick,
  onReconnectStart,
  onReconnectEnd,
  disableKeyboardA11y,
}: EdgeRendererProps<EdgeType>) {
  const { edgesFocusable, edgesReconnectable, elementsSelectable, onError } = useStore(useShallow(selector));
  const edgeIds = useVisibleEdgeIds(onlyRenderVisibleElements);

  return (
    <div className="react-flow__edges">
      <MarkerDefinitions defaultColor={defaultMarkerColor} rfId={rfId} />

      {edgeIds.map((id) => {
        return (
          <EdgeWrapper<EdgeType>
            key={id}
            id={id}
            edgesFocusable={edgesFocusable}
            edgesReconnectable={edgesReconnectable}
            elementsSelectable={elementsSelectable}
            noPanClassName={noPanClassName}
            onReconnect={onReconnect}
            onContextMenu={onEdgeContextMenu}
            onMouseEnter={onEdgeMouseEnter}
            onMouseMove={onEdgeMouseMove}
            onMouseLeave={onEdgeMouseLeave}
            onClick={onEdgeClick}
            reconnectRadius={reconnectRadius}
            onDoubleClick={onEdgeDoubleClick}
            onReconnectStart={onReconnectStart}
            onReconnectEnd={onReconnectEnd}
            rfId={rfId}
            onError={onError}
            edgeTypes={edgeTypes}
            disableKeyboardA11y={disableKeyboardA11y}
          />
        );
      })}
    </div>
  );
}

EdgeRendererComponent.displayName = 'EdgeRenderer';

export const EdgeRenderer = memo(EdgeRendererComponent) as typeof EdgeRendererComponent;

// packages/solidjs/src/container/EdgeRenderer/index.tsx
// import { memo, ReactNode } from 'react';
// import { shallow } from 'zustand/shallow';

import { useStore, useStoreApi } from '../../hooks/useStore';
import { useVisibleEdgeIds } from '../../hooks/useVisibleEdgeIds';
import MarkerDefinitions from './MarkerDefinitions';
import { GraphViewProps } from '../GraphView';
import { EdgeWrapper } from '../../components/EdgeWrapper';
import type { Edge, SolidFlowState, Node } from '../../types';
import { For, ParentProps } from 'solid-js';

type EdgeRendererProps<NodeType extends Node, EdgeType extends Edge> = Pick<
  GraphViewProps<NodeType, EdgeType>,
  | 'onEdgeClick'
  | 'onEdgeDoubleClick'
  | 'defaultMarkerColor'
  | 'onlyRenderVisibleElements'
  | 'onReconnect'
  | 'onEdgeContextMenu'
  | 'onEdgeMouseEnter'
  | 'onEdgeMouseMove'
  | 'onEdgeMouseLeave'
  | 'onReconnectStart'
  | 'onReconnectEnd'
  | 'reconnectRadius'
  | 'noPanClassName'
  | 'rfId'
  | 'disableKeyboardA11y'
  | 'edgeTypes'
>;

const selector = (s: SolidFlowState) => ({
  edgesFocusable: () => s.edgesFocusable.get(),
  edgesReconnectable: () => s.edgesReconnectable.get(),
  elementsSelectable: () => s.elementsSelectable.get(),
  connectionMode: () => s.connectionMode.get(),
  onError: () => s.onError.get(),
});

function EdgeRendererComponent<NodeType extends Node = Node, EdgeType extends Edge = Edge>(
  p: ParentProps<EdgeRendererProps<NodeType, EdgeType>>
) {
  const storeData = useStore(selector);
  const edgeIds = useVisibleEdgeIds(() => p.onlyRenderVisibleElements);

  return (
    <div class="react-flow__edges">
      <MarkerDefinitions defaultColor={p.defaultMarkerColor} rfId={p.rfId} />

      <For each={edgeIds()}>
        {(id) => {
          return (
            <EdgeWrapper<EdgeType>
              id={id}
              edgesFocusable={storeData.edgesFocusable()}
              edgesReconnectable={storeData.edgesReconnectable()}
              elementsSelectable={storeData.elementsSelectable()}
              noPanClassName={p.noPanClassName}
              onReconnect={p.onReconnect}
              onContextMenu={p.onEdgeContextMenu}
              onMouseEnter={p.onEdgeMouseEnter}
              onMouseMove={p.onEdgeMouseMove}
              onMouseLeave={p.onEdgeMouseLeave}
              onClick={p.onEdgeClick}
              reconnectRadius={p.reconnectRadius}
              onDoubleClick={p.onEdgeDoubleClick}
              onReconnectStart={p.onReconnectStart}
              onReconnectEnd={p.onReconnectEnd}
              rfId={p.rfId}
              onError={storeData.onError()}
              edgeTypes={p.edgeTypes}
              disableKeyboardA11y={p.disableKeyboardA11y}
            />
          );
        }}
      </For>
    </div>
  );
}

EdgeRendererComponent.displayName = 'EdgeRenderer';

export const EdgeRenderer = EdgeRendererComponent;
