// src/container/EdgeRenderer/MarkerSymbols.tsx
import React, { useMemo } from 'react';
import { MarkerType, EdgeMarker } from '../../types';

type SymbolProps = Omit<EdgeMarker, 'type'>;

const ArrowSymbol = ({ color = 'none', strokeWidth = 1 }: SymbolProps) => {
  return (
    <polyline
      stroke={color}
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
      fill="none"
      points="-5,-4 0,0 -5,4"
    />
  );
};

const ArrowClosedSymbol = ({ color = 'none', strokeWidth = 1 }: SymbolProps) => {
  return (
    <polyline
      stroke={color}
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
      fill={color}
      points="-5,-4 0,0 -5,4 -5,-4"
    />
  );
};

export const MarkerSymbols = {
  [MarkerType.Arrow]: ArrowSymbol,
  [MarkerType.ArrowClosed]: ArrowClosedSymbol,
};

export function useMarkerSymbol(type: MarkerType) {
  const symbol = useMemo(() => {
    const symbolExists = MarkerSymbols.hasOwnProperty(type);

    if (!symbolExists) {
      console.warn(`marker type "${type}" doesn't exist.`);
      return () => null;
    }

    return MarkerSymbols[type];
  }, [type]);
  return symbol;
}

export default MarkerSymbols;

// packages/solidjs/src/container/EdgeRenderer/MarkerSymbols.tsx
// import { useMemo } from 'react';
import { errorMessages, MarkerType, type EdgeMarker } from '@xyflow/system';

import { useStoreApi } from '../../hooks/useStore';
import { mergeProps } from 'solid-js';

type SymbolProps = Omit<EdgeMarker, 'type'>;

const ArrowSymbol = (_p: SymbolProps) => {
  
  // { color = 'none', strokeWidth = 1 }: SymbolProps) => {
    const p = mergeProps({ color: 'none', strokeWidth: 1 }, _p);

  return (
    <polyline
      style={{
        stroke: p.color,
        "stroke-width": p.strokeWidth  ? p.strokeWidth + "px" : undefined,
      }}
      stroke-linecap="round"
      stroke-linejoin="round"
      fill="none"
      points="-5,-4 0,0 -5,4"
    />
  );
};

const ArrowClosedSymbol = (_p: SymbolProps) => {
  // { color = 'none', strokeWidth = 1 }: SymbolProps) => {
    const p = mergeProps({ color: 'none', strokeWidth: 1 }, _p);

  return (
    <polyline
      style={{
        stroke: p.color,
        fill: p.color,
        "stroke-width": p.strokeWidth ? p.strokeWidth + "px" : undefined,
      }}
      stroke-linecap="round"
      stroke-linejoin="round"
      points="-5,-4 0,0 -5,4 -5,-4"
    />
  );
};

export const MarkerSymbols = {
  [MarkerType.Arrow]: ArrowSymbol,
  [MarkerType.ArrowClosed]: ArrowClosedSymbol,
};

export function useMarkerSymbol(type: () => MarkerType) {
  const store = useStoreApi();

  const symbol = () => {
    const symbolExists = Object.prototype.hasOwnProperty.call(MarkerSymbols, type());

    if (!symbolExists) {
      store.onError.get()?.('009', errorMessages['error009'](type()));

      return null;
    }

    return MarkerSymbols[type()];
  };

  return symbol;
}
