// packages/vue/src/components/Panel/Panel.vue
<script lang="ts" setup>
import type { PanelProps } from '../../types/panel';
import { computed } from 'vue';
import { storeToRefs, useStore } from '../../composables';

const props = defineProps<PanelProps>();

const { userSelectionActive } = storeToRefs(useStore());

const positionClasses = computed(() => `${props.position}`.split('-'));
</script>

<script lang="ts">
export default {
  name: 'Panel',
  compatConfig: { MODE: 3 },
};
</script>

<template>
  <div
    class="vue-flow__panel"
    :class="positionClasses"
    :aria-label="label ?? undefined"
    :style="{ pointerEvents: userSelectionActive ? 'none' : 'all' }"
  >
    <slot />
  </div>
</template>

// packages/core/src/components/Panel/index.tsx
import React, { type HTMLAttributes, type ReactNode } from 'react';
import cc from 'classcat';

import { useStore } from '../../hooks/useStore';
import type { PanelPosition, ReactFlowState } from '../../types';

export type PanelProps = HTMLAttributes<HTMLDivElement> & {
  position: PanelPosition;
  children: ReactNode;
};

const selector = (s: ReactFlowState) => (s.userSelectionActive ? 'none' : 'all');

function Panel({ position, children, className, style, ...rest }: PanelProps) {
  const pointerEvents = useStore(selector);
  const positionClasses = `${position}`.split('-');

  return (
    <div
      className={cc(['react-flow__panel', className, ...positionClasses])}
      style={{ ...style, pointerEvents }}
      {...rest}
    >
      {children}
    </div>
  );
}

export default Panel;
