// packages/svelte/src/lib/container/Panel/Panel.svelte
<script lang="ts">
  import type { PanelProps } from './types';
  import { useStore } from '$lib/store';

  let { position = 'top-right', style, class: className, children, ...rest }: PanelProps = $props();

  const store = useStore();

  let positionClasses = $derived(`${position}`.split('-'));
</script>

<div
  class={['svelte-flow__panel', className, ...positionClasses]}
  {style}
  style:pointer-events={store.selectionRectMode ? 'none' : ''}
  {...rest}
>
  {@render children?.()}
</div>

// packages/core/src/components/Panel/index.tsx
import React, { type HTMLAttributes, type ReactNode } from 'react';
import cc from 'classcat';

import { useStore } from '../../hooks/useStore';
import type { PanelPosition, ReactFlowState } from '../../types';

export type PanelProps = HTMLAttributes<HTMLDivElement> & {
  position: PanelPosition;
  children: ReactNode;
};

const selector = (s: ReactFlowState) => (s.userSelectionActive ? 'none' : 'all');

function Panel({ position, children, className, style, ...rest }: PanelProps) {
  const pointerEvents = useStore(selector);
  const positionClasses = `${position}`.split('-');

  return (
    <div
      className={cc(['react-flow__panel', className, ...positionClasses])}
      style={{ ...style, pointerEvents }}
      {...rest}
    >
      {children}
    </div>
  );
}

export default Panel;
