// examples/react/src/examples/DetachedHandle/index.tsx
import { ReactFlow, Node, ReactFlowProvider, Background, BackgroundVariant, NodeProps, Handle, Position } from '@xyflow/react';

import './style.css';

const initialNodes: Node[] = [
  {
    id: '1',
    data: { label: 'Node 1' },
    position: { x: 250, y: 5 },
  },
  {
    id: '2',
    data: { label: 'Node 2' },
    position: { x: 50, y: 100 },
  },
  {
    id: '3',
    data: { label: 'Node 3' },
    position: { x: 450, y: 100 },
  },
];

const CustomNode = (_: NodeProps) => {
  return (
    <>
      <Handle type="target" position={Position.Left} />
      <div>Custom node</div>
      <Handle type="source" position={Position.Right}>
        <button className="detached-handle">➡️</button>
      </Handle>
    </>
  );
};

const nodeTypes = {
  default: CustomNode,
};

const DetachedHandle = () => {
  return (
    <ReactFlow defaultNodes={initialNodes} nodeTypes={nodeTypes} fitView>
      <Background variant={BackgroundVariant.Lines} />
    </ReactFlow>
  );
};

export default function App() {
  return (
    <ReactFlowProvider>
      <DetachedHandle />
    </ReactFlowProvider>
  );
}

// examples/svelte/src/routes/examples/detached-handle/+page.svelte
<script lang="ts">
	import {
		SvelteFlow,
		Background,
		MiniMap,
		Position,
		type Node,
		type NodeTypes,
		type Edge
	} from '@xyflow/svelte';
	import CustomNode from './CustomNode.svelte';

	import '@xyflow/svelte/dist/style.css';

	const nodeTypes: NodeTypes = {
		custom: CustomNode
	};

	let nodes = $state.raw<Node[]>([
		{
			id: '1',
			type: 'custom',
			data: { label: 'node 1' },
			position: { x: 0, y: 0 },
			sourcePosition: Position.Right
		},
		{
			id: '2',
			type: 'custom',
			data: { label: 'node 2' },
			position: { x: 250, y: 250 }
		}
	]);

	let edges = $state.raw<Edge[]>([]);
</script>

<SvelteFlow bind:nodes bind:edges {nodeTypes} fitView>
	<Background />
	<MiniMap />
</SvelteFlow>
