// packages/react/src/container/Pane/index.tsx
import {
  useRef,
  type MouseEvent as ReactMouseEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { shallow } from 'zustand/shallow';
import cc from 'classcat';
import {
  getNodesInside,
  getEventPosition,
  SelectionMode,
  areSetsEqual,
  type NodeChange,
  type EdgeChange,
} from '@xyflow/system';

import { UserSelection } from '../../components/UserSelection';
import { containerStyle } from '../../styles/utils';
import { useStore, useStoreApi } from '../../hooks/useStore';
import { getSelectionChanges } from '../../utils';
import type { ReactFlowProps, ReactFlowState } from '../../types';

type PaneProps = {
  isSelecting: boolean;
  selectionKeyPressed: boolean;
  children: ReactNode;
} & Partial<
  Pick<
    ReactFlowProps,
    | 'selectionMode'
    | 'panOnDrag'
    | 'onSelectionStart'
    | 'onSelectionEnd'
    | 'onPaneClick'
    | 'onPaneContextMenu'
    | 'onPaneScroll'
    | 'onPaneMouseEnter'
    | 'onPaneMouseMove'
    | 'onPaneMouseLeave'
    | 'selectionOnDrag'
    | 'paneClickDistance'
  >
>;

const wrapHandler = (
  handler: React.MouseEventHandler | undefined,
  containerRef: React.MutableRefObject<HTMLDivElement | null>
): React.MouseEventHandler => {
  return (event: ReactMouseEvent) => {
    if (event.target !== containerRef.current) {
      return;
    }
    handler?.(event);
  };
};

const selector = (s: ReactFlowState) => ({
  userSelectionActive: s.userSelectionActive,
  elementsSelectable: s.elementsSelectable,
  connectionInProgress: s.connection.inProgress,
  dragging: s.paneDragging,
});

export function Pane({
  isSelecting,
  selectionKeyPressed,
  selectionMode = SelectionMode.Full,
  panOnDrag,
  paneClickDistance = 0,
  selectionOnDrag,
  onSelectionStart,
  onSelectionEnd,
  onPaneClick,
  onPaneContextMenu,
  onPaneScroll,
  onPaneMouseEnter,
  onPaneMouseMove,
  onPaneMouseLeave,
  children,
}: PaneProps) {
  const store = useStoreApi();
  const { userSelectionActive, elementsSelectable, dragging, connectionInProgress } = useStore(selector, shallow);
  const hasActiveSelection = elementsSelectable && (isSelecting || userSelectionActive);

  const container = useRef<HTMLDivElement | null>(null);
  const containerBounds = useRef<DOMRect>();

  const selectedNodeIds = useRef<Set<string>>(new Set());
  const selectedEdgeIds = useRef<Set<string>>(new Set());

  // Used to prevent click events when the user lets go of the selectionKey during a selection
  const selectionInProgress = useRef<boolean>(false);
  const selectionStarted = useRef<boolean>(false);

  const onClick = (event: ReactMouseEvent) => {
    // We prevent click events when the user let go of the selectionKey during a selection
    // We also prevent click events when a connection is in progress
    if (selectionInProgress.current || connectionInProgress) {
      selectionInProgress.current = false;
      return;
    }

    onPaneClick?.(event);
    store.getState().resetSelectedElements();
    store.setState({ nodesSelectionActive: false });
  };

  const onContextMenu = (event: ReactMouseEvent) => {
    if (Array.isArray(panOnDrag) && panOnDrag?.includes(2)) {
      event.preventDefault();
      return;
    }

    onPaneContextMenu?.(event);
  };

  const onWheel = onPaneScroll ? (event: React.WheelEvent) => onPaneScroll(event) : undefined;

  const onClickCapture = (event: ReactMouseEvent) => {
    if (selectionInProgress.current) {
      event.stopPropagation();
    }
  };

  // We are using capture here in order to prevent other pointer events
  // to be able to create a selection above a node or an edge
  const onPointerDownCapture = (event: ReactPointerEvent): void => {
    const { resetSelectedElements, domNode } = store.getState();
    containerBounds.current = domNode?.getBoundingClientRect();

    const isNoKeyEvent = event.target !== container.current && !!(event.target as HTMLElement).closest('.nokey');
    const isSelectionActive =
      (selectionOnDrag && container.current === event.target) || !selectionOnDrag || selectionKeyPressed;

    if (
      !elementsSelectable ||
      !isSelecting ||
      event.button !== 0 ||
      !containerBounds.current ||
      isNoKeyEvent ||
      !isSelectionActive ||
      !event.isPrimary
    ) {
      return;
    }

    (event.target as Partial<Element>)?.setPointerCapture?.(event.pointerId);

    selectionStarted.current = true;
    selectionInProgress.current = false;

    const { x, y } = getEventPosition(event.nativeEvent, containerBounds.current);

    store.setState({
      userSelectionRect: {
        width: 0,
        height: 0,
        startX: x,
        startY: y,
        x,
        y,
      },
    });

    if (event.target !== container.current || paneClickDistance === 0) {
      event.stopPropagation();
      event.preventDefault();

      resetSelectedElements();

      onSelectionStart?.(event);
    }
  };

  const onPointerMove = (event: ReactPointerEvent): void => {
    const {
      userSelectionRect,
      transform,
      nodeLookup,
      edgeLookup,
      connectionLookup,
      triggerNodeChanges,
      triggerEdgeChanges,
      defaultEdgeOptions,
    } = store.getState();

    if (!containerBounds.current || !userSelectionRect) {
      return;
    }

    const { x: mouseX, y: mouseY } = getEventPosition(event.nativeEvent, containerBounds.current);
    const { startX, startY } = userSelectionRect;

    if (
      !selectionInProgress.current &&
      event.target === container.current &&
      !selectionKeyPressed &&
      paneClickDistance > 0
    ) {
      const distance = Math.hypot(mouseX - startX, mouseY - startY);
      if (distance <= paneClickDistance) {
        return;
      }
    }

    selectionInProgress.current = true;

    const nextUserSelectRect = {
      startX,
      startY,
      x: mouseX < startX ? mouseX : startX,
      y: mouseY < startY ? mouseY : startY,
      width: Math.abs(mouseX - startX),
      height: Math.abs(mouseY - startY),
    };

    const prevSelectedNodeIds = selectedNodeIds.current;
    const prevSelectedEdgeIds = selectedEdgeIds.current;

    selectedNodeIds.current = new Set(
      getNodesInside(nodeLookup, nextUserSelectRect, transform, selectionMode === SelectionMode.Partial, true).map(
        (node) => node.id
      )
    );

    selectedEdgeIds.current = new Set();
    const edgesSelectable = defaultEdgeOptions?.selectable ?? true;

    // We look for all edges connected to the selected nodes
    for (const nodeId of selectedNodeIds.current) {
      const connections = connectionLookup.get(nodeId);
      if (!connections) continue;
      for (const { edgeId } of connections.values()) {
        const edge = edgeLookup.get(edgeId);
        if (edge && (edge.selectable ?? edgesSelectable)) {
          selectedEdgeIds.current.add(edgeId);
        }
      }
    }

    if (!areSetsEqual(prevSelectedNodeIds, selectedNodeIds.current)) {
      const changes = getSelectionChanges(nodeLookup, selectedNodeIds.current, true) as NodeChange[];
      triggerNodeChanges(changes);
    }

    if (!areSetsEqual(prevSelectedEdgeIds, selectedEdgeIds.current)) {
      const changes = getSelectionChanges(edgeLookup, selectedEdgeIds.current) as EdgeChange[];
      triggerEdgeChanges(changes);
    }

    store.setState({
      userSelectionRect: nextUserSelectRect,
      userSelectionActive: true,
      nodesSelectionActive: false,
    });
  };

  const onPointerUp = (event: ReactPointerEvent) => {
    if (event.button !== 0 || !selectionStarted.current) {
      return;
    }

    (event.target as Partial<Element>)?.releasePointerCapture?.(event.pointerId);

    const { userSelectionRect } = store.getState();
    /*
     * We only want to trigger click functions when in selection mode if
     * the user did not move the mouse.
     */
    if (!userSelectionActive && userSelectionRect && event.target === container.current) {
      onClick?.(event);
    }

    store.setState({
      userSelectionActive: false,
      userSelectionRect: null,
      nodesSelectionActive: selectedNodeIds.current.size > 0,
    });
    onSelectionEnd?.(event);

    /*
     * If the user kept holding the selectionKey during the selection,
     * we need to reset the selectionInProgress, so the next click event is not prevented
     */
    if (selectionKeyPressed || selectionOnDrag) {
      selectionInProgress.current = false;
    }

    selectionStarted.current = false;
  };

  const draggable = panOnDrag === true || (Array.isArray(panOnDrag) && panOnDrag.includes(0));

  return (
    <div
      className={cc(['react-flow__pane', { draggable, dragging, selection: isSelecting }])}
      onClick={hasActiveSelection ? undefined : wrapHandler(onClick, container)}
      onContextMenu={wrapHandler(onContextMenu, container)}
      onWheel={wrapHandler(onWheel, container)}
      onPointerEnter={hasActiveSelection ? undefined : onPaneMouseEnter}
      onPointerMove={hasActiveSelection ? onPointerMove : onPaneMouseMove}
      onPointerUp={hasActiveSelection ? onPointerUp : undefined}
      onPointerDownCapture={hasActiveSelection ? onPointerDownCapture : undefined}
      onClickCapture={hasActiveSelection ? onClickCapture : undefined}
      onPointerLeave={onPaneMouseLeave}
      ref={container}
      style={containerStyle}
    >
      {children}
      <UserSelection />
    </div>
  );
}

// packages/solidjs/src/container/Pane/index.tsx
/**
 * The user selection rectangle gets displayed when a user drags the mouse while pressing shift
 */

import cc from 'classcat';
import {
  getNodesInside,
  getEventPosition,
  SelectionMode,
  areSetsEqual,
  type NodeChange,
  type EdgeChange,
} from '@xyflow/system';

import { UserSelection } from '../../components/UserSelection';
import { containerStyle } from '../../styles/utils';
import { useStore, useStoreApi } from '../../hooks/useStore';
import { getSelectionChanges } from '../../utils';
import type { ReactFlowProps, SolidFlowState } from '../../types';
import { mergeProps, JSX, ParentProps } from 'solid-js';
import { useRef } from '../../utils/hooks';

type PaneProps = {
  isSelecting: boolean;
  selectionKeyPressed: boolean;
} & Partial<
  Pick<
    ReactFlowProps,
    | 'selectionMode'
    | 'panOnDrag'
    | 'onSelectionStart'
    | 'onSelectionEnd'
    | 'onPaneClick'
    | 'onPaneContextMenu'
    | 'onPaneScroll'
    | 'onPaneMouseEnter'
    | 'onPaneMouseMove'
    | 'onPaneMouseLeave'
    | 'selectionOnDrag'
  >
>;

const wrapHandler = <T extends HTMLElement>(
  handler: ((event: MouseEvent) => void) | undefined,
  containerRef: { current: T | null }
): ((event: MouseEvent) => void) => {
  return (event: MouseEvent) => {
    if (event.target !== containerRef.current) {
      return;
    }
    handler?.(event);
  };
};

const selector = (s: SolidFlowState) => ({
  userSelectionActive: () => s.userSelectionActive.get(),
  elementsSelectable: () => s.elementsSelectable.get(),
  connectionInProgress: () => s.connection.get().inProgress,
  dragging: () => s.paneDragging.get(),
});

export function Pane(_p: ParentProps<PaneProps>) {
  const p = mergeProps(
    {
      selectionMode: SelectionMode.Full,
    } satisfies Partial<PaneProps>,
    _p
  );

  const store = useStoreApi();
  const storeData = useStore(selector);
  const hasActiveSelection = () => storeData.elementsSelectable() && (p.isSelecting || storeData.userSelectionActive());

  const container = useRef<HTMLDivElement | null>(null);
  const containerBounds = useRef<DOMRect | null>(null);

  const selectedNodeIds = useRef<Set<string>>(new Set());
  const selectedEdgeIds = useRef<Set<string>>(new Set());

  // Used to prevent click events when the user lets go of the selectionKey during a selection
  const selectionInProgress = useRef<boolean>(false);
  const selectionStarted = useRef<boolean>(false);

  const onClick = (event: MouseEvent) => {
    // We prevent click events when the user let go of the selectionKey during a selection
    // We also prevent click events when a connection is in progress
    if (selectionInProgress.current || storeData.connectionInProgress()) {
      selectionInProgress.current = false;
      return;
    }

    p.onPaneClick?.(event);
    store.resetSelectedElements();
    store.nodesSelectionActive.set(false);
  };

  const onContextMenu = (event: MouseEvent) => {
    if (Array.isArray(p.panOnDrag) && p.panOnDrag?.includes(2)) {
      event.preventDefault();
      return;
    }

    p.onPaneContextMenu?.(event);
  };

  const onWheel = p.onPaneScroll ? (event: WheelEvent) => p.onPaneScroll!(event) : undefined;

  const onPointerDown = (event: PointerEvent): void => {
    const domNodeRect = store.domNode.get()?.getBoundingClientRect();
    if (!domNodeRect) {
      return;
    }
    containerBounds.current = domNodeRect;

    if (
      !storeData.elementsSelectable() ||
      !p.isSelecting ||
      event.button !== 0 ||
      event.target !== container.current ||
      !containerBounds.current
    ) {
      return;
    }

    (event.target as Partial<Element> | null)?.setPointerCapture?.(event.pointerId);

    selectionStarted.current = true;
    selectionInProgress.current = false;

    const { x, y } = getEventPosition(event, containerBounds.current);

    store.resetSelectedElements();

    store.userSelectionRect.set({
      width: 0,
      height: 0,
      startX: x,
      startY: y,
      x,
      y,
    });

    p.onSelectionStart?.(event);
  };

  const onPointerMove = (event: PointerEvent): void => {
    if (!containerBounds.current || !store.userSelectionRect.get()) {
      return;
    }

    selectionInProgress.current = true;

    const { x: mouseX, y: mouseY } = getEventPosition(event, containerBounds.current);
    const userSelectionRect = store.userSelectionRect.get()!;
    const { startX, startY } = userSelectionRect;

    const nextUserSelectRect = {
      startX,
      startY,
      x: mouseX < startX ? mouseX : startX,
      y: mouseY < startY ? mouseY : startY,
      width: Math.abs(mouseX - startX),
      height: Math.abs(mouseY - startY),
    };

    const prevSelectedNodeIds = selectedNodeIds.current;
    const prevSelectedEdgeIds = selectedEdgeIds.current;

    selectedNodeIds.current = new Set(
      getNodesInside(
        store.nodeLookup,
        nextUserSelectRect,
        store.transform.get(),
        p.selectionMode === SelectionMode.Partial,
        true
      ).map((node) => node.id)
    );

    selectedEdgeIds.current = new Set();
    const edgesSelectable = store.defaultEdgeOptions?.selectable ?? true;

    // We look for all edges connected to the selected nodes
    for (const nodeId of selectedNodeIds.current) {
      const connections = store.connectionLookup.get(nodeId);
      if (!connections) continue;
      for (const { edgeId } of connections.values()) {
        const edge = store.edgeLookup.get(edgeId);
        if (edge && (edge.selectable ?? edgesSelectable)) {
          selectedEdgeIds.current.add(edgeId);
        }
      }
    }

    if (!areSetsEqual(prevSelectedNodeIds, selectedNodeIds.current)) {
      const changes = getSelectionChanges(store.nodeLookup, selectedNodeIds.current, true) as NodeChange[];
      store.triggerNodeChanges(changes);
    }

    if (!areSetsEqual(prevSelectedEdgeIds, selectedEdgeIds.current)) {
      const changes = getSelectionChanges(store.edgeLookup, selectedEdgeIds.current) as EdgeChange[];
      store.triggerEdgeChanges(changes);
    }

    store.userSelectionRect.set(nextUserSelectRect);
    store.userSelectionActive.set(true);
    store.nodesSelectionActive.set(false);
  };

  const onPointerUp = (event: PointerEvent) => {
    if (event.button !== 0 || !selectionStarted.current) {
      return;
    }

    (event.target as Partial<Element>)?.releasePointerCapture?.(event.pointerId);
    const userSelectionRect = store.userSelectionRect.get();

    /*
     * We only want to trigger click functions when in selection mode if
     * the user did not move the mouse.
     */
    if (!storeData.userSelectionActive() && userSelectionRect && event.target === container.current) {
      onClick(event as any);
    }

    store.userSelectionActive.set(false);
    store.userSelectionRect.set(null);
    store.nodesSelectionActive.set(selectedNodeIds.current.size > 0);

    p.onSelectionEnd?.(event);

    /*
     * If the user kept holding the selectionKey during the selection,
     * we need to reset the selectionInProgress, so the next click event is not prevented
     */
    if (p.selectionKeyPressed || p.selectionOnDrag) {
      selectionInProgress.current = false;
    }

    selectionStarted.current = false;
  };

  const draggable = () => p.panOnDrag === true || (Array.isArray(p.panOnDrag) && p.panOnDrag.includes(0));

  const wrapWheelHandler = (
    handler: ((event: WheelEvent) => void) | undefined,
    containerRef: { current: HTMLDivElement | null }
  ): ((event: WheelEvent) => void) | undefined => {
    if (!handler) return undefined;
    return (event: WheelEvent) => {
      if (event.target !== containerRef.current) {
        return;
      }
      handler(event);
    };
  };

  return (
    <div
      class={cc([
        'react-flow__pane',
        { draggable: draggable(), dragging: storeData.dragging(), selection: p.isSelecting },
      ])}
      onClick={hasActiveSelection() ? undefined : wrapHandler(onClick, container)}
      onContextMenu={wrapHandler(onContextMenu, container)}
      onWheel={wrapWheelHandler(onWheel, container)}
      onPointerEnter={hasActiveSelection() ? undefined : p.onPaneMouseEnter}
      onPointerDown={hasActiveSelection() ? onPointerDown : p.onPaneMouseMove}
      onPointerMove={hasActiveSelection() ? onPointerMove : p.onPaneMouseMove}
      onPointerUp={hasActiveSelection() ? onPointerUp : undefined}
      onPointerLeave={p.onPaneMouseLeave}
      ref={(el) => (container.current = el)}
      style={containerStyle}
    >
      {p.children}
      <UserSelection />
    </div>
  );
}
