// packages/core/src/container/Pane/index.tsx
/**
 * The user selection rectangle gets displayed when a user drags the mouse while pressing shift
 */

import { memo, useRef, type MouseEvent as ReactMouseEvent, type ReactNode } from 'react';
import { shallow } from 'zustand/shallow';
import cc from 'classcat';
import { getNodesInside, getEventPosition } from '@reactflow/utils';
import { SelectionMode } from '@reactflow/system';

import UserSelection from '../../components/UserSelection';
import { containerStyle } from '../../styles';
import { useStore, useStoreApi } from '../../hooks/useStore';
import { getSelectionChanges, getConnectedEdges } from '../../utils';
import type { ReactFlowProps, ReactFlowState, NodeChange, EdgeChange, Node } from '../../types';

type PaneProps = {
  isSelecting: boolean;
  children: ReactNode;
} & Partial<
  Pick<
    ReactFlowProps,
    | 'selectionMode'
    | 'panOnDrag'
    | 'onSelectionStart'
    | 'onSelectionEnd'
    | 'onPaneClick'
    | 'onPaneContextMenu'
    | 'onPaneScroll'
    | 'onPaneMouseEnter'
    | 'onPaneMouseMove'
    | 'onPaneMouseLeave'
  >
>;

const wrapHandler = (
  handler: React.MouseEventHandler | undefined,
  containerRef: React.MutableRefObject<HTMLDivElement | null>
): React.MouseEventHandler => {
  return (event: ReactMouseEvent) => {
    if (event.target !== containerRef.current) {
      return;
    }
    handler?.(event);
  };
};

const selector = (s: ReactFlowState) => ({
  userSelectionActive: s.userSelectionActive,
  elementsSelectable: s.elementsSelectable,
  dragging: s.paneDragging,
});

const Pane = memo(
  ({
    isSelecting,
    selectionMode = SelectionMode.Full,
    panOnDrag,
    onSelectionStart,
    onSelectionEnd,
    onPaneClick,
    onPaneContextMenu,
    onPaneScroll,
    onPaneMouseEnter,
    onPaneMouseMove,
    onPaneMouseLeave,
    children,
  }: PaneProps) => {
    const container = useRef<HTMLDivElement | null>(null);
    const store = useStoreApi();
    const prevSelectedNodesCount = useRef<number>(0);
    const prevSelectedEdgesCount = useRef<number>(0);
    const containerBounds = useRef<DOMRect>();
    const { userSelectionActive, elementsSelectable, dragging } = useStore(selector, shallow);

    const resetUserSelection = () => {
      store.setState({ userSelectionActive: false, userSelectionRect: null });

      prevSelectedNodesCount.current = 0;
      prevSelectedEdgesCount.current = 0;
    };

    const onClick = (event: ReactMouseEvent) => {
      onPaneClick?.(event);
      store.getState().resetSelectedElements();
      store.setState({ nodesSelectionActive: false });
    };

    const onContextMenu = (event: ReactMouseEvent) => {
      if (Array.isArray(panOnDrag) && panOnDrag?.includes(2)) {
        event.preventDefault();
        return;
      }

      onPaneContextMenu?.(event);
    };

    const onWheel = onPaneScroll ? (event: React.WheelEvent) => onPaneScroll(event) : undefined;

    const onMouseDown = (event: ReactMouseEvent): void => {
      const { resetSelectedElements, domNode } = store.getState();
      containerBounds.current = domNode?.getBoundingClientRect();

      if (
        !elementsSelectable ||
        !isSelecting ||
        event.button !== 0 ||
        event.target !== container.current ||
        !containerBounds.current
      ) {
        return;
      }

      const { x, y } = getEventPosition(event, containerBounds.current);

      resetSelectedElements();

      store.setState({
        userSelectionRect: {
          width: 0,
          height: 0,
          startX: x,
          startY: y,
          x,
          y,
        },
      });

      onSelectionStart?.(event);
    };

    const onMouseMove = (event: ReactMouseEvent): void => {
      const { userSelectionRect, edges, transform, onNodesChange, onEdgesChange, nodeOrigin, getNodes } =
        store.getState();
      if (!isSelecting || !containerBounds.current || !userSelectionRect) {
        return;
      }

      store.setState({ userSelectionActive: true, nodesSelectionActive: false });

      const mousePos = getEventPosition(event, containerBounds.current);
      const startX = userSelectionRect.startX ?? 0;
      const startY = userSelectionRect.startY ?? 0;

      const nextUserSelectRect = {
        ...userSelectionRect,
        x: mousePos.x < startX ? mousePos.x : startX,
        y: mousePos.y < startY ? mousePos.y : startY,
        width: Math.abs(mousePos.x - startX),
        height: Math.abs(mousePos.y - startY),
      };

      const nodes = getNodes();
      const selectedNodes = getNodesInside<Node>(
        nodes,
        nextUserSelectRect,
        transform,
        selectionMode === SelectionMode.Partial,
        true,
        nodeOrigin
      );
      const selectedEdgeIds = getConnectedEdges(selectedNodes, edges).map((e) => e.id);
      const selectedNodeIds = selectedNodes.map((n) => n.id);

      if (prevSelectedNodesCount.current !== selectedNodeIds.length) {
        prevSelectedNodesCount.current = selectedNodeIds.length;
        const changes = getSelectionChanges(nodes, selectedNodeIds) as NodeChange[];
        if (changes.length) {
          onNodesChange?.(changes);
        }
      }

      if (prevSelectedEdgesCount.current !== selectedEdgeIds.length) {
        prevSelectedEdgesCount.current = selectedEdgeIds.length;
        const changes = getSelectionChanges(edges, selectedEdgeIds) as EdgeChange[];
        if (changes.length) {
          onEdgesChange?.(changes);
        }
      }

      store.setState({
        userSelectionRect: nextUserSelectRect,
      });
    };

    const onMouseUp = (event: ReactMouseEvent) => {
      if (event.button !== 0) {
        return;
      }
      const { userSelectionRect } = store.getState();
      // We only want to trigger click functions when in selection mode if
      // the user did not move the mouse.
      if (!userSelectionActive && userSelectionRect && event.target === container.current) {
        onClick?.(event);
      }

      store.setState({ nodesSelectionActive: prevSelectedNodesCount.current > 0 });

      resetUserSelection();
      onSelectionEnd?.(event);
    };

    const onMouseLeave = (event: ReactMouseEvent) => {
      if (userSelectionActive) {
        store.setState({ nodesSelectionActive: prevSelectedNodesCount.current > 0 });
        onSelectionEnd?.(event);
      }

      resetUserSelection();
    };

    const hasActiveSelection = elementsSelectable && (isSelecting || userSelectionActive);

    return (
      <div
        className={cc(['react-flow__pane', { dragging, selection: isSelecting }])}
        onClick={hasActiveSelection ? undefined : wrapHandler(onClick, container)}
        onContextMenu={wrapHandler(onContextMenu, container)}
        onWheel={wrapHandler(onWheel, container)}
        onMouseEnter={hasActiveSelection ? undefined : onPaneMouseEnter}
        onMouseDown={hasActiveSelection ? onMouseDown : undefined}
        onMouseMove={hasActiveSelection ? onMouseMove : onPaneMouseMove}
        onMouseUp={hasActiveSelection ? onMouseUp : undefined}
        onMouseLeave={hasActiveSelection ? onMouseLeave : onPaneMouseLeave}
        ref={container}
        style={containerStyle}
      >
        {children}
        <UserSelection />
      </div>
    );
  }
);

Pane.displayName = 'Pane';

export default Pane;

// packages/solidjs/src/container/Pane/index.tsx
/**
 * The user selection rectangle gets displayed when a user drags the mouse while pressing shift
 */

import cc from 'classcat';
import { getNodesInside, getEventPosition, SelectionMode, type NodeChange, type EdgeChange } from '@xyflow/system';

import { UserSelection } from '../../components/UserSelection';
import { containerStyle } from '../../styles/utils';
import { useStore, useStoreApi } from '../../hooks/useStore';
import { getSelectionChanges } from '../../utils';
import type { ReactFlowProps, SolidEvent, SolidFlowState } from '../../types';
import { mergeProps, JSX, ParentProps, batch, createEffect } from 'solid-js';
import { useRef, RefObject } from '../../utils/hooks';

type PaneProps = {
  isSelecting: boolean;
} & Partial<
  Pick<
    ReactFlowProps,
    | 'selectionMode'
    | 'panOnDrag'
    | 'onSelectionStart'
    | 'onSelectionEnd'
    | 'onPaneClick'
    | 'onPaneContextMenu'
    | 'onPaneScroll'
    | 'onPaneMouseEnter'
    | 'onPaneMouseMove'
    | 'onPaneMouseLeave'
  >
>;

const wrapHandler = <T, E extends Event>(
  handler: ((event: SolidEvent<T, E>) => void) | undefined,
  containerRef: RefObject<T | null>
): ((event: SolidEvent<T, E>) => void) => {
  return (event: E) => {
    if (event.target !== containerRef.current) {
      return;
    }
    handler?.(event as SolidEvent<T, E>);
  };
};

const selector = (s: SolidFlowState) => ({
  userSelectionActive: s.userSelectionActive,
  elementsSelectable: s.elementsSelectable,
  dragging: s.paneDragging,
});

export function Pane(_p: ParentProps<PaneProps>) {
  //   {
  //   isSelecting,
  //   selectionMode = SelectionMode.Full,
  //   panOnDrag,
  //   onSelectionStart,
  //   onSelectionEnd,
  //   onPaneClick,
  //   onPaneContextMenu,
  //   onPaneScroll,
  //   onPaneMouseEnter,
  //   onPaneMouseMove,
  //   onPaneMouseLeave,
  //   children,
  // }: PaneProps) {

  const p = mergeProps(
    {
      selectionMode: SelectionMode.Full,
    },
    _p
  );

  const container = useRef<HTMLDivElement | null>(null);
  const store = useStoreApi();
  const prevSelectedNodesCount = useRef<number>(0);
  const prevSelectedEdgesCount = useRef<number>(0);
  const containerBounds = useRef<DOMRect | null>(null);
  const edgeIdLookup = useRef<Map<string, Set<string>>>(new Map());

  const { userSelectionActive, elementsSelectable, dragging } = useStore(selector);

  const resetUserSelection = () => {
    store.batch((store) => {
      store.userSelectionActive.set(false);
      store.userSelectionRect.set(null);
    });

    prevSelectedNodesCount.current = 0;
    prevSelectedEdgesCount.current = 0;
  };

  const onClick = (event: MouseEvent) => {
    batch(() => {
      p.onPaneClick?.(event);
      store.resetSelectedElements();
      store.nodesSelectionActive.set(false);
    });
  };

  const onContextMenu = (event: MouseEvent) => {
    if (Array.isArray(p.panOnDrag) && p.panOnDrag?.includes(2)) {
      event.preventDefault();
      return;
    }

    p.onPaneContextMenu?.(event);
  };

  const onWheel = () => (p.onPaneScroll ? (event: WheelEvent) => p.onPaneScroll?.(event) : undefined);

  const onMouseDown = (event: MouseEvent): void => {
    console.log("mouse down")
    batch(() => {
      const { resetSelectedElements, domNode, edgeLookup } = store;
      containerBounds.current = domNode.get()?.getBoundingClientRect() ?? null;

      if (
        !elementsSelectable.get() ||
        !p.isSelecting ||
        event.button !== 0 ||
        event.target !== container.current ||
        !containerBounds.current
      ) {
        console.log("returning from mouse down")
        return;
      }

      edgeIdLookup.current = new Map();

      for (const [id, edge] of edgeLookup) {
        edgeIdLookup.current.set(edge.source, edgeIdLookup.current.get(edge.source)?.add(id) || new Set([id]));
        edgeIdLookup.current.set(edge.target, edgeIdLookup.current.get(edge.target)?.add(id) || new Set([id]));
      }

      const { x, y } = getEventPosition(event, containerBounds.current);

      resetSelectedElements();

      console.log("setting user selection rect")
      store.userSelectionRect.set({
        width: 0,
        height: 0,
        startX: x,
        startY: y,
        x,
        y,
      });

      p.onSelectionStart?.(event);
    });
  };

  const onMouseMove = (event: MouseEvent): void => {
    batch(() => {
      const { edgeLookup, transform, nodeOrigin, nodeLookup, triggerNodeChanges, triggerEdgeChanges } = store;

      const userSelectionRect = store.userSelectionRect.get();

      if (!p.isSelecting || !containerBounds.current || !userSelectionRect) {
        return;
      }

      const { x: mouseX, y: mouseY } = getEventPosition(event, containerBounds.current);
      const { startX, startY } = userSelectionRect;

      const nextUserSelectRect = {
        startX,
        startY,
        x: mouseX < startX ? mouseX : startX,
        y: mouseY < startY ? mouseY : startY,
        width: Math.abs(mouseX - startX),
        height: Math.abs(mouseY - startY),
      };

      const selectedNodes = getNodesInside(
        nodeLookup,
        nextUserSelectRect,
        transform.get(),
        p.selectionMode === SelectionMode.Partial,
        true,
        nodeOrigin.get()
      );

      const selectedEdgeIds = new Set<string>();
      const selectedNodeIds = new Set<string>();

      for (const selectedNode of selectedNodes) {
        selectedNodeIds.add(selectedNode.id);

        const edgeIds = edgeIdLookup.current.get(selectedNode.id);

        if (edgeIds) {
          for (const edgeId of edgeIds) {
            selectedEdgeIds.add(edgeId);
          }
        }
      }

      if (prevSelectedNodesCount.current !== selectedNodeIds.size) {
        prevSelectedNodesCount.current = selectedNodeIds.size;
        const changes = getSelectionChanges(nodeLookup, selectedNodeIds) as NodeChange[];
        triggerNodeChanges(changes);
      }

      if (prevSelectedEdgesCount.current !== selectedEdgeIds.size) {
        prevSelectedEdgesCount.current = selectedEdgeIds.size;
        const changes = getSelectionChanges(edgeLookup, selectedEdgeIds) as EdgeChange[];
        triggerEdgeChanges(changes);
      }

      store.batch((store) => {
        store.userSelectionRect.set(nextUserSelectRect);
        store.userSelectionActive.set(true);
        store.nodesSelectionActive.set(false);
      });
    });
  };

  const onMouseUp = (event: MouseEvent) => {
    batch(() => {
      if (event.button !== 0) {
        return;
      }
      const { userSelectionRect } = store;
      // We only want to trigger click functions when in selection mode if
      // the user did not move the mouse.
      if (!userSelectionActive.get() && userSelectionRect.get() && event.target === container.current) {
        onClick?.(event);
      }

      store.nodesSelectionActive.set(prevSelectedNodesCount.current > 0);

      resetUserSelection();
      p.onSelectionEnd?.(event);
    });
  };

  const onMouseLeave = (event: MouseEvent) => {
    if (userSelectionActive.get()) {
      store.nodesSelectionActive.set(prevSelectedNodesCount.current > 0);
      p.onSelectionEnd?.(event);
    }

    resetUserSelection();
  };

  const hasActiveSelection = () => elementsSelectable.get() && (p.isSelecting || userSelectionActive.get());

  createEffect(() => { 
    console.log("elements selectable", elementsSelectable.get());
    console.log("is selecting", p.isSelecting);
    console.log("user selection active", userSelectionActive.get());
  })

  const handleClick = () => {
    if (hasActiveSelection()) {
      // do nothing
    } else {
      wrapHandler(onClick, container);
    }
  };

  const handleMouseEnter: JSX.EventHandlerUnion<HTMLDivElement, MouseEvent> = (e) => {
    if (hasActiveSelection()) {
      // do nothing
    } else {
      p.onPaneMouseEnter?.(e);
    }
  };

  const handleMouseDown = (e: MouseEvent) => {
    if (hasActiveSelection()) {
      onMouseDown(e);
    } else {
      // do nothing
    }
  };

  const onPaneMouseMove = (e: MouseEvent) => {
    if (hasActiveSelection()) {
      onMouseMove(e);
    } else {
      p.onPaneMouseMove?.(e);
    }
  };

  const onPaneMouseLeave = (e: MouseEvent) => {
    if (hasActiveSelection()) {
      onMouseLeave(e);
    } else {
      p.onPaneMouseLeave?.(e);
    }
  };

  const handleMouseUp = (e: MouseEvent) => {
    if (hasActiveSelection()) {
      onMouseUp(e);
    } else {
      // do nothing
    }
  };

  return (
    <div
      class={cc(['react-flow__pane', { draggable: p.panOnDrag, dragging: dragging.get(), selection: p.isSelecting }])}
      onClick={handleClick}
      onContextMenu={wrapHandler(onContextMenu, container)}
      onWheel={wrapHandler(onWheel(), container)}
      onMouseEnter={handleMouseEnter}
      onMouseDown={handleMouseDown}
      onMouseMove={onPaneMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={onPaneMouseLeave}
      ref={(node) => (container.current = node)}
      style={containerStyle}
    >
      {p.children}
      <UserSelection />
    </div>
  );
}
