// examples/svelte/src/routes/examples/node-toolbar/CustomNode.svelte
<script lang="ts">
	import { NodeToolbar, type NodeProps, Handle, Position } from '@xyflow/svelte';

	type $$Props = NodeProps;

	export let data: $$Props['data'];
</script>

<NodeToolbar
	isVisible={data.toolbarVisible}
	position={data.toolbarPosition}
	align={data.toolbarAlign}
>
	<button>delete</button>
	<button>copy</button>
	<button>expand</button>
</NodeToolbar>
<div class="node">
	<div>{data.label}</div>
	<Handle type="target" position={Position.Left} />
	<Handle type="source" position={Position.Right} />
</div>

<style>
	.node {
		width: 180px;
		height: 50px;
		border: solid 1px black;
		background: white;
	}
</style>

// storybook/vue/stories/examples/NodeToolbar/CustomNode.vue
<script lang="ts" setup>
import type { ToolbarNodeData } from './types';
import { Handle, NodeToolbar, Position as PositionEnum } from '@xyflow/vue';

interface Props {
  data: ToolbarNodeData;
  label?: string;
}

defineProps<Props>();
</script>

<template>
  <NodeToolbar :is-visible="data.toolbarVisible" :position="data.toolbarPosition">
    <button>delete</button>
    <button>copy</button>
    <button>expand</button>
  </NodeToolbar>

  <div :style="{ padding: '10px 20px' }">
    {{ label }}
  </div>

  <Handle type="target" :position="PositionEnum.Left" />
  <Handle type="source" :position="PositionEnum.Right" />
</template>
