// examples/astro-xyflow/src/components/ReactFlowExample/CustomNode.tsx
import { memo, type FC, type CSSProperties } from 'react';
import { Handle, Position, type NodeProps } from '@xyflow/react';

const sourceHandleStyleA: CSSProperties = { left: 50 };
const sourceHandleStyleB: CSSProperties = {
  right: 50,
  left: 'auto',
};

const CustomNode: FC<NodeProps> = ({ data, positionAbsoluteX, positionAbsoluteY }) => {
  return (
    <>
      <Handle type="target" position={Position.Top} />
      <div>
        <div>
          Label: <strong>{data.label}</strong>
        </div>
        <div>
          Position:{' '}
          <strong>
            {positionAbsoluteX.toFixed(2)},{positionAbsoluteY.toFixed(2)}
          </strong>
        </div>
      </div>

      <Handle type="source" position={Position.Bottom} id="a" style={sourceHandleStyleA} />
      <Handle type="source" position={Position.Bottom} id="b" style={sourceHandleStyleB} />
    </>
  );
};

export default memo(CustomNode);

// examples/svelte/src/routes/examples/overview/CustomNode.svelte
<script lang="ts">
	import { Handle, Position, type BuiltInNode, type NodeProps } from '@xyflow/svelte';

	let {
		data = { label: 'Node' },
		positionAbsoluteX = 0,
		positionAbsoluteY = 0
	}: NodeProps<BuiltInNode> = $props();
</script>

<div class="custom">
	<div>{data.label}</div>
	<div>{~~positionAbsoluteX}, {~~positionAbsoluteY}</div>

	<Handle type="target" position={Position.Top} />

	<Handle type="source" position={Position.Bottom} style="left: 10%;" id="a" />
	<Handle type="source" position={Position.Bottom} id="b" />
	<Handle type="source" position={Position.Bottom} style="left: 90%;" id="c" />
</div>

<style>
	.custom {
		background: #ffcc00;
		padding: 10px;
	}
</style>
