// examples/vue/src/Edges/CustomEdge.vue
<script lang="ts" setup>
import type { EdgeProps } from '@xyflow/vue';
import { EdgeLabelRenderer, getBezierPath, useVueFlow } from '@xyflow/vue';

const props = defineProps<EdgeProps>();

const { removeEdges } = useVueFlow();

const path = computed(() => getBezierPath(props));
</script>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>

<template>
  <path :id="id" :style="style" class="vue-flow__edge-path" :d="path[0]" :marker-end="markerEnd" />

  <EdgeLabelRenderer>
    <div
      :style="{
        pointerEvents: 'all',
        position: 'absolute',
        transform: `translate(-50%, -50%) translate(${path[1]}px,${path[2]}px)`,
      }"
      class="nodrag nopan"
    >
      <button class="edgebutton" @click="removeEdges(id)">
        ×
      </button>
    </div>
  </EdgeLabelRenderer>
</template>

<style>
.edgebutton {
  border-radius: 999px;
  cursor: pointer;
}
.edgebutton:hover {
  box-shadow: 0 0 0 2px pink, 0 0 0 4px #f05f75;
}
</style>

// examples/svelte/src/routes/examples/overview/CustomEdge.svelte
<script lang="ts">
	import {
		BaseEdge,
		EdgeLabelRenderer,
		useEdges,
		type EdgeProps,
		getBezierPath
	} from '@xyflow/svelte';

	type $$Props = EdgeProps;

	$: [path, labelX, labelY] = getBezierPath({
		sourceX: $$props.sourceX,
		sourceY: $$props.sourceY,
		targetX: $$props.targetX,
		targetY: $$props.targetY,
		sourcePosition: $$props.sourcePosition,
		targetPosition: $$props.targetPosition
	});

	const edges = useEdges();

	function onClick() {
		edges.update((eds) => eds.filter((e) => e.id !== $$props.id));
	}
</script>

<BaseEdge {path} {labelX} {labelY} {...$$props} />

<EdgeLabelRenderer>
	<button
		style:transform={`translate(-50%,-50%) translate(${labelX}px,${labelY}px)`}
		class="edge-button"
		on:click={onClick}
	>
		✕
	</button>
</EdgeLabelRenderer>

<style>
	.edge-button {
		border-radius: 50%;
		position: absolute;
		border: none;
		width: 1rem;
		height: 1rem;
		display: flex;
		justify-content: center;
		align-items: center;
		font-size: 8px;
		pointer-events: all;
		cursor: pointer;
		background-color: #eee;
	}

	.edge-button:hover {
		box-shadow: 0 0 2px 1px rgba(0, 0, 0, 0.12);
	}
</style>
