// examples/svelte/src/routes/examples/edge-toolbar/+page.svelte
<script lang="ts">
	import { Background, Position, SvelteFlow, type Edge, type Node } from '@xyflow/svelte';

	import '@xyflow/svelte/dist/style.css';

	import CustomEdge from './CustomEdge.svelte';

	const edgeTypes = {
		custom: CustomEdge
	};

	const initialNodes: Node[] = [
		{
			id: '1',
			data: { label: 'Node 1', toolbarPosition: Position.Top },
			position: { x: 0, y: 0 },
			class: 'svelte-flow__node-default'
		},
		{
			id: '2',
			data: { label: 'Node 2', toolbarPosition: Position.Top },
			position: { x: 100, y: 150 },
			class: 'svelte-flow__node-default'
		},
		{
			id: '3',
			data: { label: 'Node 3', toolbarPosition: Position.Top },
			position: { x: 200, y: 0 },
			class: 'svelte-flow__node-default'
		}
	];

	const initialEdges: Edge[] = [
		{
			id: 'e1-2',
			source: '1',
			target: '2',
			type: 'custom'
		},
		{
			id: 'e3-2',
			source: '3',
			target: '2',
			type: 'custom'
		},
		{
			id: 'e1-3',
			source: '1',
			target: '3',
			type: 'custom'
		}
	];

	let nodes = $state.raw<Node[]>(initialNodes);
	let edges = $state.raw<Edge[]>(initialEdges);
</script>

<div style="height: 100vh;">
	<SvelteFlow bind:nodes bind:edges {edgeTypes} fitView>
		<Background />
	</SvelteFlow>
</div>

// examples/react/src/examples/EdgeToolbar/index.tsx
import {
  Background,
  BackgroundVariant,
  Controls,
  Edge,
  EdgeTypes,
  MiniMap,
  Node,
  NodeOrigin,
  Position,
  ReactFlow,
} from '@xyflow/react';

import { CustomEdge } from './CustomEdge';

const edgeTypes: EdgeTypes = {
  custom: CustomEdge,
};

const initialNodes: Node[] = [
  {
    id: '1',
    data: { label: 'Node 1', toolbarPosition: Position.Top },
    position: { x: 0, y: 0 },
    className: 'react-flow__node-default',
  },
  {
    id: '2',
    data: { label: 'Node 2', toolbarPosition: Position.Top },
    position: { x: 100, y: 150 },
    className: 'react-flow__node-default',
  },
  {
    id: '3',
    data: { label: 'Node 3', toolbarPosition: Position.Top },
    position: { x: 200, y: 0 },
    className: 'react-flow__node-default',
  },
];

const initialEdges: Edge[] = [
  {
    id: 'e1-2',
    source: '1',
    target: '2',
    type: 'custom',
  },
  {
    id: 'e3-2',
    source: '3',
    target: '2',
    type: 'custom',
  },
  {
    id: 'e1-3',
    source: '1',
    target: '3',
    type: 'custom',
  },
];

// const defaultEdgeOptions = { zIndex: 0 };
const nodeOrigin: NodeOrigin = [0.5, 0.5];

export default function EdgeToolbarExample() {
  return (
    <ReactFlow
      defaultNodes={initialNodes}
      defaultEdges={initialEdges}
      className="react-flow-edge-toolbar-example"
      minZoom={0.2}
      maxZoom={4}
      fitView
      // defaultEdgeOptions={defaultEdgeOptions}
      edgeTypes={edgeTypes}
      nodeOrigin={nodeOrigin}
    >
      <Background variant={BackgroundVariant.Dots} />
      <MiniMap />
      <Controls />
    </ReactFlow>
  );
}
