// packages/react/src/components/Nodes/DefaultNode.tsx
import { Position, type NodeProps } from '@xyflow/system';

import { Handle } from '../../components/Handle';

export function DefaultNode({
  data,
  isConnectable,
  targetPosition = Position.Top,
  sourcePosition = Position.Bottom,
}: NodeProps) {
  return (
    <>
      <Handle type="target" position={targetPosition} isConnectable={isConnectable} />
      {data?.label}
      <Handle type="source" position={sourcePosition} isConnectable={isConnectable} />
    </>
  );
}

// packages/svelte/src/lib/components/nodes/DefaultNode.svelte
<script lang="ts">
	import { Position } from '@xyflow/system';

	import { Handle } from '$lib/components/Handle';
	import type { NodeProps } from '$lib/types';

	let {
		data,
		targetPosition = Position.Top,
		sourcePosition = Position.Bottom
	}: NodeProps = $props();
</script>

<Handle type="target" position={targetPosition} />
{data?.label}
<Handle type="source" position={sourcePosition} />
