// src/components/Nodes/InputNode.tsx
import React from 'react';

import Handle from '../../components/Handle';
import { NodeProps, Position } from '../../types';

const InputNode = ({ data, sourcePosition = Position.Bottom }: NodeProps) => (
  <>
    {data.label}
    <Handle type="source" position={sourcePosition} />
  </>
);

InputNode.displayName = 'InputNode';

export default InputNode;

// packages/svelte/src/lib/components/nodes/InputNode.svelte
<script lang="ts">
	import { Position } from '@xyflow/system';
	import type { NodeProps } from '$lib/types';

	import { Handle } from '$lib/components/Handle';

	let { data = { label: 'Node' }, sourcePosition = Position.Bottom }: NodeProps = $props();
</script>

{data?.label}
<Handle type="source" position={sourcePosition} />
