// src/components/Nodes/OutputNode.tsx
import React, { memo } from 'react';

import Handle from '../../components/Handle';
import { NodeProps, Position } from '../../types';

const OutputNode = memo(({ data, targetPosition = Position.Top }: NodeProps) => (
  <>
    <Handle type="target" position={targetPosition} />
    {data.label}
  </>
));

OutputNode.displayName = 'OutputNode';

export default OutputNode;

// packages/svelte/src/lib/components/nodes/OutputNode.svelte
<script lang="ts">
  import { Position } from '@xyflow/system';
  import type { NodeProps } from '$lib/types';

  import { Handle } from '$lib/components/Handle';

  let { data = { label: 'Node' }, targetPosition = Position.Top }: NodeProps = $props();
</script>

{data?.label}
<Handle type="target" position={targetPosition} />
