// examples/nextjs/pages/Undirectional/CustomNode.tsx
import React, { memo, FC, CSSProperties } from 'react';

import { Handle, Position, NodeProps } from '@react-flow/bundle';

const nodeStyles: CSSProperties = {
  padding: '10px 15px',
  border: '1px solid #ddd',
};

const CustomNode: FC<NodeProps> = ({ id }) => {
  return (
    <div style={nodeStyles}>
      <div>node {id}</div>
      <Handle type="source" id="left" position={Position.Left} />
      <Handle type="source" id="right" position={Position.Right} />
      <Handle type="source" id="top" position={Position.Top} />
      <Handle type="source" id="bottom" position={Position.Bottom} />
    </div>
  );
};

export default memo(CustomNode);

// storybook/vue/stories/examples/Unidirectional/CustomNode.vue
<script lang="ts" setup>
import type { CSSProperties } from 'vue';
import { Handle, Position } from '@xyflow/vue';

interface Props {
  id: string;
}

const props = defineProps<Props>();
const nodeStyles: CSSProperties = { padding: '10px 15px', border: '1px solid #ddd' };
</script>

<template>
  <div :key="props.id" :style="nodeStyles">
    <div>node {{ props.id }}</div>
    <Handle id="left" type="source" :position="Position.Left" />
    <Handle id="right" type="source" :position="Position.Right" />
    <Handle id="top" type="source" :position="Position.Top" />
    <Handle id="bottom" type="source" :position="Position.Bottom" />
  </div>
</template>
