// example/src_oldapi/UseUpdateNodeInternals/CustomNode.tsx
import React, { memo, FC, useMemo, CSSProperties } from 'react';

import { Handle, Position, NodeProps } from 'react-flow-renderer';

const nodeStyles: CSSProperties = { padding: 10, border: '1px solid #ddd' };

const CustomNode: FC<NodeProps> = ({ data }) => {
  const handles = useMemo(
    () =>
      Array.from({ length: data.handleCount }, (x, i) => {
        const handleId = `handle-${i}`;
        return (
          <Handle
            key={handleId}
            type="source"
            position={Position.Right}
            id={handleId}
            style={{ top: 10 * i + data.handlePosition * 10 }}
          />
        );
      }),
    [data.handleCount, data.handlePosition]
  );

  return (
    <div style={nodeStyles}>
      <Handle type="target" position={Position.Left} />
      <div>output handle count: {data.handleCount}</div>
      {handles}
    </div>
  );
};

export default memo(CustomNode);

// storybook/vue/stories/examples/Unidirectional/CustomNode.vue
<script lang="ts" setup>
import type { CSSProperties } from 'vue';
import { Handle, Position } from '@xyflow/vue';

interface Props {
  id: string;
}

const props = defineProps<Props>();
const nodeStyles: CSSProperties = { padding: '10px 15px', border: '1px solid #ddd' };
</script>

<template>
  <div :key="props.id" :style="nodeStyles">
    <div>node {{ props.id }}</div>
    <Handle id="left" type="source" :position="Position.Left" />
    <Handle id="right" type="source" :position="Position.Right" />
    <Handle id="top" type="source" :position="Position.Top" />
    <Handle id="bottom" type="source" :position="Position.Bottom" />
  </div>
</template>
