// examples/svelte/src/routes/examples/usenodesdata/TextNode.svelte
<script lang="ts">
	import { Handle, Position, type NodeProps, useUpdateNodeData } from '@xyflow/svelte';

	type $$Props = NodeProps;

	export let id: $$Props['id'];
	export let data: $$Props['data'];

	const updateNodeData = useUpdateNodeData();
</script>

<div class="custom">
	<div>node {id}</div>
	<div>
		<input
			value={data.text}
			on:input={(evt) => updateNodeData(id, { text: evt.currentTarget.value })}
		/>
	</div>
	<Handle type="source" position={Position.Right} />
</div>

<style>
	.custom {
		background-color: #eee;
		padding: 10px;
		border-radius: 10px;
	}
</style>

// examples/react/src/examples/UseNodesData/TextNode.tsx
import { memo, ChangeEventHandler } from 'react';
import { Position, NodeProps, useUpdateNodeData, Handle } from '@xyflow/react';

function TextNode({ id, data }: NodeProps) {
  const updateNodeData = useUpdateNodeData();

  const onChange: ChangeEventHandler<HTMLInputElement> = (evt) => updateNodeData(id, { text: evt.target.value });

  return (
    <div style={{ background: '#eee', color: '#222', padding: 10, fontSize: 12, borderRadius: 10 }}>
      <div>node {id}</div>
      <div>
        <input onChange={onChange} value={data.text} />
      </div>
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default memo(TextNode);
