// examples/svelte/src/routes/examples/usenodesdata/UppercaseNode.svelte
<script lang="ts">
	import {
		Handle,
		Position,
		type NodeProps,
		useHandleConnections,
		useNodesData,
		useSvelteFlow
	} from '@xyflow/svelte';

	type $$Props = NodeProps;

	export let id: $$Props['id'];

	const { updateNodeData } = useSvelteFlow();
	const connections = useHandleConnections({
		nodeId: id,
		type: 'target'
	});

	$: nodeData = useNodesData($connections[0]?.source);

	$: {
		updateNodeData(id, { text: $nodeData?.text?.toUpperCase() || '' });
	}
</script>

<div class="custom">
	<Handle type="target" position={Position.Left} isConnectable={$connections.length === 0} />
	<div>uppercase transform</div>
	<Handle type="source" position={Position.Right} />
</div>

<style>
	.custom {
		background-color: #eee;
		padding: 10px;
		border-radius: 10px;
	}
</style>

// examples/react/src/examples/UseNodesData/UppercaseNode.tsx
import { memo, useEffect } from 'react';
import { Position, NodeProps, useUpdateNodeData, Handle, useHandleConnections, useNodesData } from '@xyflow/react';

function UppercaseNode({ id }: NodeProps) {
  const connections = useHandleConnections({
    type: 'target',
  });
  const nodeData = useNodesData(connections[0]?.source);
  const updateNodeData = useUpdateNodeData();

  useEffect(() => {
    updateNodeData(id, { text: nodeData?.text.toUpperCase() });
  }, [nodeData]);

  return (
    <div style={{ background: '#eee', color: '#222', padding: 10, fontSize: 12, borderRadius: 10 }}>
      <Handle type="target" position={Position.Left} isConnectable={connections.length === 0} />
      <div>uppercase transform</div>
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default memo(UppercaseNode);
