// packages/svelte/src/lib/components/nodes/InputNode.svelte
<script lang="ts">
	import { Position } from '@xyflow/system';
	import type { NodeProps } from '$lib/types';

	import { Handle } from '$lib/components/Handle';

	let { data = { label: 'Node' }, sourcePosition = Position.Bottom }: NodeProps = $props();
</script>

{data?.label}
<Handle type="source" position={sourcePosition} />

// packages/react/src/components/Nodes/InputNode.tsx
import { Position, type NodeProps } from '@xyflow/system';

import { Handle } from '../../components/Handle';

export function InputNode({ data, isConnectable, sourcePosition = Position.Bottom }: NodeProps) {
  return (
    <>
      {data?.label}
      <Handle type="source" position={sourcePosition} isConnectable={isConnectable} />
    </>
  );
}
