// packages/react/src/components/Edges/StraightEdgeInternal.tsx
import { memo } from 'react';
import { getStraightPath } from '@xyflow/system';

import BaseEdge from './BaseEdge';
import type { EdgeProps } from '../../types';

const StraightEdge = memo(
  ({
    sourceX,
    sourceY,
    targetX,
    targetY,
    label,
    labelStyle,
    labelShowBg,
    labelBgStyle,
    labelBgPadding,
    labelBgBorderRadius,
    style,
    markerEnd,
    markerStart,
    interactionWidth,
  }: EdgeProps) => {
    const [path, labelX, labelY] = getStraightPath({ sourceX, sourceY, targetX, targetY });

    return (
      <BaseEdge
        path={path}
        labelX={labelX}
        labelY={labelY}
        label={label}
        labelStyle={labelStyle}
        labelShowBg={labelShowBg}
        labelBgStyle={labelBgStyle}
        labelBgPadding={labelBgPadding}
        labelBgBorderRadius={labelBgBorderRadius}
        style={style}
        markerEnd={markerEnd}
        markerStart={markerStart}
        interactionWidth={interactionWidth}
      />
    );
  }
);

StraightEdge.displayName = 'StraightEdge';

export default StraightEdge;

// packages/svelte/src/lib/components/edges/StraightEdgeInternal.svelte
<script lang="ts">
	import { getStraightPath } from '@xyflow/system';

	import BaseEdge from './BaseEdge.svelte';
	import type { EdgeProps } from '$lib/types';

	let {
		sourceX,
		sourceY,
		targetX,
		targetY,
		label,
		labelStyle,
		markerStart,
		markerEnd,
		interactionWidth,
		style
	}: EdgeProps = $props();

	let [path, labelX, labelY] = $derived(
		getStraightPath({
			sourceX,
			sourceY,
			targetX,
			targetY
		})
	);
</script>

<BaseEdge
	{path}
	{labelX}
	{labelY}
	{label}
	{labelStyle}
	{markerStart}
	{markerEnd}
	{interactionWidth}
	{style}
/>
