// packages/core/src/components/Edges/EdgeText.tsx
import { memo, useRef, useState, useEffect, type FC, type PropsWithChildren } from 'react';
import cc from 'classcat';
import type { Rect } from '@reactflow/system';

import type { EdgeTextProps } from '../../types';

const EdgeText: FC<PropsWithChildren<EdgeTextProps>> = ({
  x,
  y,
  label,
  labelStyle = {},
  labelShowBg = true,
  labelBgStyle = {},
  labelBgPadding = [2, 4],
  labelBgBorderRadius = 2,
  children,
  className,
  ...rest
}) => {
  const edgeRef = useRef<SVGTextElement>(null);
  const [edgeTextBbox, setEdgeTextBbox] = useState<Rect>({ x: 0, y: 0, width: 0, height: 0 });
  const edgeTextClasses = cc(['react-flow__edge-textwrapper', className]);

  useEffect(() => {
    if (edgeRef.current) {
      const textBbox = edgeRef.current.getBBox();

      setEdgeTextBbox({
        x: textBbox.x,
        y: textBbox.y,
        width: textBbox.width,
        height: textBbox.height,
      });
    }
  }, [label]);

  if (typeof label === 'undefined' || !label) {
    return null;
  }

  return (
    <g
      transform={`translate(${x - edgeTextBbox.width / 2} ${y - edgeTextBbox.height / 2})`}
      className={edgeTextClasses}
      visibility={edgeTextBbox.width ? 'visible' : 'hidden'}
      {...rest}
    >
      {labelShowBg && (
        <rect
          width={edgeTextBbox.width + 2 * labelBgPadding[0]}
          x={-labelBgPadding[0]}
          y={-labelBgPadding[1]}
          height={edgeTextBbox.height + 2 * labelBgPadding[1]}
          className="react-flow__edge-textbg"
          style={labelBgStyle}
          rx={labelBgBorderRadius}
          ry={labelBgBorderRadius}
        />
      )}
      <text className="react-flow__edge-text" y={edgeTextBbox.height / 2} dy="0.3em" ref={edgeRef} style={labelStyle}>
        {label}
      </text>
      {children}
    </g>
  );
};
export default memo(EdgeText);

// packages/solidjs/src/components/Edges/EdgeText.tsx
// import { memo, useState, useCallback } from 'react';
import cc from 'classcat';
import type { Rect } from '@xyflow/system';

import type { EdgeLabelOptions } from '../../types';
import { Show, mergeProps, splitProps, JSX, createSignal } from 'solid-js';

interface Props extends EdgeLabelOptions, JSX.GSVGAttributes<SVGGElement> {
  x: number;
  y: number;
}

function EdgeTextComponent(_p: Props) {
  const p = mergeProps(
    {
      labelStyle: {},
      labelShowBg: true,
      labelBgStyle: {},
      labelBgPadding: [2, 4],
      labelBgBorderRadius: 2,
    },
    _p
  );

  const [edgeTextBbox, setEdgeTextBbox] = createSignal<Rect>({ x: 1, y: 0, width: 0, height: 0 });

  const edgeTextClasses = () => cc(['react-flow__edge-textwrapper', p.class]);

  const onEdgeTextRefChange = (edgeRef: SVGTextElement) => {
    if (edgeRef === null) return;

    const textBbox = edgeRef.getBBox();

    setEdgeTextBbox({
      x: textBbox.x,
      y: textBbox.y,
      width: textBbox.width,
      height: textBbox.height,
    });
  };


  const [_, rest] = splitProps(p, [
    'label',
    'labelStyle',
    'labelShowBg',
    'labelBgStyle',
    'labelBgPadding',
    'labelBgBorderRadius',
    'children',
    'class',
  ]);

  return (
    <Show when={p.label}>
      {(label) => {
        return (
          <g
            transform={`translate(${p.x - edgeTextBbox().width / 2} ${p.y - edgeTextBbox().height / 2})`}
            class={edgeTextClasses()}
            visibility={edgeTextBbox().width ? 'visible' : 'hidden'}
            {...rest}
          >
            <Show when={p.labelShowBg}>
              <rect
                width={edgeTextBbox().width + 2 * p.labelBgPadding[0]}
                x={-p.labelBgPadding[0]}
                y={-p.labelBgPadding[1]}
                height={edgeTextBbox().height + 2 * p.labelBgPadding[1]}
                class="react-flow__edge-textbg"
                style={p.labelBgStyle}
                rx={p.labelBgBorderRadius}
                ry={p.labelBgBorderRadius}
              />
            </Show>

            <text
              class="react-flow__edge-text"
              y={edgeTextBbox().height / 2}
              dy="0.3em"
              ref={onEdgeTextRefChange}
              style={p.labelStyle}
            >
              {label()}
            </text>
            {p.children}
          </g>
        );
      }}
    </Show>
  );
}

EdgeTextComponent.displayName = 'EdgeText';

export const EdgeText = EdgeTextComponent;
