// examples/vue/Header.vue
<script lang="ts" setup>
import { useRoute, useRouter } from 'vue-router';
import { routes } from './router';

const router = useRouter();

const route = useRoute();

function onChange(event: Event) {
  router.push((event.target as HTMLSelectElement).value);
}

const computedRoutes = computed(() =>
  routes
    .filter(r => r.path !== '/')
    .map(r => ({
      path: r.path,
      label: r.path.substring(1),
    })),
);
</script>

<template>
  <header>
    <a class="logo" href="https://github.com/bcakmakoglu/vue-flow"> Vue Flow Dev </a>
    <select :value="route.path" @change="onChange">
      <template v-for="r of computedRoutes" :key="r.path">
        <option :value="r.path">
          {{ r.label }}
        </option>
      </template>
    </select>
  </header>
</template>

// examples/react/src/App/header.tsx
import { useEffect, useState } from 'react';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';

import routes from './routes';

export default function Header() {
  const location = useLocation();
  const navigate = useNavigate();
  const [currentPath, setCurrentPath] = useState(location.pathname);

  useEffect(() => {
    const name = routes.find((route) => route.path === currentPath)?.name;
    document.title = `React Flow Examples${name ? ' - ' + name : ''}`;
    navigate(currentPath);
  }, [currentPath]);

  return (
    <>
      {/* <header>
        <a className="logo" href="https://github.com/xyflow/xyflow">
          React Flow Dev
        </a>
        <select value={currentPath} onChange={(event) => setCurrentPath(event.target.value)}>
          {routes.map((route) => (
            <option value={route.path} key={route.path}>
              {route.name}
            </option>
          ))}
        </select>
      </header> */}
      <Outlet />
    </>
  );
}
