// packages/react/src/components/Attribution/index.tsx
import { useEffect } from 'react';
import { type PanelPosition, handleAttributionWarning } from '@xyflow/system';

import { Panel } from '../Panel';
import { type ProOptions } from '../../types/general';

type AttributionProps = {
  proOptions?: ProOptions;
  position?: PanelPosition;
};

const link = `https://reactflow.dev${
  process.env.NODE_ENV === 'production' ? '?utm_source=attribution' : '/attribution'
}`;

/**
 * React Flow is independent and entirely funded by its users.
 * If you hide the attribution, please support our work by subscribing to React Flow Pro: https://reactflow.dev/remove-attribution
 */
export function Attribution({ proOptions, position = 'bottom-right' }: AttributionProps) {
  useEffect(() => {
    if (process.env.NODE_ENV !== 'development') {
      return;
    }

    handleAttributionWarning('react');
  }, []);

  if (proOptions?.hideAttribution) {
    return null;
  }

  return (
    <Panel
      position={position}
      className="react-flow__attribution"
      data-message={`Please only hide this attribution when you are subscribed to React Flow Pro: ${link}`}
    >
      <a href={link} target="_blank" rel="noopener noreferrer" aria-label="React Flow attribution">
        React Flow
      </a>
    </Panel>
  );
}

// packages/svelte/src/lib/components/Attribution/Attribution.svelte
<script lang="ts">
  import { handleAttributionWarning } from '@xyflow/system';

  import { Panel } from '$lib/container/Panel/index.js';
  import type { AttributionProps } from './types.js';

  let { proOptions, position = 'bottom-right' }: AttributionProps = $props();

  const link = `https://svelteflow.dev${
    process.env.NODE_ENV === 'production' ? '?utm_source=attribution' : '/attribution'
  }`;

  $effect(() => {
    if (process.env.NODE_ENV !== 'development') {
      return;
    }

    handleAttributionWarning('svelte');
  });
</script>

{#if !proOptions?.hideAttribution}
  <!--
@component
Svelte Flow is independent and entirely funded by its users.
If you hide the attribution, please support our work by subscribing to Svelte Flow Pro: https://svelteflow.dev/remove-attribution
-->
  <Panel
    {position}
    class="svelte-flow__attribution"
    data-message={`Please only hide this attribution when you are subscribed to Svelte Flow Pro: ${link}`}
  >
    <a href={link} target="_blank" rel="noopener noreferrer" aria-label="Svelte Flow attribution">
      Svelte Flow
    </a>
  </Panel>
{/if}
