// packages/solidjs/src/components/NodeWrapper/index.tsx
// import { type MouseEvent, type KeyboardEvent } from 'react';
import cc from 'classcat';
import {
  elementSelectionKeys,
  errorMessages,
  getNodeDimensions,
  isInputDOMNode,
  nodeHasDimensions,
} from '@xyflow/system';

import { useStore, useStoreApi } from '../../hooks/useStore';
import { Provider } from '../../contexts/NodeIdContext';
import { ARIA_NODE_DESC_KEY } from '../A11yDescriptions';
import { useDrag } from '../../hooks/useDrag';
import { useMoveSelectedNodes } from '../../hooks/useMoveSelectedNodes';
import { handleNodeClick } from '../Nodes/utils';
import { arrowKeyDiffs, builtinNodeTypes, getNodeInlineStyleDimensions } from './utils';
import { useNodeObserver } from './useNodeObserver';
import type { InternalNode, Node, NodeWrapperProps } from '../../types';
import { Show, JSX, onMount, createRenderEffect, createEffect, createSignal, on } from 'solid-js';
import { Dynamic } from 'solid-js/web';

export function NodeWrapper<NodeType extends Node>(p: NodeWrapperProps<NodeType>): JSX.Element {
  //   id,
  //   onClick,
  //   onMouseEnter,
  //   onMouseMove,
  //   onMouseLeave,
  //   onContextMenu,
  //   onDoubleClick,
  //   nodesDraggable,
  //   elementsSelectable,
  //   nodesConnectable,
  //   nodesFocusable,
  //   resizeObserver,
  //   noDragClassName,
  //   noPanClassName,
  //   disableKeyboardA11y,
  //   rfId,
  //   nodeTypes,
  //   nodeExtent,
  //   nodeOrigin,
  //   onError,
  // }: NodeWrapperProps<NodeType>) {
  const store = useStoreApi();
  const nodeData = useStore((s) => {
    const node = () => s.nodeLookup.get(p.id)! as InternalNode<NodeType>;
    const isParent = () => s.parentLookup.has(p.id);

    return {
      node,
      internals: () => node().internals,
      isParent,
    };
  });

  const initialNodeType = () => nodeData.node()?.type || 'default';
  const initialNodeComponent = () => p.nodeTypes?.[initialNodeType()] || builtinNodeTypes[initialNodeType()];

  const NodeComponent = () => {
    const comp = initialNodeComponent();
    if (comp === undefined) {
      p.onError?.('003', errorMessages['error003'](initialNodeType()));
      return builtinNodeTypes.default;
    }
    return comp;
  };

  const nodeType = () => {
    let nt = initialNodeType();
    if (initialNodeComponent() === undefined) {
      nt = 'default';
    }
    return nt;
  };

  // if (NodeComponent === undefined) {
  //   p.onError?.('003', errorMessages['error003'](nodeType));
  //   nodeType = 'default';
  //   NodeComponent = builtinNodeTypes.default;
  // }

  const isDraggable = () =>
    !!(nodeData.node()?.draggable || (p.nodesDraggable && typeof nodeData.node()?.draggable === 'undefined'));
  const isSelectable = () =>
    !!(nodeData.node()?.selectable || (p.elementsSelectable && typeof nodeData.node()?.selectable === 'undefined'));
  const isConnectable = () =>
    !!(nodeData.node()?.connectable || (p.nodesConnectable && typeof nodeData.node()?.connectable === 'undefined'));
  const isFocusable = () =>
    !!(nodeData.node()?.focusable || (p.nodesFocusable && typeof nodeData.node()?.focusable === 'undefined'));

  const hasDimensions = () => nodeHasDimensions(nodeData.node());
  const nodeRef = useNodeObserver({
    node: nodeData.node,
    nodeType,
    hasDimensions,
    resizeObserver: () => p.resizeObserver,
  });
  const dragging = useDrag({
    nodeRef: () => nodeRef.current ?? undefined,
    disabled: () => nodeData.node()?.hidden || !isDraggable(),
    noDragClassName: () => p.noDragClassName,
    handleSelector: () => nodeData.node()?.dragHandle,
    nodeId: () => p.id,
    isSelectable,
    nodeClickDistance: () => p.nodeClickDistance,
  });
  const moveSelectedNodes = useMoveSelectedNodes();

  // if (node.hidden) {
  //   return null;
  // }

  const nodeDimensions = () => getNodeDimensions(nodeData.node());
  const inlineDimensions = () => getNodeInlineStyleDimensions(nodeData.node());

  const hasPointerEvents = () =>
    isSelectable() || isDraggable() || p.onClick || p.onMouseEnter || p.onMouseMove || p.onMouseLeave;

  const onMouseEnterHandler = (e: MouseEvent) => {
    if (p.onMouseEnter) {
      p.onMouseEnter(e, { ...nodeData.internals()?.userNode });
    }
  };
  // onMouseEnter ? (event: MouseEvent) => onMouseEnter(event, { ...node }) : undefined;
  const onMouseMoveHandler = (e: MouseEvent) => {
    if (p.onMouseMove) {
      p.onMouseMove(e, { ...nodeData.internals()?.userNode });
    }
  };
  // onMouseMove ? (event: MouseEvent) => onMouseMove(event, { ...node }) : undefined;
  const onMouseLeaveHandler = (e: MouseEvent) => {
    if (p.onMouseLeave) {
      p.onMouseLeave(e, { ...nodeData.internals()?.userNode });
    }
  };
  // onMouseLeave ? (event: MouseEvent) => onMouseLeave(event, { ...node }) : undefined;
  const onContextMenuHandler = (e: MouseEvent) => {
    if (p.onContextMenu) {
      p.onContextMenu(e, { ...nodeData.internals()?.userNode });
    }
  };

  // onContextMenu ? (event: MouseEvent) => onContextMenu(event, { ...node }) : undefined;
  const onDoubleClickHandler = (e: MouseEvent) => {
    if (p.onDoubleClick) {
      p.onDoubleClick(e, { ...nodeData.internals()?.userNode });
    }
  };
  // onDoubleClick ? (event: MouseEvent) => onDoubleClick(event, { ...node }) : undefined;

  const onSelectNodeHandler = (event: MouseEvent) => {
    if (isSelectable() && (!store.selectNodesOnDrag.get() || !isDraggable() || store.nodeDragThreshold.get() > 0)) {
      /*
       * this handler gets called by XYDrag on drag start when selectNodesOnDrag=true
       * here we only need to call it when selectNodesOnDrag=false
       */
      handleNodeClick({
        id: p.id,
        store,
        nodeRef: nodeRef.current ?? undefined,
      });
    }

    if (p.onClick) {
      p.onClick(event, { ...nodeData.internals()?.userNode });
    }
  };

  const onKeyDown = (event: KeyboardEvent) => {
    if (isInputDOMNode(event) || p.disableKeyboardA11y) {
      return;
    }

    if (elementSelectionKeys.includes(event.key) && isSelectable()) {
      const unselect = event.key === 'Escape';

      handleNodeClick({
        id: p.id,
        store,
        unselect,
        nodeRef: nodeRef.current ?? undefined,
      });
    } else if (
      isDraggable() &&
      nodeData.node()?.selected &&
      Object.prototype.hasOwnProperty.call(arrowKeyDiffs, event.key)
    ) {
      // prevent default scrolling behavior on arrow key press when node is moved
      event.preventDefault();

      const ariaLiveMessage = `Moved selected node ${event.key
        .replace('Arrow', '')
        .toLowerCase()}. New position, x: ${~~nodeData.internals()?.positionAbsolute.x}, y: ${~~nodeData.internals()
        ?.positionAbsolute.y}`;

      store.ariaLiveMessage.set(ariaLiveMessage);

      moveSelectedNodes({
        direction: arrowKeyDiffs[event.key],
        factor: event.shiftKey ? 4 : 1,
      });
    }
  };

  return (
    <div
      class={cc([
        'react-flow__node',
        `react-flow__node-${nodeType()}`,
        {
          // this is overwritable by passing `nopan` as a class name
          [p.noPanClassName]: isDraggable(),
        },
        nodeData.node()?.className,
        {
          selected: nodeData.node()?.selected,
          selectable: isSelectable(),
          parent: nodeData.isParent(),
          draggable: isDraggable(),
          dragging: dragging(),
        },
      ])}
      ref={(node) => (nodeRef.current = node)}
      style={{
        'z-index': nodeData.internals()?.z,
        transform: `translate(${nodeData.internals()?.positionAbsolute.x}px,${
          nodeData.internals()?.positionAbsolute.y
        }px)`,
        'pointer-events': hasPointerEvents() ? 'all' : 'none',
        visibility: hasDimensions() ? 'visible' : 'hidden',
        display: nodeData.node()?.hidden ? 'none' : 'block',
        ...nodeData.node()?.style,
        ...inlineDimensions(),
      }}
      data-id={p.id}
      data-testid={`rf__node-${p.id}`}
      onMouseEnter={onMouseEnterHandler}
      onMouseMove={onMouseMoveHandler}
      onMouseLeave={onMouseLeaveHandler}
      onContextMenu={onContextMenuHandler}
      onClick={onSelectNodeHandler}
      onDblClick={onDoubleClickHandler}
      onKeyDown={isFocusable() ? onKeyDown : undefined}
      tabIndex={isFocusable() ? 0 : undefined}
      role={isFocusable() ? 'button' : undefined}
      aria-describedby={p.disableKeyboardA11y ? undefined : `${ARIA_NODE_DESC_KEY}-${p.rfId}`}
      aria-label={nodeData.node()?.ariaLabel}
    >
      <Provider value={() => p.id}>
        <Dynamic
          component={NodeComponent()}
          id={p.id}
          data={nodeData.node()?.data}
          type={nodeType()}
          positionAbsoluteX={nodeData.internals()?.positionAbsolute.x}
          positionAbsoluteY={nodeData.internals()?.positionAbsolute.y}
          selected={nodeData.node()?.selected ?? false}
          selectable={isSelectable()}
          draggable={isDraggable()}
          deletable={nodeData.node()?.deletable ?? true}
          isConnectable={isConnectable()}
          sourcePosition={nodeData.node()?.sourcePosition}
          targetPosition={nodeData.node()?.targetPosition}
          dragging={dragging()}
          dragHandle={nodeData.node()?.dragHandle}
          zIndex={nodeData.internals()?.z}
          parentId={nodeData.node()?.parentId}
          {...nodeDimensions()}
        />
      </Provider>
    </div>
  );
}

// packages/react/src/components/NodeWrapper/index.tsx
import { type MouseEvent, type KeyboardEvent, memo, useCallback } from 'react';
import cc from 'classcat';
import {
  elementSelectionKeys,
  errorMessages,
  getNodeDimensions,
  isInputDOMNode,
  nodeHasDimensions,
  getNodesInside,
} from '@xyflow/system';

import { useReactFlowStore, useReactFlowStoreApi, useShallow } from '../../hooks/useReactFlowStore';
import { Provider } from '../../contexts/NodeIdContext';
import { ARIA_NODE_DESC_KEY } from '../A11yDescriptions';
import { useDrag } from '../../hooks/useDrag';
import { useMoveSelectedNodes } from '../../hooks/useMoveSelectedNodes';
import { handleNodeClick } from '../Nodes/utils';
import { arrowKeyDiffs, builtinNodeTypes, getNodeInlineStyleDimensions } from './utils';
import { useNodeObserver } from './useNodeObserver';
import type { InternalNode, Node, NodeWrapperProps, ReactFlowState } from '../../types';

function NodeWrapper<NodeType extends Node>({
  id,
  onClick,
  onMouseEnter,
  onMouseMove,
  onMouseLeave,
  onContextMenu,
  onDoubleClick,
  nodesDraggable,
  elementsSelectable,
  nodesConnectable,
  nodesFocusable,
  resizeObserver,
  noDragClassName,
  noPanClassName,
  disableKeyboardA11y,
  rfId,
  nodeTypes,
  nodeClickDistance,
  onError,
}: NodeWrapperProps<NodeType>) {
  const selector = useCallback(
    (s: ReactFlowState) => {
      const node = s.nodeLookup.get(id)! as InternalNode<NodeType>;
      const isParent = s.parentLookup.has(id);

      return {
        node,
        internals: node.internals,
        isParent,
      };
    },
    [id]
  );
  const { node, internals, isParent } = useReactFlowStore(useShallow(selector));

  let nodeType = node.type || 'default';
  let NodeComponent = nodeTypes?.[nodeType] || builtinNodeTypes[nodeType];

  if (NodeComponent === undefined) {
    onError?.('003', errorMessages['error003'](nodeType));
    nodeType = 'default';
    NodeComponent = nodeTypes?.['default'] || builtinNodeTypes.default;
  }

  const isDraggable = !!(node.draggable || (nodesDraggable && typeof node.draggable === 'undefined'));
  const isSelectable = !!(node.selectable || (elementsSelectable && typeof node.selectable === 'undefined'));
  const isConnectable = !!(node.connectable || (nodesConnectable && typeof node.connectable === 'undefined'));
  const isFocusable = !!(node.focusable || (nodesFocusable && typeof node.focusable === 'undefined'));

  const store = useReactFlowStoreApi();
  const hasDimensions = nodeHasDimensions(node);
  const nodeRef = useNodeObserver({ node, nodeType, hasDimensions, resizeObserver });
  const dragging = useDrag({
    nodeRef,
    disabled: node.hidden || !isDraggable,
    noDragClassName,
    handleSelector: node.dragHandle,
    nodeId: id,
    isSelectable,
    nodeClickDistance,
  });
  const moveSelectedNodes = useMoveSelectedNodes();

  if (node.hidden) {
    return null;
  }

  const nodeDimensions = getNodeDimensions(node);
  const inlineDimensions = getNodeInlineStyleDimensions(node);

  const hasPointerEvents = isSelectable || isDraggable || onClick || onMouseEnter || onMouseMove || onMouseLeave;

  const onMouseEnterHandler = onMouseEnter
    ? (event: MouseEvent) => onMouseEnter(event, { ...internals.userNode })
    : undefined;
  const onMouseMoveHandler = onMouseMove
    ? (event: MouseEvent) => onMouseMove(event, { ...internals.userNode })
    : undefined;
  const onMouseLeaveHandler = onMouseLeave
    ? (event: MouseEvent) => onMouseLeave(event, { ...internals.userNode })
    : undefined;
  const onContextMenuHandler = onContextMenu
    ? (event: MouseEvent) => onContextMenu(event, { ...internals.userNode })
    : undefined;
  const onDoubleClickHandler = onDoubleClick
    ? (event: MouseEvent) => onDoubleClick(event, { ...internals.userNode })
    : undefined;

  const onSelectNodeHandler = (event: MouseEvent) => {
    const { selectNodesOnDrag, nodeDragThreshold } = store.getState();

    if (isSelectable && (!selectNodesOnDrag || !isDraggable || nodeDragThreshold > 0)) {
      /*
       * this handler gets called by XYDrag on drag start when selectNodesOnDrag=true
       * here we only need to call it when selectNodesOnDrag=false
       */
      handleNodeClick({
        id,
        store,
        nodeRef,
      });
    }

    if (onClick) {
      onClick(event, { ...internals.userNode });
    }
  };

  const onKeyDown = (event: KeyboardEvent) => {
    if (isInputDOMNode(event.nativeEvent) || disableKeyboardA11y) {
      return;
    }

    if (elementSelectionKeys.includes(event.key) && isSelectable) {
      const unselect = event.key === 'Escape';

      handleNodeClick({
        id,
        store,
        unselect,
        nodeRef,
      });
    } else if (isDraggable && node.selected && Object.prototype.hasOwnProperty.call(arrowKeyDiffs, event.key)) {
      // prevent default scrolling behavior on arrow key press when node is moved
      event.preventDefault();

      const { ariaLabelConfig } = store.getState();

      store.setState({
        ariaLiveMessage: ariaLabelConfig['node.a11yDescription.ariaLiveMessage']({
          direction: event.key.replace('Arrow', '').toLowerCase(),
          x: ~~internals.positionAbsolute.x,
          y: ~~internals.positionAbsolute.y,
        }),
      });

      moveSelectedNodes({
        direction: arrowKeyDiffs[event.key],
        factor: event.shiftKey ? 4 : 1,
      });
    }
  };

  const onFocus = () => {
    if (disableKeyboardA11y || !nodeRef.current?.matches(':focus-visible')) {
      return;
    }

    const { transform, width, height, autoPanOnNodeFocus, setCenter } = store.getState();

    if (!autoPanOnNodeFocus) {
      return;
    }

    const withinViewport =
      getNodesInside(new Map([[id, node]]), { x: 0, y: 0, width, height }, transform, true).length > 0;

    if (!withinViewport) {
      void setCenter(node.position.x + nodeDimensions.width / 2, node.position.y + nodeDimensions.height / 2, {
        zoom: transform[2],
      });
    }
  };

  return (
    <div
      className={cc([
        'react-flow__node',
        `react-flow__node-${nodeType}`,
        {
          // this is overwritable by passing `nopan` as a class name
          [noPanClassName]: isDraggable,
        },
        node.className,
        {
          selected: node.selected,
          selectable: isSelectable,
          parent: isParent,
          draggable: isDraggable,
          dragging,
        },
      ])}
      ref={nodeRef}
      style={{
        zIndex: internals.z,
        transform: `translate(${internals.positionAbsolute.x}px,${internals.positionAbsolute.y}px)`,
        pointerEvents: hasPointerEvents ? 'all' : 'none',
        visibility: hasDimensions ? 'visible' : 'hidden',
        ...node.style,
        ...inlineDimensions,
      }}
      data-id={id}
      data-testid={`rf__node-${id}`}
      onMouseEnter={onMouseEnterHandler}
      onMouseMove={onMouseMoveHandler}
      onMouseLeave={onMouseLeaveHandler}
      onContextMenu={onContextMenuHandler}
      onClick={onSelectNodeHandler}
      onDoubleClick={onDoubleClickHandler}
      onKeyDown={isFocusable ? onKeyDown : undefined}
      tabIndex={isFocusable ? 0 : undefined}
      onFocus={isFocusable ? onFocus : undefined}
      role={node.ariaRole ?? (isFocusable ? 'group' : undefined)}
      aria-roledescription="node"
      aria-describedby={disableKeyboardA11y ? undefined : `${ARIA_NODE_DESC_KEY}-${rfId}`}
      aria-label={node.ariaLabel}
      {...node.domAttributes}
    >
      <Provider value={id}>
        <NodeComponent
          id={id}
          data={node.data}
          type={nodeType}
          positionAbsoluteX={internals.positionAbsolute.x}
          positionAbsoluteY={internals.positionAbsolute.y}
          selected={node.selected ?? false}
          selectable={isSelectable}
          draggable={isDraggable}
          deletable={node.deletable ?? true}
          isConnectable={isConnectable}
          sourcePosition={node.sourcePosition}
          targetPosition={node.targetPosition}
          dragging={dragging}
          dragHandle={node.dragHandle}
          zIndex={internals.z}
          parentId={node.parentId}
          {...nodeDimensions}
        />
      </Provider>
    </div>
  );
}

export default memo(NodeWrapper) as typeof NodeWrapper;
