// examples/vue/src/EasyConnect/FloatingConnectionLine.vue
<script lang="ts" setup>
import type { ConnectionLineProps } from '@xyflow/vue';
import { BaseEdge, getStraightPath } from '@xyflow/vue';
import { computed } from 'vue';

const props = defineProps<ConnectionLineProps>();

const edgePath = computed(() =>
  getStraightPath({
    sourceX: props.fromX - (props.fromNode.measured?.width ?? 0) / 2,
    sourceY: props.fromY,
    targetX: props.toX,
    targetY: props.toY,
  }),
);
</script>

<template>
  <g>
    <BaseEdge
      :style="{
        strokeWidth: 3,
        stroke: 'black',
      }"
      :path="edgePath[0]"
    />
    <circle :cx="toX" :cy="toY" fill="black" :r="3" stroke="black" :stroke-width="1.5" />
  </g>
</template>

// examples/react/src/examples/FloatingEdges/FloatingConnectionLine.tsx
import { getBezierPath, ConnectionLineComponentProps, InternalNode } from '@xyflow/react';

import { getEdgeParams } from './utils';

function FloatingConnectionLine({ toX, toY, fromPosition, toPosition, fromNode }: ConnectionLineComponentProps) {
  if (!fromNode) {
    return null;
  }

  const targetNode = {
    id: 'connection-target',
    width: 1,
    height: 1,
    position: { x: toX, y: toY },
  } as InternalNode;

  const { sx, sy } = getEdgeParams(fromNode, targetNode);

  const [path] = getBezierPath({
    sourceX: sx,
    sourceY: sy,
    sourcePosition: fromPosition,
    targetPosition: toPosition,
    targetX: toX,
    targetY: toY,
  });

  return (
    <g>
      <path fill="none" stroke="#222" strokeWidth={1.5} className="animated" d={path} />
      <circle cx={toX} cy={toY} fill="#fff" r={3} stroke="#222" strokeWidth={1.5} />
    </g>
  );
}

export default FloatingConnectionLine;
