// packages/core/src/components/EdgeLabelRenderer/index.tsx
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useStore } from '../../hooks/useStore';
import { ReactFlowState } from '../../types';

const selector = (s: ReactFlowState) => s.domNode?.querySelector('.react-flow__edgelabel-renderer');

function EdgeLabelRenderer({ children }: { children: ReactNode }) {
  const edgeLabelRenderer = useStore(selector);

  if (!edgeLabelRenderer) {
    return null;
  }

  return createPortal(children, edgeLabelRenderer);
}

export default EdgeLabelRenderer;

// packages/solidjs/src/components/EdgeLabelRenderer/index.tsx

import { useStore } from '../../hooks/useStore';
import type { SolidFlowState } from '../../types';
import { Portal } from 'solid-js/web';
import { ParentProps, Show } from 'solid-js';

const selector = (s: SolidFlowState) => () => s.domNode.get()?.querySelector('.react-flow__edgelabel-renderer');

export function EdgeLabelRenderer(p: ParentProps) {
  const edgeLabelRenderer = useStore(selector);

  return (
    <Show when={edgeLabelRenderer()}>
      {(el) => {
        return <Portal mount={el()}>{p.children}</Portal>;
      }}
    </Show>
  );
}
