// packages/solidjs/src/additional-components/NodeToolbar/NodeToolbarPortal.tsx
import type { SolidFlowState } from '../../types';
import { useStore } from '../../hooks/useStore';
import { Portal } from 'solid-js/web';
import { ParentProps, Show } from 'solid-js';

const selector = (state: SolidFlowState) => () => state.domNode.get()?.querySelector('.react-flow__renderer');

export function NodeToolbarPortal(p: ParentProps) {
  const wrapperRef = useStore(selector);

  return <Show when={wrapperRef()}>
    {(el) => {
      return <Portal mount={el()}>{p.children}</Portal>;
    }}
  </Show>;
}

// packages/react/src/additional-components/NodeToolbar/NodeToolbarPortal.tsx
import { ReactNode } from 'react';
import { createPortal } from 'react-dom';

import type { ReactFlowState } from '../../types';
import { useStore } from '../../hooks/useStore';

const selector = (state: ReactFlowState) => state.domNode?.querySelector('.react-flow__renderer');

export function NodeToolbarPortal({ children }: { children: ReactNode }) {
  const wrapperRef = useStore(selector);

  if (!wrapperRef) {
    return null;
  }

  return createPortal(children, wrapperRef);
}
