// packages/svelte/src/lib/container/EdgeRenderer.svelte
<script lang="ts"> 
  type EdgePositions = {
    sourceX: number;
    sourceY: number;
    targetX: number;
    targetY: number;
  }

  import Edge from '$lib/components/edges/BaseEdge.svelte';
  import { useStore } from '$lib/store';
	import { type NodeHandleBounds, type Rect, type Node, type HandleElement, Position, type XYPosition } from '@reactflow/core';
  import { internalsSymbol } from '@reactflow/core';

  const { edgesStore, widthStore, heightStore, nodesStore } = useStore();

  function getNodeData(node?: Node): [Rect, NodeHandleBounds | null, boolean] {
    const handleBounds = node?.[internalsSymbol]?.handleBounds || null;

    const isValid =
      handleBounds &&
      node?.width &&
      node?.height &&
      typeof node?.positionAbsolute?.x !== 'undefined' &&
      typeof node?.positionAbsolute?.y !== 'undefined';

    return [
      {
        x: node?.positionAbsolute?.x || 0,
        y: node?.positionAbsolute?.y || 0,
        width: node?.width || 0,
        height: node?.height || 0,
      },
      handleBounds,
      !!isValid,
    ];
  }

  function getHandlePosition(position: Position, nodeRect: Rect, handle: HandleElement | null = null): XYPosition {
    const x = (handle?.x || 0) + nodeRect.x;
    const y = (handle?.y || 0) + nodeRect.y;
    const width = handle?.width || nodeRect.width;
    const height = handle?.height || nodeRect.height;

    switch (position) {
      case Position.Top:
        return {
          x: x + width / 2,
          y,
        };
      case Position.Right:
        return {
          x: x + width,
          y: y + height / 2,
        };
      case Position.Bottom:
        return {
          x: x + width / 2,
          y: y + height,
        };
      case Position.Left:
        return {
          x,
          y: y + height / 2,
        };
    }
  }

  function getHandle(bounds: HandleElement[], handleId?: string | null): HandleElement | null {
    if (!bounds) {
      return null;
    }

    if (handleId) {
      return bounds.find((d) => d.id === handleId)!;
    } else if (bounds.length === 1) {
      return bounds[0];
    }

    return null;
  }

  function getEdgePositions(
    sourceNodeRect: Rect,
    sourceHandle: HandleElement,
    sourcePosition: Position,
    targetNodeRect: Rect,
    targetHandle: HandleElement,
    targetPosition: Position
  ): EdgePositions {
    const sourceHandlePos = getHandlePosition(sourcePosition, sourceNodeRect, sourceHandle);
    const targetHandlePos = getHandlePosition(targetPosition, targetNodeRect, targetHandle);

    return {
      sourceX: sourceHandlePos.x,
      sourceY: sourceHandlePos.y,
      targetX: targetHandlePos.x,
      targetY: targetHandlePos.y,
    };
  };

  let edgesWithData: any = [];

  $: {
    $nodesStore
    edgesWithData = $edgesStore.map((edge) => {
      const sourceNode = $nodesStore.find((node) => node.id === edge.source);
      const targetNode = $nodesStore.find((node) => node.id === edge.target);
      const [sourceNodeRect, sourceHandleBounds, sourceIsValid] = getNodeData(sourceNode);
      const [targetNodeRect, targetHandleBounds, targetIsValid] = getNodeData(targetNode);

      if (!sourceIsValid || !targetIsValid) {
        return null;
      }

      let edgeType = edge.type || 'default';

      const targetNodeHandles = targetHandleBounds!.target;
      const sourceHandle = getHandle(sourceHandleBounds!.source!, edge.sourceHandle);
      const targetHandle = getHandle(targetNodeHandles!, edge.targetHandle);
      const sourcePosition = sourceHandle?.position || Position.Bottom;
      const targetPosition = targetHandle?.position || Position.Top;

      if (!sourceHandle || !targetHandle) {
        return null;
      }


      const { sourceX, sourceY, targetX, targetY } = getEdgePositions(
        sourceNodeRect,
        sourceHandle,
        sourcePosition,
        targetNodeRect,
        targetHandle,
        targetPosition
      );


      return {
        id: edge.id,
        type: edgeType,
        sourceX,
        sourceY,
        targetX,
        targetY
      };
    })
  }
 </script>

<svg
  width={$widthStore}
  height={$heightStore}
  class="react-flow__edges react-flow__container"
>
  {#each edgesWithData as edge}
    {#if edge}
      <Edge {...edge} />
    {/if}
  {/each}
</svg>

<style>
  .react-flow__edges {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
    pointer-events: none;
  }
</style>

// src/container/EdgeRenderer/index.tsx
import React, { memo, SVGAttributes } from 'react';

import { useStoreState } from '../../store/hooks';
import ConnectionLine from '../../components/ConnectionLine/index';
import { isEdge } from '../../utils/graph';
import { XYPosition, Position, Edge, Node, ElementId, Transform } from '../../types';

interface EdgeRendererProps {
  width: number;
  height: number;
  edgeTypes: any;
  connectionLineStyle?: SVGAttributes<{}>;
  connectionLineType?: string;
  onElementClick?: () => void;
};

interface EdgeRendererState {
  nodes: Node[];
  edges: Edge[];
  transform: Transform;
  selectedElements: any;
  connectionSourceId: ElementId | null;
  position: XYPosition;
};

interface HandleElement {
  height: number;
  id?: ElementId;
  position: Position;
  width: number;
  x: number;
  y: number;
};

function getHandlePosition(position: Position, node: Node, handle: any = null) {
  if (!handle) {
    switch (position) {
      case 'top': return {
        x: node.__rg.width / 2,
        y: 0
      };
      case 'right': return {
        x: node.__rg.width,
        y: node.__rg.height / 2
      };
      case 'bottom': return {
        x: node.__rg.width / 2,
        y: node.__rg.height
      };
      case 'left': return {
        x: 0,
        y: node.__rg.height / 2
      };
    }

    return null;
  }

  switch (position) {
    case 'top': return {
      x: handle.x + (handle.width / 2),
      y: handle.y
    };
    case 'right': return {
      x: handle.x + handle.width,
      y: handle.y + (handle.height / 2)
    };
    case 'bottom': return {
      x: handle.x + (handle.width / 2),
      y: handle.y + handle.height
    };
    case 'left': return {
      x: handle.x,
      y: handle.y + (handle.height / 2)
    };
  }
}

function getHandle(bounds, handleId): HandleElement | null {
  let handle = null;

  if (!bounds) {
    return null;
  }

  // there is no handleId when there are no multiple handles/ handles with ids
  // so we just pick the first one
  if (bounds.length === 1 || !handleId) {
    handle = bounds[0];
  } else if (handleId) {
    handle = bounds.find(d => d.id === handleId);
  }

  return handle;
}

function getEdgePositions({ sourceNode, sourceHandle, sourcePosition, targetNode, targetHandle, targetPosition }) {
  const sourceHandlePos = getHandlePosition(sourcePosition, sourceNode, sourceHandle)
  const sourceX = sourceNode.__rg.position.x + sourceHandlePos.x;
  const sourceY = sourceNode.__rg.position.y + sourceHandlePos.y;

  const targetHandlePos = getHandlePosition(targetPosition, targetNode, targetHandle);
  const targetX = targetNode.__rg.position.x + targetHandlePos.x;
  const targetY = targetNode.__rg.position.y + targetHandlePos.y;

  return {
    sourceX, sourceY, targetX, targetY
  };
}

function renderEdge(edge: Edge, props: EdgeRendererProps, state: EdgeRendererState) {
  const edgeType = edge.type || 'default';

  const hasSourceHandleId = edge.source.includes('__');
  const hasTargetHandleId = edge.target.includes('__');

  const sourceId = hasSourceHandleId ? edge.source.split('__')[0] : edge.source;
  const targetId = hasTargetHandleId ? edge.target.split('__')[0] : edge.target;

  const sourceHandleId = hasSourceHandleId ? edge.source.split('__')[1] : null;
  const targetHandleId = hasTargetHandleId ? edge.target.split('__')[1] : null;

  const sourceNode = state.nodes.find(n => n.id === sourceId);
  const targetNode = state.nodes.find(n => n.id === targetId);

  if (!sourceNode) {
    throw new Error(`couldn't create edge for source id: ${sourceId}`);
  }

  if (!targetNode) {
    throw new Error(`couldn't create edge for target id: ${targetId}`);
  }

  const EdgeComponent = props.edgeTypes[edgeType] || props.edgeTypes.default;
  const sourceHandle = getHandle(sourceNode.__rg.handleBounds.source, sourceHandleId);
  const targetHandle = getHandle(targetNode.__rg.handleBounds.target, targetHandleId);
  const sourcePosition = sourceHandle ? sourceHandle.position : 'bottom';
  const targetPosition = targetHandle ? targetHandle.position : 'top';

  const { sourceX, sourceY, targetX, targetY } = getEdgePositions({
    sourceNode, sourceHandle, sourcePosition,
    targetNode, targetHandle, targetPosition
  });
  const selected = state.selectedElements
    .filter(isEdge)
    .find(elm => elm.source === sourceId && elm.target === targetId);

  return (
    <EdgeComponent
      key={edge.id}
      id={edge.id}
      type={edge.type}
      onClick={props.onElementClick}
      selected={selected}
      animated={edge.animated}
      style={edge.style}
      source={sourceId}
      target={targetId}
      sourceHandleId={sourceHandleId}
      targetHandleId={targetHandleId}
      sourceX={sourceX}
      sourceY={sourceY}
      targetX={targetX}
      targetY={targetY}
      sourcePosition={sourcePosition}
      targetPosition={targetPosition}
    />
  );
}

const EdgeRenderer = memo(({
  width, height, connectionLineStyle, connectionLineType, ...rest
}: EdgeRendererProps) => {
  const state: EdgeRendererState = useStoreState(s => ({
    nodes: s.nodes,
    edges: s.edges,
    transform: s.transform,
    selectedElements: s.selectedElements,
    connectionSourceId: s.connectionSourceId,
    position: s.connectionPosition
  }));
  if (!width) {
    return null;
  }

  const { transform, edges, nodes, connectionSourceId, position } = state;
  const transformStyle = `translate(${transform[0]},${transform[1]}) scale(${transform[2]})`;

  return (
    <svg
      width={width}
      height={height}
      className="react-flow__edges"
    >
      <g transform={transformStyle}>
        {edges.map(e => renderEdge(e, { width, height, connectionLineStyle, connectionLineType, ...rest }, state))}
        {connectionSourceId && (
          <ConnectionLine
            nodes={nodes}
            connectionSourceId={connectionSourceId}
            connectionPositionX={position.x}
            connectionPositionY={position.y}
            transform={transform}
            connectionLineStyle={connectionLineStyle}
            connectionLineType={connectionLineType}
          />
        )}
      </g>
    </svg>
  );
});

EdgeRenderer.displayName = 'EdgeRenderer';

export default EdgeRenderer;
