// packages/solidjs/src/container/GraphView/useStylesLoadedWarning.ts
import { createEffect } from 'solid-js';
import { errorMessages } from '@xyflow/system';

import { useStoreApi } from '../../hooks/useStore';

export function useStylesLoadedWarning() {
  const store = useStoreApi();
  let checked = false;

  createEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      if (!checked) {
        const pane = document.querySelector('.react-flow__pane');

        if (pane && !(window.getComputedStyle(pane).zIndex === '1')) {
          store.onError.get()?.('013', errorMessages['error013']('solid'));
        }

        checked = true;
      }
    }
  });
}

// packages/react/src/container/GraphView/useStylesLoadedWarning.ts
import { useEffect, useRef } from 'react';
import { errorMessages } from '@xyflow/system';

import { useStoreApi } from '../../hooks/useStore';

export function useStylesLoadedWarning() {
  const store = useStoreApi();
  const checked = useRef(false);

  if (process.env.NODE_ENV === 'development') {
    useEffect(() => {
      if (!checked.current) {
        const pane = document.querySelector('.react-flow__pane');

        if (pane && !(window.getComputedStyle(pane).zIndex === '1')) {
          store.getState().onError?.('013', errorMessages['error013']('react'));
        }

        checked.current = true;
      }
    }, []);
  }
}
