// src/components/EdgeLabelRenderer/index.tsx
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useStore } from '../../store';
import { ReactFlowState } from '../../types';

const selector = (s: ReactFlowState) => s.domNode?.querySelector('.react-flow__edgelabel-renderer');

function EdgeLabelRenderer({ children }: { children: ReactNode }) {
  const edgeLabelRenderer = useStore(selector);

  if (!edgeLabelRenderer) {
    return null;
  }

  return createPortal(children, edgeLabelRenderer);
}

export default EdgeLabelRenderer;

// packages/svelte/src/lib/components/EdgeLabelRenderer/EdgeLabelRenderer.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import portal from '$lib/actions/portal';
  import { useStore } from '$lib/store';

  const store = useStore();

  let { children }: { children?: Snippet } = $props();
</script>

<div use:portal={{ target: '.svelte-flow__edgelabel-renderer', domNode: store.domNode }}>
  {@render children?.()}
</div>
