// packages/svelte/src/lib/plugins/Minimap/Minimap.svelte
<script lang="ts">
  import cc from 'classcat';
	import type { PanelPosition, Rect, Node } from '@reactflow/system';
	import { getBoundsOfRects, getNodePositionWithOrigin, getRectOfNodes } from '@reactflow/utils';

  import { useStore } from '$lib/store';
	import Panel from '$lib/container/Panel/index.svelte';
  import MinimapNode from './MinimapNode.svelte';

  let position: PanelPosition = 'bottom-right';
  let ariaLabel: string = 'Mini map';
  let className: string = '';
  let style: Record<string, unknown> = {};
  let nodeStrokeColor: string = 'transparent';
  let nodeColor: string = '#e2e2e2';
  let nodeClassName: string = '';
  let nodeBorderRadius: number = 5;
  let nodeStrokeWidth: number = 2;
  let bgColor: string = '#fff';
  let maskColor: string = 'rgb(240, 240, 240, 0.6)';
  let maskStrokeColor: string = 'none';
  let maskStrokeWidth: number = 1;
  export { className as class };

  const defaultWidth = 200;
  const defaultHeight = 150;
  const { nodesStore, transformStore, widthStore, heightStore, nodeOriginStore, idStore } = useStore();

  type GetMiniMapNodeAttribute = (node: Node) => string;
  const getAttrFunction = (func: any): GetMiniMapNodeAttribute => (func instanceof Function ? func : () => func);
  const nodeColorFunc = getAttrFunction(nodeColor);
  const nodeStrokeColorFunc = getAttrFunction(nodeStrokeColor);
  const nodeClassNameFunc = getAttrFunction(nodeClassName);
  const shapeRendering = typeof window === 'undefined' || !!window.chrome ? 'crispEdges' : 'geometricPrecision';
  const labelledBy = `react-flow__minimap-desc-${$idStore}`;
  
  $: viewBB = {
    x: -$transformStore[0] / $transformStore[2],
    y: -$transformStore[1] / $transformStore[2],
    width: $widthStore / $transformStore[2],
    height: $heightStore / $transformStore[2],
  } as Rect;
  $: boundingRect = $nodesStore.length > 0 ? getBoundsOfRects(getRectOfNodes($nodesStore, $nodeOriginStore), viewBB) : viewBB
  $: elementWidth = (style?.width as number) ?? defaultWidth;
  $: elementHeight = (style?.height as number) ?? defaultHeight;  
  $: scaledWidth = boundingRect.width / elementWidth;
  $: scaledHeight = boundingRect.height / elementHeight;
  $: viewScale = Math.max(scaledWidth, scaledHeight);
  $: viewWidth = viewScale * elementWidth;
  $: viewHeight = viewScale * elementHeight;
  $: offset = 5 * viewScale;
  $: x = boundingRect.x - (viewWidth - boundingRect.width) / 2 - offset;
  $: y = boundingRect.y - (viewHeight - boundingRect.height) / 2 - offset;
  $: width = viewWidth + offset * 2;
  $: height = viewHeight + offset * 2;
</script>

<Panel position={position} class={cc(['react-flow__minimap', className])} style={`background-color: ${bgColor};`}>
  <svg
    width={elementWidth}
    height={elementHeight}
    viewBox={`${x} ${y} ${width} ${height}`}
    role="img"
    aria-labelledby={labelledBy}
  >
    {#if ariaLabel}<title id={labelledBy}>{ariaLabel}</title>{/if}

    {#each $nodesStore as node}
      {#if node.width && node.height}
        {@const pos = getNodePositionWithOrigin(node, $nodeOriginStore).positionAbsolute}
        <MinimapNode
          x={pos.x}
          y={pos.y}
          width={node.width}
          height={node.height}
          color={nodeColorFunc(node)}
          borderRadius={nodeBorderRadius}
          strokeColor={nodeStrokeColorFunc(node)}
          strokeWidth={nodeStrokeWidth}
          shapeRendering={shapeRendering}
          class={nodeClassNameFunc(node)}
          style={{}}
        />
      {/if}
    {/each}
    <path
      class="react-flow__minimap-mask"
      d={`M${x - offset},${y - offset}h${width + offset * 2}v${height + offset * 2}h${-width - offset * 2}z
    M${viewBB.x},${viewBB.y}h${viewBB.width}v${viewBB.height}h${-viewBB.width}z`}
      fill={maskColor}
      fill-rule="evenodd"
      stroke={maskStrokeColor}
      stroke-width={maskStrokeWidth}
      pointer-events="none"
    />
  </svg>
</Panel>

// packages/interactive-minimap/src/MiniMap.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { memo, useEffect, useRef } from 'react';
import cc from 'classcat';
import shallow from 'zustand/shallow';
import { zoom, D3ZoomEvent } from 'd3-zoom';
import { select } from 'd3-selection';
import { useStore, getRectOfNodes, ReactFlowState, Rect, Panel, getBoundsOfRects } from '@reactflow/core';

import MiniMapNode from './MiniMapNode';
import { MiniMapProps, GetMiniMapNodeAttribute } from './types';

declare const window: any;

const defaultWidth = 200;
const defaultHeight = 150;

const selector = (s: ReactFlowState) => {
  const nodes = Array.from(s.nodeInternals.values());
  const viewBB: Rect = {
    x: -s.transform[0] / s.transform[2],
    y: -s.transform[1] / s.transform[2],
    width: s.width / s.transform[2],
    height: s.height / s.transform[2],
  };

  return {
    nodes: nodes.filter((node) => !node.hidden && node.width && node.height),
    viewBB,
    boundingRect: nodes.length > 0 ? getBoundsOfRects(getRectOfNodes(nodes), viewBB) : viewBB,
    rfId: s.rfId,
  };
};

const getAttrFunction = (func: any): GetMiniMapNodeAttribute => (func instanceof Function ? func : () => func);

const ARIA_LABEL_KEY = 'react-flow__minimap-desc';

function MiniMap({
  style,
  className,
  nodeStrokeColor = '#555',
  nodeColor = '#fff',
  nodeClassName = '',
  nodeBorderRadius = 5,
  nodeStrokeWidth = 2,
  maskColor = 'rgb(240, 242, 243, 0.7)',
  position = 'bottom-right',
}: MiniMapProps) {
  const svg = useRef<SVGSVGElement>(null);
  const { boundingRect, viewBB, nodes, rfId } = useStore(selector, shallow);
  const elementWidth = (style?.width as number) ?? defaultWidth;
  const elementHeight = (style?.height as number) ?? defaultHeight;
  const nodeColorFunc = getAttrFunction(nodeColor);
  const nodeStrokeColorFunc = getAttrFunction(nodeStrokeColor);
  const nodeClassNameFunc = getAttrFunction(nodeClassName);
  const scaledWidth = boundingRect.width / elementWidth;
  const scaledHeight = boundingRect.height / elementHeight;
  const viewScale = Math.max(scaledWidth, scaledHeight);
  const viewWidth = viewScale * elementWidth;
  const viewHeight = viewScale * elementHeight;
  const offset = 5 * viewScale;
  const x = boundingRect.x - (viewWidth - boundingRect.width) / 2 - offset;
  const y = boundingRect.y - (viewHeight - boundingRect.height) / 2 - offset;
  const width = viewWidth + offset * 2;
  const height = viewHeight + offset * 2;
  const shapeRendering = typeof window === 'undefined' || !!window.chrome ? 'crispEdges' : 'geometricPrecision';
  const labelledBy = `${ARIA_LABEL_KEY}-${rfId}`;

  useEffect(() => {
    const d3ZoomInstance = zoom();
    const selection = select(svg.current as Element).call(d3ZoomInstance);

    d3ZoomInstance.on('zoom', (event: D3ZoomEvent<HTMLDivElement, any>) => {
      console.log(event);
    });
  }, []);

  return (
    <Panel position={position} style={style} className={cc(['react-flow__minimap', className])}>
      <svg
        width={elementWidth}
        height={elementHeight}
        viewBox={`${x} ${y} ${width} ${height}`}
        role="img"
        aria-labelledby={labelledBy}
        ref={svg}
      >
        <title id={labelledBy}>React Flow mini map</title>
        {nodes.map((node) => {
          return (
            <MiniMapNode
              key={node.id}
              x={node.positionAbsolute?.x ?? 0}
              y={node.positionAbsolute?.y ?? 0}
              width={node.width!}
              height={node.height!}
              style={node.style}
              className={nodeClassNameFunc(node)}
              color={nodeColorFunc(node)}
              borderRadius={nodeBorderRadius}
              strokeColor={nodeStrokeColorFunc(node)}
              strokeWidth={nodeStrokeWidth}
              shapeRendering={shapeRendering}
            />
          );
        })}
        <path
          className="react-flow__minimap-mask"
          d={`M${x - offset},${y - offset}h${width + offset * 2}v${height + offset * 2}h${-width - offset * 2}z
        M${viewBB.x},${viewBB.y}h${viewBB.width}v${viewBB.height}h${-viewBB.width}z`}
          fill={maskColor}
          fillRule="evenodd"
        />
      </svg>
    </Panel>
  );
}

MiniMap.displayName = 'MiniMap';

export default memo(MiniMap);
