// packages/controls/src/Controls.tsx
import { memo, FC, useEffect, useState, PropsWithChildren } from 'react';
import cc from 'classcat';
import { useStore, useStoreApi, useReactFlow, ReactFlowState, Panel } from '@react-flow/core';

import PlusIcon from './Icons/Plus';
import MinusIcon from './Icons/Minus';
import FitviewIcon from './Icons/FitView';
import LockIcon from './Icons/Lock';
import UnlockIcon from './Icons/Unlock';
import ControlButton from './ControlButton';

import { ControlProps } from './types';

const isInteractiveSelector = (s: ReactFlowState) => s.nodesDraggable && s.nodesConnectable && s.elementsSelectable;

const Controls: FC<PropsWithChildren<ControlProps>> = ({
  style,
  showZoom = true,
  showFitView = true,
  showInteractive = true,
  fitViewOptions,
  onZoomIn,
  onZoomOut,
  onFitView,
  onInteractiveChange,
  className,
  children,
  position = 'bottom-left',
}) => {
  const store = useStoreApi();
  const [isVisible, setIsVisible] = useState<boolean>(false);
  const isInteractive = useStore(isInteractiveSelector);
  const { zoomIn, zoomOut, fitView } = useReactFlow();

  useEffect(() => {
    setIsVisible(true);
  }, []);

  if (!isVisible) {
    return null;
  }

  const onZoomInHandler = () => {
    zoomIn();
    onZoomIn?.();
  };

  const onZoomOutHandler = () => {
    zoomOut();
    onZoomOut?.();
  };

  const onFitViewHandler = () => {
    fitView(fitViewOptions);
    onFitView?.();
  };

  const onToggleInteractivity = () => {
    store.setState({
      nodesDraggable: !isInteractive,
      nodesConnectable: !isInteractive,
      elementsSelectable: !isInteractive,
    });

    onInteractiveChange?.(!isInteractive);
  };

  return (
    <Panel className={cc(['react-flow__controls', className])} position={position} style={style}>
      {showZoom && (
        <>
          <ControlButton
            onClick={onZoomInHandler}
            className="react-flow__controls-zoomin"
            title="zoom in"
            aria-label="zoom in"
          >
            <PlusIcon />
          </ControlButton>
          <ControlButton
            onClick={onZoomOutHandler}
            className="react-flow__controls-zoomout"
            title="zoom out"
            aria-label="zoom out"
          >
            <MinusIcon />
          </ControlButton>
        </>
      )}
      {showFitView && (
        <ControlButton
          className="react-flow__controls-fitview"
          onClick={onFitViewHandler}
          title="fit view"
          aria-label="fit view"
        >
          <FitviewIcon />
        </ControlButton>
      )}
      {showInteractive && (
        <ControlButton
          className="react-flow__controls-interactive"
          onClick={onToggleInteractivity}
          title="toggle interactivity"
          aria-label="toggle interactivity"
        >
          {isInteractive ? <UnlockIcon /> : <LockIcon />}
        </ControlButton>
      )}
      {children}
    </Panel>
  );
};

Controls.displayName = 'Controls';

export default memo(Controls);

// packages/svelte/src/lib/plugins/Controls/index.svelte
<script lang="ts">
  import Panel from '$lib/container/Panel.svelte';
	import type { PanelPosition } from '@reactflow/system';

  import ControlButton from './ControlButton.svelte';
  import PlusIcon from './Icons/Plus.svelte';
  import MinusIcon from './Icons/Minus.svelte';
  import FitViewIcon from './Icons/Fit.svelte';
  import LockIcon from './Icons/Lock.svelte';
  import UnlockIcon from './Icons/Unlock.svelte';

  export let position: PanelPosition = 'bottom-left';
  export let showZoom = true;
  export let showFitView = true;
  export let showInteractive = true;

	import { useStore } from '$lib/store';

  const { zoomIn, zoomOut, fitView } = useStore();

  const isInteractive = true;

  const onZoomInHandler = () => {
    zoomIn();
  };

  const onZoomOutHandler = () => {
    zoomOut();
  };

  const onFitViewHandler = () => {
    fitView();
  };

  const onToggleInteractivity = () => {
    // store.setState({
    //   nodesDraggable: !isInteractive,
    //   nodesConnectable: !isInteractive,
    //   elementsSelectable: !isInteractive,
    // });

    // onInteractiveChange?.(!isInteractive);
  };

</script>

<Panel class="react-flow__controls" position={position}>
  {#if showZoom}
    <ControlButton
      on:click={onZoomInHandler}
      class="react-flow__controls-zoomin"
      title="zoom in"
      aria-label="zoom in"
    >
      <PlusIcon />
    </ControlButton>
    <svelte:component
      this={ControlButton}
      on:click={onZoomOutHandler}
      class="react-flow__controls-zoomout"
      title="zoom out"
      aria-label="zoom out"
    >
      <MinusIcon />
    </svelte:component>
  {/if}
  {#if showFitView}
    <svelte:component
      this={ControlButton}
      class="react-flow__controls-fitview"
      on:click={onFitViewHandler}
      title="fit view"
      aria-label="fit view"
    >
      <FitViewIcon />
    </svelte:component>
  {/if}
  {#if showInteractive}
    <svelte:component
      this={ControlButton}
      class="react-flow__controls-interactive"
      on:click={onToggleInteractivity}
      title="toggle interactivity"
      aria-label="toggle interactivity"
    >
      {#if isInteractive}<UnlockIcon />{:else}<LockIcon />{/if}
    </svelte:component>
  {/if}
</Panel>
