// packages/react/src/additional-components/MiniMap/MiniMapNode.tsx
import { memo } from 'react';
import cc from 'classcat';

import type { MiniMapNodeProps } from './types';

function MiniMapNode({
  id,
  x,
  y,
  width,
  height,
  style,
  color,
  strokeColor,
  strokeWidth,
  className,
  borderRadius,
  shapeRendering,
  selected,
  onClick,
}: MiniMapNodeProps) {
  const { background, backgroundColor } = style || {};
  const fill = (color || background || backgroundColor) as string;

  return (
    <rect
      className={cc(['react-flow__minimap-node', { selected }, className])}
      x={x}
      y={y}
      rx={borderRadius}
      ry={borderRadius}
      width={width}
      height={height}
      fill={fill}
      stroke={strokeColor}
      strokeWidth={strokeWidth}
      shapeRendering={shapeRendering}
      onClick={onClick ? (event) => onClick(event, id) : undefined}
    />
  );
}

export default memo(MiniMapNode);

// packages/vue/src/components/MiniMap/MiniMapNode.vue
<script setup lang="ts">
import type { MiniMapNodeEmits, MiniMapNodeProps } from './types';
import { inject, useAttrs } from 'vue';
import { Slots } from './types';

const props = defineProps<MiniMapNodeProps>();

const emits = defineEmits<MiniMapNodeEmits>();

const miniMapSlots = inject(Slots, {});

const attrs = useAttrs() as Record<string, any>;
</script>

<script lang="ts">
export default {
  name: 'MiniMapNode',
  compatConfig: { MODE: 3 },
  inheritAttrs: false,
};
</script>

<template>
  <template v-if="!hidden && dimensions.width !== 0 && dimensions.height !== 0">
    <component
      :is="miniMapSlots[`node-${props.type}`]"
      v-if="miniMapSlots[`node-${props.type}`]"
      v-bind="{ ...props, ...attrs }"
    />

    <rect
      v-else
      :id="id"
      v-bind="attrs"
      class="vue-flow__minimap-node"
      :class="{ selected, dragging }"
      :x="position.x"
      :y="position.y"
      :rx="borderRadius"
      :ry="borderRadius"
      :width="dimensions.width"
      :height="dimensions.height"
      :fill="color || (attrs.style?.background as string) || attrs.style?.backgroundColor"
      :stroke="strokeColor"
      :stroke-width="strokeWidth"
      :shape-rendering="shapeRendering"
      @click="emits('click', $event)"
      @dblclick="emits('dblclick', $event)"
      @mouseenter="emits('mouseenter', $event)"
      @mousemove="emits('mousemove', $event)"
      @mouseleave="emits('mouseleave', $event)"
    />
  </template>
</template>
