// examples/svelte/src/routes/examples/node-toolbar/SelectedNodesToolbar.svelte
<script lang="ts">
	import { NodeToolbar, useNodes } from '@xyflow/svelte';

	const nodes = useNodes();

	$: selectedNodeIds = $nodes.filter((node) => node.selected).map((node) => node.id);
	$: isVisible = selectedNodeIds.length > 1;
</script>

<NodeToolbar nodeId={selectedNodeIds} {isVisible}>
	<button>Selection action</button>
</NodeToolbar>

// examples/vite-app/src/examples/NodeToolbar/SelectedNodesToolbar.tsx
import { NodeToolbar, ReactFlowState, useStore } from '@xyflow/react';

const selectedNodesSelector = (state: ReactFlowState) =>
  state.nodes.filter((node) => node.selected).map((node) => node.id);

export default function SelectedNodesToolbar() {
  const selectedNodeIds = useStore(selectedNodesSelector);
  const isVisible = selectedNodeIds.length > 1;

  return (
    <NodeToolbar nodeId={selectedNodeIds} isVisible={isVisible}>
      <button>Selection action</button>
    </NodeToolbar>
  );
}
