// packages/svelte/src/lib/plugins/Minimap/MinimapNode.svelte
<script lang="ts">
  import cc from 'classcat';

  export let x: number;
  export let y: number;
  export let width: number = 0;
  export let height: number = 0;
  export let borderRadius: number = 5;
  export let color: string;
  export let shapeRendering: string;
  export let strokeColor: string;
  export let strokeWidth: number = 2;
  export let style: Record<string, string>;
  let className: string = '';
  export { className as class };

  const { background, backgroundColor } = style || {};
  const fill = (color || background || backgroundColor) as string;
</script>

<rect
  class={cc(['react-flow__minimap-node', className])}
  {x}
  {y}
  rx={borderRadius}
  ry={borderRadius}
  {width}
  {height}
  {fill}
  stroke={strokeColor}
  stroke-width={strokeWidth}
  shape-rendering={shapeRendering}
/>

// packages/minimap/src/MiniMapNode.tsx
import { memo, CSSProperties } from 'react';
import cc from 'classcat';

interface MiniMapNodeProps {
  x: number;
  y: number;
  width: number;
  height: number;
  borderRadius: number;
  className: string;
  color: string;
  shapeRendering: string;
  strokeColor: string;
  strokeWidth: number;
  style?: CSSProperties;
}

const MiniMapNode = ({
  x,
  y,
  width,
  height,
  style,
  color,
  strokeColor,
  strokeWidth,
  className,
  borderRadius,
  shapeRendering,
}: MiniMapNodeProps) => {
  const { background, backgroundColor } = style || {};
  const fill = (color || background || backgroundColor) as string;

  return (
    <rect
      className={cc(['react-flow__minimap-node', className])}
      x={x}
      y={y}
      rx={borderRadius}
      ry={borderRadius}
      width={width}
      height={height}
      fill={fill}
      stroke={strokeColor}
      strokeWidth={strokeWidth}
      shapeRendering={shapeRendering}
    />
  );
};

MiniMapNode.displayName = 'MiniMapNode';

export default memo(MiniMapNode);
